### ISSUE TITLE
It's not working for me. It seems to be adding endpoints to each custom post type and ACF fields.

### ISSUE THREAD

**Issue by myuseringithub** [airesvsg/acf-to-rest-api#1]
http://dev.dentrist.com/wp-json/acf/v2/article :

{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
______________________________________

When checking http://dev.dentrist.com/wp-json/acf/v2/ :

{
  "namespace": "acf/v2",
  "routes": {
    "/acf/v2": {
      "namespace": "acf/v2",
      "methods": [
        "GET"
      ],
      "endpoints": [
        {
          "methods": [
            "GET"
          ],
          "args": {
            "namespace": {
              "required": false,
              "default": "acf/v2"
            },
            "context": {
              "required": false,
              "default": "view"
            }
          }
        }
      ],
      "_links": {
        "self": "http://dev.dentrist.com/wp-json/acf/v2"
      }
    },

etc .....

    "/acf/v2/article/(?P<id>\d+)/?": {
      "namespace": "acf/v2",
      "methods": [
        "GET",
        "POST",
        "PUT",
        "PATCH"
      ],
      "endpoints": [
        {
          "methods": [
            "GET"
          ],
          "args": []
        },
        {
          "methods": [
            "POST",
            "PUT",
            "PATCH"
          ],
          "args": []
        }
      ]
    },

etc .....

While the regular WP REST API request works for GET: 
http://dev.dentrist.com/wp-json/wp/v2/article
Thanks

**Comment by myuseringithub** [comment]
Should I add any extra code to the functions.php ? 
I added this code to turn show_in_rest to true for custom post types (using Types plugin by wp-types): 

//******** Add show_in_rest for wp-types plugins to show custom post types in Wordpress REST API V2**********//
add_filter( 'wpcf_type', 'add_show_in_rest_func', 10, 2);
function add_show_in_rest_func($data, $post_type) {
    //if(in_array($post_type, $post_types_all)){
        $data['show_in_rest'] = true;
    //}
    return $data;
}

**Comment by myuseringithub** [comment]
I figured that calling specific ID does return results: 
http://dev.dentrist.com/wp-json/acf/v2/article/2354

So should I use it in combination with /wp-json/wp/v2 by means of: 
/wp-json/wp/v2 for getting the default fields, and for editing them only.
while 
/wp-json/acf/v2 will be used for custom fields viewing and editing.

Is that the correct way to use it ? So I should run each time 2 json requests and try to combine them ?

**Comment by airesvsg** [comment]
Hi @myuseringithub,

`/wp-json/wp/v2/article/2354`
You will get the full response of the post with the ACF Fields.
![WP Enpoint](http://airesgoncalves.com.br/screenshot/acf-to-rest-api/issues/wp-endpoint.png)

`/wp-json/acf/v2/article/2354`
You will get only ACF Fields.

![ACF Endpoint](http://airesgoncalves.com.br/screenshot/acf-to-rest-api/issues/acf-endpoint.png)

To edit all endpoint works.

**Comment by myuseringithub** [comment]
Excellent ! I'm new to using JSON API sorry for the obvious questions.
Thank you great work.

**Comment by airesvsg** [comment]
:+1:
