### ISSUE TITLE
Adding user custom fields to the reponse

### ISSUE THREAD

**Issue by Pxlat** [airesvsg/acf-to-rest-api#10]
Hi, Thanks for your great code,

#9  Does this solution work also to get fields from /users/ ?

**Comment by airesvsg** [comment]
Hi @Pxlat,

Yes, this solution works too.

See below the example:
```PHP
add_filter( 'acf/rest_api/user/get_fields', function( $data, $request, $response ) {
	if ( $response instanceof WP_REST_Response ) {
		$data = $response->get_data();
	}

	if( isset( $data['acf'] ) ) {
		$data['acf']['my_fields']->acf = get_fields( 1 );	 // get fieldsa from post with id #1		
	}	
	
	return $data;
}, 10, 3 );
```

Whats fields do you want to append in your response?

**Comment by Pxlat** [comment]
I want to append the field "logo" from this endpoint http://s15695.p20.sites.pressdns.com/wp-json/wp/v2/users/  into this endpoint http://s15695.p20.sites.pressdns.com/wp-json/wp/v2/wimo-order/  in "acf.retailer"

**Comment by airesvsg** [comment]
Hi @Pxlat,

Please, replace the filter of isseu #9 by bellow code:

```PHP
add_filter( 'acf/rest_api/wimo-order/get_fields', function( $data, $request, $response ) {
    if ( $response instanceof WP_REST_Response ) {
        $data = $response->get_data();
    }

    if( isset( $data['acf'] ) ) {
		$data['acf']['shipping_address']->acf = get_fields( $data['acf']['shipping_address']->ID );
		
		// only logo
		// $data['acf']['retailer']->logo    = get_field( 'logo', 'user_' . $data['acf']['retailer']->ID );

		// all acf fields
		$data['acf']['retailer']->acf         = get_fields( $data['acf']['retailer']->ID );
    }   

    return $data;
}, 10, 3 );
```

**Comment by Pxlat** [comment]
Didn't work..do you think this has anything to do with Auth? http://s15695.p20.sites.pressdns.com/wp-json/wp/v2/users/5

**Comment by airesvsg** [comment]
In the plugin ( wp rest api ) has some conditions for you get data from users.

See: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L199

**Comment by airesvsg** [comment]
Hi @Pxlat,
I'll close this issue, because the error isn't in the plugin.
If you want some help, write an email for me: airesvsg@gmail.com
Thanks

**Comment by airesvsg** [comment]
Hi @Pxlat,

please, check that the filter below will work:
```PHP
add_filter( 'acf/rest_api/item_permissions/get', function( $permission, $request, $type ) {
    if ( 'user' == $type && method_exists( $request, 'get_param' ) && get_current_user_id() == $request->get_param( 'id' ) ) {
        return true;
    }
    return $permission;
}, 10, 3 );
```
Thanks
