### ISSUE TITLE
ACF Date Time Picker-field not accessible via REST API

### ISSUE THREAD

**Issue by OlliGranlund** [airesvsg/acf-to-rest-api#103]
Hey

It seems like the Date Time Picker-field value is not accessible via REST API. I guess this is due to the field being quite new...

**Date Time Picker:** https://www.advancedcustomfields.com/resources/date-time-picker/
**Added in version 5.3.9**

**Comment by airesvsg** [comment]
Hi @OlliGranlund,
This field is the same as the others.

![datetime-admin](https://cloud.githubusercontent.com/assets/396668/22782515/91de253a-eeae-11e6-973e-75fec2ca9cac.png)
![datetime-json](https://cloud.githubusercontent.com/assets/396668/22782520/94590898-eeae-11e6-9145-a3662dcd6a3d.png)

Thanks

**Comment by OlliGranlund** [comment]
You are so right. I spinned up a new VM with WP and installed only ACF Pro and ACF to REST API. The difference was that I created the fields but then added them via PHP and deleted the visual part in WP-admin. This still worked. We are working on another site where 4/5 ACF fields are visible via REST-API, it's only the Date-Time field that is missing. I guess I have to keep on debugging...
