### ISSUE TITLE
List all custom post_type contents with acf fields?

### ISSUE THREAD

**Issue by danielsailes** [airesvsg/acf-to-rest-api#104]
Just wondering if there's a way to list custom posts similar to:
http://{url}/wp-json/wp/v2/{post_type}/

I know that the plugin works per-id etc, but I'm trying to make a really lightweight to-do list style JS app hooked into WP via the WP API using custom post types and custom fields. The more efficient and lightweight way to get data for the list is to just get all the posts & their ACF data.
I could request all info individually, after doing a wp-json/wp/v2/{post_type}/, but that seems like a lot of network requests for 1 action, right?

Happy for any input/responses on this - I could just be thinking about this in the wrong way! I'm sure you's know how it is after staring at a screen for many hours haha

**Comment by danielsailes** [comment]
If not, i'll fork the project and see if I can come up with something - would be happy to help out :) 

Thanks for the plugin in general - helped me get very close to achieving this project in a short amount of time!

**Comment by airesvsg** [comment]
Hi @danielsailes,
In the current version it isn't available, but in the next version I'll release this feature.
![acf-endpoint](https://cloud.githubusercontent.com/assets/396668/22885356/308c5c9a-f1e0-11e6-9ad9-a197cbeb2c76.png)
Thanks

**Comment by danielsailes** [comment]
When is your v3 due out? Or is there a 'beta' I could test with, maybe?

**Comment by airesvsg** [comment]
This week I'll release in the Github.

**Comment by danielsailes** [comment]
Amazing, many thanks. Will keep an eye on the repo

**Comment by danielsailes** [comment]
Any update on the v3? Or anything I could test? 
This would be really useful for a project I'm wanting to work on

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api/releases/tag/3.0.0-beta
