### ISSUE TITLE
Post again: GET request from wp, only custom field posts needed

### ISSUE THREAD

**Issue by st-small** [airesvsg/acf-to-rest-api#105]
Hello! I had this trouble in September  (https://github.com/airesvsg/acf-to-rest-api/issues/66) and you helped me very good. But now (after updating my WordPress) I have the same one. Can you give me advice how I can skip this situation?!

I want to get filtered answer for request http://www.mysite.com/wp-json/wp/v2/posts?filter[meta_key]=offer&filter[meta_value]=1, but I have all products JSON in answer and don't mind any what I should to do...

Thank you very much.

**Comment by airesvsg** [comment]
Hi @st-small,
I'll test it today.
Thanks

**Comment by st-small** [comment]
@airesvsg Thank you for reply! Will wait, because my app become stupid and fetch all products from site... it takes a few minutes ))) it is very bad, all I need to wait your helpful! Thanks!

**Comment by airesvsg** [comment]
@st-small try it out: https://github.com/airesvsg/wp-rest-api-cache

**Comment by airesvsg** [comment]
Hi @st-small,
The filter `rest_query_vars` was removed, now I'm using the filter `rest_{type}_query`.
```PHP
add_filter( 'rest_post_query', function( $args, $request ) {
  $offer = $request->get_param( 'offer' );
  
  if ( ! is_null( $offer ) ) {
    $args['meta_query'] = array(
      array(
        'key'     => 'offer',
        'value'   => $offer ? 1 : 0,
      )
    );
  }

  return $args;
}, 10, 2 );
```

**URL**: http://www.mysite.com/wp-json/wp/v2/posts?offer=1

Thanks

**Comment by st-small** [comment]
@airesvsg Thank you very much! It works and I'm very happy to use it! Also I want to ask you about fetch results, is it possible to get the number of posts from my site using filter? How I can get answer that all posts with this filter received?!

Thanks.

**Comment by airesvsg** [comment]
@st-small  Maybe the filter bellow works.
```PHP
// rest_{post_type}_query
add_filter( 'rest_post_query', function( $args ) {
  $args['posts_per_page'] = -1;
  return $args;
} );
```
Thanks

**Comment by st-small** [comment]
@airesvsg thanks, will use!

**Comment by uzarsalan** [comment]
Sorry, may be i did something wrong, but this not work for me.
I have added custom field named 'email' and trying to filter posts with a query like
http://www.mysite.com/wp-json/wp/v2/posts?email=example@site.com

That's what i write in functions.php file

`add_filter( 'rest_post_query', function( $args, $request ) {
  $email = $request->get_param( 'email' );
  
  if ( ! is_null( $email ) ) {
    $args['meta_query'] = array(
      array(
        'key'     => 'email',
        'value'   => $email,
      )
    );
  }

  return $args;
}, 10, 2 );`

**Comment by airesvsg** [comment]
Hi @uzarsalan,
I tested in latest version of WordPress and it's works.
What's your WordPress version?
Thanks

**Comment by uzarsalan** [comment]
I'm sorry! I'm a stupid. Version is 4.6.1 =)
