### ISSUE TITLE
ACF Option Page not showing in json

### ISSUE THREAD

**Issue by lucavercellio** [airesvsg/acf-to-rest-api#108]
Hi Aires, i'm trying to call http://www.lucavercellio.com/wp-json/acf/v3/options/acf-options-bio but it seems not working. I'm using your 3.0 beta version and ACF Pro Option Page, correctly completed. Am i doing something wrong?
Another issue seems not to show images (from acf field) in json. 
Thanks a lot for help
Luca

**Comment by lucavercellio** [comment]
Yes it is working now! Thanks for the support and for the great plugin

**Comment by lithiumlab** [comment]
How do you handle the case of subpages created like this?

`
if( function_exists('acf_add_options_page') ){
	acf_add_options_page();
	acf_add_options_sub_page('Settings Subpage Test');
}
`

**Comment by wgroenewold** [comment]
Beware that if you want to get the field data in a plugin that you use your set "ID" instead of option. 

So get_field('foo', 'acf-options-bio'); instead of the usual get_field('foo', 'option');

**Comment by Twansparant** [comment]
> How do you handle the case of subpages created like this?
> 
> ```
> if( function_exists('acf_add_options_page') ){
> 	acf_add_options_page();
> 	acf_add_options_sub_page('Settings Subpage Test');
> }
> ```

Did you manage to find a solutions to this?

**Comment by beltranrengifo** [comment]
> How do you handle the case of subpages created like this?
> 
> ```
> if( function_exists('acf_add_options_page') ){
> 	acf_add_options_page();
> 	acf_add_options_sub_page('Settings Subpage Test');
> }
> ```

I wonder the same...

**Comment by willpaige** [comment]
> > How do you handle the case of subpages created like this?
> > ```
> > if( function_exists('acf_add_options_page') ){
> > 	acf_add_options_page();
> > 	acf_add_options_sub_page('Settings Subpage Test');
> > }
> > ```
> 
> I wonder the same...

I'm also wondering how you handle sub option pages

**Comment by cytronn** [comment]
> > > How do you handle the case of subpages created like this?
> > > ```
> > > if( function_exists('acf_add_options_page') ){
> > > 	acf_add_options_page();
> > > 	acf_add_options_sub_page('Settings Subpage Test');
> > > }
> > > ```
> > 
> > 
> > I wonder the same...
> 
> I'm also wondering how you handle sub option pages

Still nothing new about it?

**Comment by lee-cloete** [comment]
Any update on this yet ? 

Or is domain/wp-json/acf/v3/options/options all we have available?
