### ISSUE TITLE
WP-API ACF Rendering Homepage and no JSON

### ISSUE THREAD

**Issue by robynlarsen** [airesvsg/acf-to-rest-api#11]
Is there a specific beta version of WPI API that needs to be used with this plugin? At the moment, the endpoint serves up the homepage instead of the actual JSON data. 

Thoughts? 

`http://dev-twg-express.pantheon.io/wp-json/acf/v2/post/`

**Comment by airesvsg** [comment]
Hi @robynlarsen,
you need the latest version of [WordPress REST API](https://wordpress.org/plugins/rest-api/).

If you desire get the acf fields from your posts. So the endpoint it must be one of:

Only acf fields of post ID 10
`http://dev-twg-express.pantheon.io/wp-json/acf/v2/post/10`

All post with acf fileds appended
`http://dev-twg-express.pantheon.io/wp-json/wp/v2/posts/`

Only post ID 10 with acf fields appended
`http://dev-twg-express.pantheon.io/wp-json/wp/v2/posts/10`

**Comment by robynlarsen** [comment]
Looks like it was a permalink flushing issue... permalinks > save settings works everytime in WP.

**Comment by airesvsg** [comment]
:+1:
