### ISSUE TITLE
Returning "cant_update_item" error when editing Media field

### ISSUE THREAD

**Issue by aaroneight** [airesvsg/acf-to-rest-api#110]
I'm trying to update a media ACF field.  I know that I'm properly authenticated because I'm able to update post fields in my other ajax calls.  For some reason, I cannot get my media field to update.  I continue to get the 500 Internal Server error with a response of `cant_update_item`. 

Here is my call: 

```
var data = {
   "fields": {
        name: value,
      },
};

var url = document.location.origin + '/wp-json/acf/v2/media/' + mediaId + '/' + name;

return $.ajax({
            method: 'PUT',
            data: data,
            dataType: 'json',
            url: url,
            beforeSend: function(xhr) { xhr.setRequestHeader('X-WP-Nonce', WP_API_Settings.nonce);},
});

```

I'm using ACF to REST API version  2.2.1  and ACF PRO version 5.5.9.

Any thoughts?

**Comment by aaroneight** [comment]
I was able to resolve this by adding 

```
add_filter( 'acf/location/rule_match/attachment', function(){
    return true;
} );
```

to my functions.php

**Comment by airesvsg** [comment]
Hello @aaroneight,
Thanks for using my plugin.
I'll test it.
Thanks
