### ISSUE TITLE
endpoints returning 403 when using the V3 beta

### ISSUE THREAD

**Issue by rafegoldberg** [airesvsg/acf-to-rest-api#111]
the `acf/v3` beta looks super exciting/enticing, but it seems to break CORS accessibility. using `acf/v2` I can ping an API endpoint from another subdomain (relative to my WP install) and it all works like a charm! but if I flip over to `v3` and try to ping the same endpoint (from the same subdomain which worked a second ago) it returns a 403 error.

Maybe I'm missing something– some permissions configuration step, or something? Or maybe it's just the nature of using beta software! In any case, thanks for a great plugin; looking forward to stable `v3` release!

**Comment by airesvsg** [comment]
Hello @rafegoldberg,
Thanks for using my plugin.
You set the request API version?
https://github.com/airesvsg/acf-to-rest-api#request-api-version
Thanks
