### ISSUE TITLE
[3.0.0-beta] Options Endpoint Returns Empty ACF Array

### ISSUE THREAD

**Issue by erwstout** [airesvsg/acf-to-rest-api#112]
Hi @airesvsg! Thanks for your work on this plugin, I've been using it for a while now and I am pretty excited about what you have going for version 3. 

I'm trying to access an options page via the Rest API and I keep getting an empty `acf[]` array. 

The URL Structure:
`http://localhost:8888/wp-json/acf/v3/options/49038`

URL From ACF Options Page (for reference):
`http://localhost:8888/wp-admin/post.php?post=49038&action=edit`

JSON Response:

```json
{
"acf": []
}
```

Screenshot of options page:
![screen shot 2017-03-09 at 3 01 51 pm](https://cloud.githubusercontent.com/assets/9441913/23772763/70aa8e44-04d9-11e7-9d09-d1e3fbfdd5a2.png)

Any thoughts? I verified that the plugin is pointing to v3 via the settings page. 

Thanks!

**Comment by erwstout** [comment]
In fact, event the pages endpoint results in an empty array, and then when looking at the standard `wp/v2/pages/{id}` the `acf[]` array is empty there too. I only get values when switching back to V2.

You might already know this though, I'm not sure how far along the beta is. Thanks!

**Comment by airesvsg** [comment]
Hello @erwstout,
Please, read this issue: https://github.com/airesvsg/acf-to-rest-api/issues/108#issuecomment-283401435

The default ID in the ACF for options pages is: **options**

Please access the link below for more details:
https://www.advancedcustomfields.com/resources/acf_add_options_page/ 

```PHP
$args = array(
...
 'post_id' =>  'options',
...
); 
```

Thanks

**Comment by erwstout** [comment]
Ah got it, that makes sense.

What am I doing wrong with the page then?

For instance, `http://techpinions:8888/wp-json/acf/v3/pages/16308` results in an empty array (there are content and fields there). 

`16308` is the page id in WP and I know in PHP you could use `the_field('fieldname', 16308)` returns the field, shouldn't this be true for the Rest endpoint?

**Comment by airesvsg** [comment]
@erwstout  the endpoint is: `http://techpinions:8888/wp-json/acf/v3/options/options`

**Comment by erwstout** [comment]
Right, I get that for the options page, but for instance when trying to get ACF values from page, like in this doc example from your Readme:

`/wp-json/acf/v3/pages/{id}`

^ Hitting that endpoint, when i have acf values only on that page (not options) also returns an empty array.

**Comment by erwstout** [comment]
Screenshots:

![screen shot 2017-03-10 at 11 04 36 am](https://cloud.githubusercontent.com/assets/9441913/23807049/68fd2a0a-0581-11e7-8000-5dea77ccb00b.png)
![screen shot 2017-03-10 at 11 04 12 am](https://cloud.githubusercontent.com/assets/9441913/23807048/68fbbc10-0581-11e7-88b0-76f6d999801a.png)

**Comment by airesvsg** [comment]
@erwstout Can you to export this field group in json format and send to my email ( airesvsg@gmail.com )?
How to export:
![export-fields](https://cloud.githubusercontent.com/assets/396668/23809787/c4d078a6-05ad-11e7-8f91-eaf95b132420.png)
Thanks

**Comment by airesvsg** [comment]
Hi @erwstout,
I tested your exported data and I didn't see any problem.

Please, follow the link with my basic test:
https://youtu.be/ODvzag8VrRU

Thanks
