### ISSUE TITLE
Return posts by title or slug?

### ISSUE THREAD

**Issue by bitsleft** [airesvsg/acf-to-rest-api#113]
http://mydomain.com/?rest_route=/acf/v3/my_custom_post_type/PostID  - This works

(my_custom_post_type is defined in CPT UI Plugin)

But: 

http://mydomain.com/?rest_route=/acf/v3/my_custom_post_type/post-slug

It seems that it would be practical to return a post based on its slug rather than the ID in some cases..  For example, an Angular App that might have hard-coded header / footer links.

**Comment by airesvsg** [comment]
Hi @bitsleft,
The v3 supports this scenario.

The endpoint is:
`http://mydomain.com/wp-json/acf/v3/my_custom_post_type?slug[]=post-slug`

In your case:
`http://mydomain.com/?rest_route=/acf/v3/my_custom_post_type?slug[]=post-slug`

Thanks
