### ISSUE TITLE
Cannot update item via postman or vue

### ISSUE THREAD

**Issue by mariojankovic** [airesvsg/acf-to-rest-api#114]
First of all, I really like the idea and documentation. Looks good.
Too bad it doesn't work for me though - I am able to update the post itself, but no ACF field:
http://i.imgur.com/opMeqK2.png

**Comment by mariojankovic** [comment]
Also, this is my get request:
http://i.imgur.com/ZXVUcqD.png

**Comment by airesvsg** [comment]
Hi @mariojankovic,
Please, read about authentication, follow the link below:
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by mariojankovic** [comment]
Thanks @airesvsg, I figured it out though. For some reason, I had to register my meta field through WP as well. I guess you have to manually set every meta field to show in rest. Example:

```
<?php 
$args = array(
    'sanitize_callback' => 'sanitize_my_meta_key',
    'auth_callback' => 'authorize_my_meta_key',
    'type' => 'string',
    'description' => 'My registered meta key',
    'single' => true,
    'show_in_rest' => true,
);
register_meta( 'post', 'likes', $args );  ?>
```
