### ISSUE TITLE
Settings not appearing

### ISSUE THREAD

**Issue by tjalil** [airesvsg/acf-to-rest-api#116]
Hey, I've added this plugin to my project and I was able to "activate" it but I don't see an option for settings, as shown in your screenshot in the readme. Unable to figure it out, I proceeded to add `define( 'ACF_TO_REST_API_REQUEST_VERSION', 2 );` to wp-config.php but again not getting the desired result. Anytime i navigate to "http://domain/wp-json/acf/v2/books", I'm returned a 404.

Also, added `add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );` to functions.php but I don't see the option to activate "show in REST API" in the custom fields edit form.

**Comment by airesvsg** [comment]
Hi @tjalil,
Settings is only available in V3.

```PHP
define( 'ACF_TO_REST_API_REQUEST_VERSION', 3 );
```

Thanks

**Comment by tjalil** [comment]
![screen shot 2017-03-16 at 10 36 12 am](https://cloud.githubusercontent.com/assets/3508170/24001424/79df2028-0a34-11e7-990e-ab0b8abce5ea.png)

hey @airesvsg I still don't see the "settings" option in the plugin.

**Comment by tjalil** [comment]
Also, am I correct to add `add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );` to functions.php?

**Comment by airesvsg** [comment]
@tjalil Please update your plugin to v3.

1. Download ( https://github.com/airesvsg/acf-to-rest-api/archive/master.zip ) and extract the v3 files;
2. Copy the _acf-to-rest-api-master_ folder into your _wp-content/plugins_ folder;
3. Rename _acf-to-rest-api-master_ to _acf-to-rest-api_;
3. Activate the ACF to REST API plugin via the plugin admin page.

**Comment by Gabb971** [comment]
Hi !
I'm a bit late but I have the same issue and I'd like to know in which file functions.php I am supposed to add the filter ?
