### ISSUE TITLE
Download version at WordPress is V 2.2.1

### ISSUE THREAD

**Issue by krishkusuma** [airesvsg/acf-to-rest-api#118]
I went to https://wordpress.org/plugins/acf-to-rest-api/ but the download version is V 2.2.1.
Is the current version V 3 ?
Could you tell me where I can download the V 3, please ?
Thanks

**Comment by airesvsg** [comment]
Hi @krishkusuma,
Follow the steps below to download the v3.

1. Download ( https://github.com/airesvsg/acf-to-rest-api/archive/master.zip ) and extract the v3 files;
2. Copy the acf-to-rest-api-master folder into your wp-content/plugins folder;
3. Rename acf-to-rest-api-master to acf-to-rest-api;
4. Activate the ACF to REST API plugin via the plugin admin page.

Thanks
