### ISSUE TITLE
good example neede

### ISSUE THREAD

**Issue by uniu** [airesvsg/acf-to-rest-api#119]
Hi Aries,
Could i please to give in documentation simple example how properly **put new post with some ACL** using any rest client.

I already installed all REST and ACF plugins and get still problems.

Thanks in advance
Lukasz

**Comment by airesvsg** [comment]
Hi @uniu,
Please, follow the link with examples:
https://github.com/airesvsg/acf-to-rest-api#examples

Thanks

**Comment by uniu** [comment]
But all example rather updates posts isn't?
ex:  action="http://localhost/wp-json/acf/v3/posts/**1** - means choose post id=1
im right?

**Comment by airesvsg** [comment]
Did you check the "to do list"?
Please, see this [line](https://github.com/airesvsg/to-do-list-acf-to-rest-api/blob/master/script.js#L37) I create a new post here.
Thanks

**Comment by uniu** [comment]
Your todo list is a little complicated. I did it combines 2 api calls like below. 
Thanks for your attention Aries.

$data = [
            'title' => "test post title",
            'category' => "1",
            'status' => 'publish',
            'content' => 'test content',
        ];

        // create post and get id
        $response = CallAPI("POST", "http://wp.local/wp-json/wp/v2/posts", $data);
        $postId = $response['id'];

        $acf = [
            'fields' => [
                'myacffield' => 'test2',
                'myacfdict' => 'position3',
            ]
        ];

        // update ACF fileds
        $response = CallAPI("POST", "http://wp.local/wp-json/acf/v3/posts/".$postId , $acf);
        var_dump($response);

    function CallAPI($method, $url, $data = false) // standard google 
    {
        $data = json_encode($data);
        $curl = curl_init();

        switch ($method)
        {
            case "POST":
                curl_setopt($curl, CURLOPT_POST, 1);

                if ($data)
                    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
                break;
            case "PUT":
                curl_setopt($curl, CURLOPT_PUT, 1);
                break;
            default:
                if ($data)
                    $url = sprintf("%s?%s", $url, http_build_query($data));
        }
        $authorization = "Bearer <insert your token from jwt-auth>";
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json' , 'Authorization:'.$authorization ));

    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

    $result = curl_exec($curl);

    curl_close($curl);
    return json_decode($result,true);
    }

**Comment by airesvsg** [comment]
@uniu You can create it that way too
```PHP
$data = [
  'title'    => "test post title",
  'category' => "1",
  'status'   => 'publish',
  'content'  => 'test content',
  'fields'   => [
    'myacffield' => 'test2',
    'myacfdict'  => 'position3',
  ]
];

$response = CallAPI( "POST", "http://wp.local/wp-json/wp/v2/posts", $data );
```

Thanks
