### ISSUE TITLE
Cannot post changes to WP Rest API

### ISSUE THREAD

**Issue by m1rc0** [airesvsg/acf-to-rest-api#12]
Hi,
I've a question regarding updating ACF fields via POST request from third party clients. 

If I curl 
    curl http://mydomain.com/wp-json/acf/v2/pages/32
I get everything as expected, but if I do a post like:
    curl -X POST -H "Content-Type: application/json" -d '{acf:{"field":"2"}}' -u user:pw http://mydomain.com/wp-json/acf/v2/page/32 -v

I get error 500. 

Any ideas what I'm doing wrong?

Kind regards

**Comment by airesvsg** [comment]
Hi @m1rc0,

Your data estruture isn't right, try it:
```json
{
	"fields":{
		"my_field": "My value",
		"my_other_field": "My other value"
	}
}
```
Cheers

**Comment by m1rc0** [comment]
Oh stupid me.

Thank you very much.
