### ISSUE TITLE
get posts by category or custom field name?

### ISSUE THREAD

**Issue by vanessarusu** [airesvsg/acf-to-rest-api#122]
Hi There,

Just wondering if there is a way to get posts by their custom field name or wordpress category id? I am trying to select all posts that have a specific custom field. Any help on how to achieve this would be very appreciated!

**Comment by airesvsg** [comment]
Hi @vanessarusu,
what's version ( v2 or v3 ) are you using?
Thanks

**Comment by airesvsg** [comment]
Hi @vanessarusu,
Please, copy and paste the code bellow in your **functions.php**
```PHP
add_filter( 'rest_{type}_query', function( $args ) {
	$args['meta_query'] = array(
		array(
			'key'   => 'my_field',
			'value' => esc_sql( $_GET['field'] ),
		)
	);

	return $args;
} );
```

Url:
```
http://site.com/wp-json/wp/v2/posts?field=test
```

The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy
Thanks

**Comment by vanessarusu** [comment]
@airesvsg fantastic! Thank you so much!

**Comment by Igcorreia** [comment]
@airesvsg this is not perfect. :) Once this is added the filter works but if you go to /v2/posts <------ which usualy lists all, this stops working :/

**Comment by hitconsulting** [comment]
> @airesvsg this is not perfect. :) Once this is added the filter works but if you go to /v2/posts <------ which usualy lists all, this stops working :/

Have the same problem.. Any solution for that? :)

**Comment by aaidenduaban** [comment]
having same problem bumping this one up
