### ISSUE TITLE
Can't Update some fields

### ISSUE THREAD

**Issue by anbanm** [airesvsg/acf-to-rest-api#124]
Hi there,

I am trying to create a custom post (type:gallery) - the rest API returns the following:

GET: http://mysite/wp-json/acf/v2/gallery/1889
```JSON
{
   "acf":{
      "custom_gallery_images":"",
      "gallery_post_sidebar":"gallery_post_sidebar_off"
   }
}
```

I am not able to  update "custom_gallery_images" 

Here is a sample of my post:
POST: http://mysite/wp-json/acf/v2/gallery/1889

```JSON
{
   "acf_fields":{
      "custom_gallery_images":[
         {
            "id":1835,
            "alt":"",
            "title":"ayanda-1-9",
            "caption":"",
            "description":"",
            "mime_type":"image/jpeg",
            "url":"xyz",
            "width":667,
            "height":1000
         }
      ],
      "gallery_post_sidebar":"gallery_post_sidebar_off"
   }
}
```
RESPONSE:

```JSON
{
  "acf": {
    "custom_gallery_images": [],
    "gallery_post_sidebar": "gallery_post_sidebar_on"
  }
}
```

``

**Comment by airesvsg** [comment]
Hi @anbanm,
Thanks for using my plugin.
Please send me the below info:

**Version ACF**: 
**Type of field _custom_gallery_images_**:

Thanks
