### ISSUE TITLE
ACF post object relationship

### ISSUE THREAD

**Issue by MikeMilian** [airesvsg/acf-to-rest-api#126]
I am trying to get the ACF field of the post object. I have 2 the same functions. And the settings for the ACF for both posttypes are the same. But only the first one works.

This one works
http://keiweek.appademic.nl/wp-json/wp/v2/event

```
add_filter('acf/rest_api/event/get_fields', function( $data, $request, $response ) {
    if ( $response instanceof WP_REST_Response ) {
        $data = $response->get_data();
    }
    if( isset( $data['acf'] ) ) {
        $data['acf']['locatie']->acf = get_fields( $data['acf']['locatie']->ID );
    }   
    return $data;
}, 10, 3 );
```

And this one doesn't work
http://keiweek.appademic.nl/wp-json/wp/v2/locatie

```
add_filter('acf/rest_api/locatie/get_fields', function( $data, $request, $response ) {
    if ( $response instanceof WP_REST_Response ) {
        $data = $response->get_data();
    }
    if( isset( $data['acf'] ) ) {
        $data['acf']['events']->acf = get_fields( $data['acf']['events']->ID );
    }   
    return $data;
}, 10, 3 );
```

**Comment by airesvsg** [comment]
Hi @MikeMilian,
Please read it: https://github.com/airesvsg/acf-to-rest-api/issues/109
Thanks

**Comment by MikeMilian** [comment]
Thx, but that function still not working for me. The strange thing is that de event (post type) filter works. But with the locatie (post type) not working.

Do you know something else I can try? Thanks a lot!

**Comment by kgrosvenor** [comment]
Does this work now
