### ISSUE TITLE
Cannot update custom field in comments

### ISSUE THREAD

**Issue by CodeRodeo** [airesvsg/acf-to-rest-api#128]
First of all, many many thanks for creating this plugin. Without it I have no idea how my project would even be possible! 

But...I am unable to update a custom field for comments. 

(I am using v2. Can't seem to get v3 beta working)

I am pre-uploading the image via another ajax call and setting the ID of the newly-created media post in the ACF `fields[comment_image]` . This method is working fine for posts but not for comments.

Here is the JQuery AJAX call I am using:
```
		$("#comment-form").on('submit', function(e){
			e.preventDefault();
		        var formData = self.find('input, textarea, select').filter('.included').serialize();
			formData += '&author=' + user.id;
			formData += '&author_name=' + user.name;
			$.ajax( {
				url: '/wp-json/wp/v2/comments/',
				method: 'POST',   
				beforeSend: function ( xhr ) {
					xhr.setRequestHeader( 'X-WP-Nonce', wpApiSettings.nonce );
				},
				data: formData, 
				dataType: 'json'
			} )
			.success( function ( response ) {
				console.log( response );			
			} )	
		});

```
The serialized string is: 
`post=5401&content=testing&fields%5Bcomment_image%5D=12808&author=1&author_name=CodeRodeo`

In the response, it returns `acf : false` 
I see that all the other fields have saved correctly but nothing is added to the DB in the commentmeta table.

If I use the standard, dynamically generated wordpress comment form it also works fine, but I need to have this work for a mobile app.

Please let me know if I am missing a step, or if you need more information.

Thanks much!!
Zelda

**Comment by airesvsg** [comment]
Hi @CodeRodeo,
Thanks for using my plugins.
I need more information about WP and ACF version.
Thanks
