### ISSUE TITLE
Filter by ACF Field Value

### ISSUE THREAD

**Issue by pakoArtal** [airesvsg/acf-to-rest-api#13]
Hi Aires,

I'm trying to filter by ACF Field Value,  just the same question asked for the previous version at https://github.com/airesvsg/acf-to-wp-rest-api/issues/6.

Will your answer still work for this version? I tried your code but I'm not able to filter, getting all the results

I'm using:

- WordPress 4.4.2

- WP REST API Versión 2.0-beta12
- Custom Post Type UI Versión 1.2.3  (Admin panel for creating custom post types and custom taxonomies in WordPress)
- Advanced Custom Fields Versión 4.4.5 
- ACF to REST API Versión 2.0.6

**Comment by airesvsg** [comment]
Hi @pakoArtal,
If your Custom Post is "books", so your filter will be: **rest_books_query** = rest_{post_type}_query

```PHP
add_filter( 'rest_query_vars', function ( $valid_vars ) {
    return array_merge( $valid_vars, array( 'land', 'meta_query' ) );
} );
```

```PHP
add_filter( 'rest_books_query', function( $args, $request ) {
    $land   = $request->get_param( 'land' );

    if ( ! empty( $land ) ) {
        $args['meta_query'] = array(
            array(
                'key'     => 'land',
                'value'   => $land,
                'compare' => '=',
            )
        );      
    }

    return $args;
}, 10, 2 );
```

Cheers

**Comment by pakoArtal** [comment]
Hi @airesvsg ,

You were right. I forgot to change my filter to  rest_**books**_query

Thank you for your help and for your plugin!

**Comment by Idealien** [comment]
In that case, what would the end point be?
/wp-json/acf/v2/books?land=example ??

In my setup /wp-json/acf/v2/books/1234 brings back a singular result (ok) but cannot yet retrieve a filtered set of custom post types (or even complete set of custom post types from /wp-json/acf/v2/books/)

**Comment by airesvsg** [comment]
Hi @Idealien,
the endpoint `/wp-json/acf/v2/books` it is not supported in current version.
Please, see this issue: https://github.com/airesvsg/acf-to-rest-api/issues/51
Thanks

**Comment by Idealien** [comment]
Yeah; I edited trying to articulate that the /wp-json/wp/v2/books?land=america endpoint serves identical functionality for now. Either way, plugin is amazing and opening up so many front-end doors for development as ACF does to the admin side of WP.

Thanks!

**Comment by honeyamin** [comment]
what about using compare = IN
and also how can we use in loop?
`    if ( ! empty( $land ) ) {
        $args['meta_query'] = array(
            array(
                'key'     => 'land',
                'value'   => $land,
                'compare' => '=',
            )
        );      
    }`
