### ISSUE TITLE
Installing acf-to-rest-api breaks REST API 

### ISSUE THREAD

**Issue by ChrisTarasovs** [airesvsg/acf-to-rest-api#130]
Now that i got setup acf-to-rest-api  and if I target URL I get data:
http://ecommerce-ux.london/wp-json/acf/v3/posts/1

but now that this is enabled  my REST api is broken
http://ecommerce-ux.london/wp-json/wp/v2/posts/1

If I disable acf-to-rest-api than WP REST API works. 

I am using  WordPress as  back end and Angular 2 as front end.

**Comment by airesvsg** [comment]
Hi @ChrisTarasovs,
Please, tell me more about your environment like WP version, plugins and others.
Thanks

**Comment by ChrisTarasovs** [comment]
Hi Airesvsg, apologies couldn't get around faster. I was using latest WP and no plugins except what is listed above.
