### ISSUE TITLE
Repeater object with relationship field

### ISSUE THREAD

**Issue by gabrielstuff** [airesvsg/acf-to-rest-api#131]
Hi !

You configure a group field with a repeater. This repeater allows to select a relationship object (a custom post type). The custom post type got also a group field ith many ACF field.

In the following configuration it is not possible to retrieve the group field related to the post object inside the repeater through the API.

The ACF plugin does return an array of post object with all the details except the ACF group field associated with the post object.

You can also verify this with a simple field and a relationship object.

Thanks,

G

**Comment by airesvsg** [comment]
Hi @gabrielstuff,
Please read it: https://github.com/airesvsg/acf-to-rest-api/issues/109
Thanks
