### ISSUE TITLE
"acf" empty in JSON response

### ISSUE THREAD

**Issue by danielkoch** [airesvsg/acf-to-rest-api#133]
I'm using WordPress 4.7.4 with "ACF to REST API" 3.0.1-beta. I successfully created a custom post and added custom fields with "Advanced Custom Fields". The "Rest option" (https://github.com/airesvsg/acf-to-rest-api#field-settings) is active in every custom field. But in every REST call the `acf` node is empty:
http://<host>/wp-json/acf/v3/<custom-post-name>

Sample response:
`[{"id":422,"acf":[]},{"id":420,"acf":[]},{"id":419,"acf":[]}]`

**Comment by danielkoch** [comment]
Fixed this issue. Caused by corrupted post state.

**Comment by josephdburdick** [comment]
@danielkoch can you explain what you mean by currupted post state and how you resolved it?

**Comment by danielkoch** [comment]
I reinstalled the plugin and again saved the posts with the ACF fields.

**Comment by josephdburdick** [comment]
@danielkoch have you found/heard of any way to automate the saving of the posts with ACF fields? I've tried WP-CLI to no avail. I have 700+ entries I need to do this for so I'm just looking for an alternative.

**Comment by danielkoch** [comment]
No. Sorry.

**Comment by kjtaylor13** [comment]
Hi, I've this same issue, did anyone find a way to save multiple posts so the ACF data is updated?

Thanks
