### ISSUE TITLE
ACF Photo Gallery Field missing in JSON response

### ISSUE THREAD

**Issue by SebMeunierUX** [airesvsg/acf-to-rest-api#134]
Hi,

I'm trying to use Wordpress as a CMS using both plugins ACF Version 4.4.11  + ACF Photo Gallery Field Version 1.6.1 (link: https://wordpress.org/plugins/navz-photo-gallery/). I'm using your plugin to retrieve all the ACF information into a JSON feed, but I'm missing the gallery fields.

Bug ? Missing feature ? What would you propose to handle this scenario? 

Thanks

**Comment by airesvsg** [comment]
Hi @SebMeunierUX,
Please read it: https://wordpress.org/support/topic/acf-photo-gallery-field-api-support/#post-8954224
Thanks

**Comment by SebMeunierUX** [comment]
Oops, missed that thread. Thanks

**Comment by steffanhalv** [comment]
Doesn't look like much happened there, cant you just add support for it in your plugin?

Please :-) @airesvsg 

I also added an issue for the other plugin ..

https://github.com/navneil-naicker/acf-photo-gallery-field/issues/3

**Comment by navneil-naicker** [comment]
At the time of this comment ACF Photo Gallery v1.6.3 is still under development. You can download the beta version of the source code from [here](https://github.com/navneil-naicker/acf-photo-gallery-field).

Replace the current version of the code on your WordPress website plugin folder name '_navz-photo-gallery_' with the beta version. ACF Photo Gallery v1.6.3 has support for [ACF to REST API](https://wordpress.org/plugins/acf-to-rest-api/).

**Usage 1**
`http://www.example.com/wp-json/acf/v3/pages/<POST_ID>/<Field_Name>?type=photo_gallery`

**Example**
`http://www.example.com/wp-json/acf/v3/pages/2/vacation_photos?type=photo_gallery`

**Usage 2**
`http://www.example.com/wp-json/acf/v3/pages/<POST_ID>/<Field_Name>?type=photo_gallery&order=ASC&orderby=post__in`

**Example**
`http://www.example.com/wp-json/acf/v3/pages/2/vacation_photos?type=photo_gallery&order=ASC&orderby=post__in`
