### ISSUE TITLE
Get all data by filtering "type" of post object via ACF

### ISSUE THREAD

**Issue by jeroenb2511** [airesvsg/acf-to-rest-api#135]
Hi @airesvsg,

I tried a lot of stuff to solve the following problem tonight. 

Case:
```JSON
[{"id":30,"date":"2017-05-04T16:54:46","date_gmt":"2017-05-04T14:54:46","guid":{"rendered":"http:\/\/development.local\/?post_type=matches&#038;p=30"},"modified":"2017-05-04T21:10:58","modified_gmt":"2017-05-04T19:10:58","slug":"30","status":"publish","type":"matches","link":"http:\/\/development.local\/matches\/30\/","title":{"rendered":""},"content":{"rendered":"","protected":false},"template":"","acf":{"date":"20170502","time":"19:00","home":{"ID":9,"post_author":"1","post_date":"2017-05-04 15:43:02","post_date_gmt":"2017-05-04 13:43:02","post_content":"","post_title":"PSV","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"psv","to_ping":"","pinged":"","post_modified":"2017-05-04 15:43:02","post_modified_gmt":"2017-05-04 13:43:02","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=club&#038;p=9","menu_order":0,"post_type":"club","post_mime_type":"","comment_count":"0","filter":"raw"},"away":{"ID":7,"post_author":"1","post_date":"2017-05-04 15:40:18","post_date_gmt":"2017-05-04 13:40:18","post_content":"","post_title":"Ajax","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"ajax","to_ping":"","pinged":"","post_modified":"2017-05-04 15:40:18","post_modified_gmt":"2017-05-04 13:40:18","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=club&#038;p=7","menu_order":0,"post_type":"club","post_mime_type":"","comment_count":"0","filter":"raw"},"score":"","type":{"ID":18,"post_author":"1","post_date":"2017-05-04 16:10:39","post_date_gmt":"2017-05-04 14:10:39","post_content":"","post_title":"KNVB-beker","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"knvb-beker","to_ping":"","pinged":"","post_modified":"2017-05-04 16:10:39","post_modified_gmt":"2017-05-04 14:10:39","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=types&#038;p=18","menu_order":0,"post_type":"types","post_mime_type":"","comment_count":"0","filter":"raw"},"season":{"ID":13,"post_author":"1","post_date":"2017-05-04 15:46:34","post_date_gmt":"2017-05-04 13:46:34","post_content":"","post_title":"2016\/2017","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"20162017","to_ping":"","pinged":"","post_modified":"2017-05-04 15:46:34","post_modified_gmt":"2017-05-04 13:46:34","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=seasons&#038;p=13","menu_order":0,"post_type":"seasons","post_mime_type":"","comment_count":"0","filter":"raw"}},"_links":{"self":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/matches\/30"}],"collection":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/matches"}],"about":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/types\/matches"}],"wp:attachment":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/media?parent=30"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},{"id":28,"date":"2017-05-04T16:27:17","date_gmt":"2017-05-04T14:27:17","guid":{"rendered":"http:\/\/development.local\/?post_type=matches&#038;p=28"},"modified":"2017-05-04T21:10:02","modified_gmt":"2017-05-04T19:10:02","slug":"28","status":"publish","type":"matches","link":"http:\/\/development.local\/matches\/28\/","title":{"rendered":""},"content":{"rendered":"","protected":false},"template":"","acf":{"date":"20170504","time":"18:00","home":{"ID":7,"post_author":"1","post_date":"2017-05-04 15:40:18","post_date_gmt":"2017-05-04 13:40:18","post_content":"","post_title":"Ajax","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"ajax","to_ping":"","pinged":"","post_modified":"2017-05-04 15:40:18","post_modified_gmt":"2017-05-04 13:40:18","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=club&#038;p=7","menu_order":0,"post_type":"club","post_mime_type":"","comment_count":"0","filter":"raw"},"away":{"ID":9,"post_author":"1","post_date":"2017-05-04 15:43:02","post_date_gmt":"2017-05-04 13:43:02","post_content":"","post_title":"PSV","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"psv","to_ping":"","pinged":"","post_modified":"2017-05-04 15:43:02","post_modified_gmt":"2017-05-04 13:43:02","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=club&#038;p=9","menu_order":0,"post_type":"club","post_mime_type":"","comment_count":"0","filter":"raw"},"score":"2-0","type":{"ID":17,"post_author":"1","post_date":"2017-05-04 15:55:37","post_date_gmt":"2017-05-04 13:55:37","post_content":"","post_title":"Eredivisie","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"eredivisie","to_ping":"","pinged":"","post_modified":"2017-05-04 15:55:37","post_modified_gmt":"2017-05-04 13:55:37","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=types&#038;p=17","menu_order":0,"post_type":"types","post_mime_type":"","comment_count":"0","filter":"raw"},"season":{"ID":13,"post_author":"1","post_date":"2017-05-04 15:46:34","post_date_gmt":"2017-05-04 13:46:34","post_content":"","post_title":"2016\/2017","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"20162017","to_ping":"","pinged":"","post_modified":"2017-05-04 15:46:34","post_modified_gmt":"2017-05-04 13:46:34","post_content_filtered":"","post_parent":0,"guid":"http:\/\/development.local\/?post_type=seasons&#038;p=13","menu_order":0,"post_type":"seasons","post_mime_type":"","comment_count":"0","filter":"raw"}},"_links":{"self":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/matches\/28"}],"collection":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/matches"}],"about":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/types\/matches"}],"wp:attachment":[{"href":"http:\/\/development.local\/wp-json\/wp\/v2\/media?parent=28"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}]
```

I created different post types (clubs, matches, type and season). I selected a type in the postitem of match, which I output them as post object (see above). I am trying to filter them via the API, but it doesn't work. I tried to call them as "wp-json/wp/v2/matches?type=eredivisie", because I want filter on "eredivisie".

Do you have any idea?

**Comment by danielkoch** [comment]
Fixed this issue. It was caused by a corrupted post state.

**Comment by jeroenb2511** [comment]
Must I change some code or was it a bug?

2017-05-07 7:33 GMT+02:00 Daniel Koch <notifications@github.com>:

**Comment by danielkoch** [comment]
I reinstalled the plugin and again saved the posts with the ACF fields.

**Comment by jeroenb2511** [comment]
I changed the following things:

*ACF group for matches*

*[image: Inline afbeelding 1]*

*[image: Inline afbeelding 2]*

*Changed two matches*

*[image: Inline afbeelding 3]*

*Visible in overview*

*[image: Inline afbeelding 4]*

*Removed plugin*

*[image: Inline afbeelding 5]*

*[image: Inline afbeelding 6]*

*Install plugin again*

*[image: Inline afbeelding 7]*

*[image: Inline afbeelding 8]*

*Re-saved posts of matches*

*[image: Inline afbeelding 9]*

*[image: Inline afbeelding 10]*

*[image: Inline afbeelding 11]*

*Get the API by URL and parameter:*

*[image: Inline afbeelding 12]*

*The return of the JSON give me two records in stead of one record (both
will be return):*
[
  {
    "id": 30,
    "date": "2017-05-04T16:54:46",
    "date_gmt": "2017-05-04T14:54:46",
    "guid": {
      "rendered": "http://ajaxforever.local/?post_type=matches&#038;p=30"
    },
    "modified": "2017-05-08T08:42:04",
    "modified_gmt": "2017-05-08T06:42:04",
    "slug": "30",
    "status": "publish",
    "type": "matches",
    "link": "http://ajaxforever.local/matches/30/",
    "title": {
      "rendered": ""
    },
    "content": {
      "rendered": "",
      "protected": false
    },
    "template": "",
    "acf": {
      "date": "20170502",
      "time": "19:00",
      "home": {
        "ID": 9,
        "post_author": "1",
        "post_date": "2017-05-04 15:43:02",
        "post_date_gmt": "2017-05-04 13:43:02",
        "post_content": "",
        "post_title": "PSV",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "psv",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:43:02",
        "post_modified_gmt": "2017-05-04 13:43:02",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=club&#038;p=9",
        "menu_order": 0,
        "post_type": "club",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "away": {
        "ID": 7,
        "post_author": "1",
        "post_date": "2017-05-04 15:40:18",
        "post_date_gmt": "2017-05-04 13:40:18",
        "post_content": "",
        "post_title": "Ajax",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "ajax",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:40:18",
        "post_modified_gmt": "2017-05-04 13:40:18",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=club&#038;p=7",
        "menu_order": 0,
        "post_type": "club",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "score": "",
      "": false,
      "season": {
        "ID": 13,
        "post_author": "1",
        "post_date": "2017-05-04 15:46:34",
        "post_date_gmt": "2017-05-04 13:46:34",
        "post_content": "",
        "post_title": "2016/2017",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "20162017",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:46:34",
        "post_modified_gmt": "2017-05-04 13:46:34",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=seasons&#038;p=13",
        "menu_order": 0,
        "post_type": "seasons",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "types": {
        "ID": 18,
        "post_author": "1",
        "post_date": "2017-05-04 16:10:39",
        "post_date_gmt": "2017-05-04 14:10:39",
        "post_content": "",
        "post_title": "KNVB-beker",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "knvb-beker",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 16:10:39",
        "post_modified_gmt": "2017-05-04 14:10:39",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=types&#038;p=18",
        "menu_order": 0,
        "post_type": "types",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      }
    },
    "_links": {
      "self": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/matches/30"
        }
      ],
      "collection": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/matches"
        }
      ],
      "about": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/types/matches"
        }
      ],
      "wp:attachment": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/media?parent=30"
        }
      ],
      "curies": [
        {
          "name": "wp",
          "href": "https://api.w.org/{rel}",
          "templated": true
        }
      ]
    }
  },
  {
    "id": 28,
    "date": "2017-05-04T16:27:17",
    "date_gmt": "2017-05-04T14:27:17",
    "guid": {
      "rendered": "http://ajaxforever.local/?post_type=matches&#038;p=28"
    },
    "modified": "2017-05-08T08:44:28",
    "modified_gmt": "2017-05-08T06:44:28",
    "slug": "28",
    "status": "publish",
    "type": "matches",
    "link": "http://ajaxforever.local/matches/28/",
    "title": {
      "rendered": ""
    },
    "content": {
      "rendered": "",
      "protected": false
    },
    "template": "",
    "acf": {
      "date": "20170504",
      "time": "18:00",
      "home": {
        "ID": 7,
        "post_author": "1",
        "post_date": "2017-05-04 15:40:18",
        "post_date_gmt": "2017-05-04 13:40:18",
        "post_content": "",
        "post_title": "Ajax",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "ajax",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:40:18",
        "post_modified_gmt": "2017-05-04 13:40:18",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=club&#038;p=7",
        "menu_order": 0,
        "post_type": "club",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "away": {
        "ID": 9,
        "post_author": "1",
        "post_date": "2017-05-04 15:43:02",
        "post_date_gmt": "2017-05-04 13:43:02",
        "post_content": "",
        "post_title": "PSV",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "psv",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:43:02",
        "post_modified_gmt": "2017-05-04 13:43:02",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=club&#038;p=9",
        "menu_order": 0,
        "post_type": "club",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "score": "2-0",
      "": false,
      "season": {
        "ID": 13,
        "post_author": "1",
        "post_date": "2017-05-04 15:46:34",
        "post_date_gmt": "2017-05-04 13:46:34",
        "post_content": "",
        "post_title": "2016/2017",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "20162017",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-04 15:46:34",
        "post_modified_gmt": "2017-05-04 13:46:34",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=seasons&#038;p=13",
        "menu_order": 0,
        "post_type": "seasons",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      },
      "types": {
        "ID": 17,
        "post_author": "1",
        "post_date": "2017-05-04 15:55:37",
        "post_date_gmt": "2017-05-04 13:55:37",
        "post_content": "",
        "post_title": "Eredivisie",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "eredivisie",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2017-05-05 15:26:42",
        "post_modified_gmt": "2017-05-05 13:26:42",
        "post_content_filtered": "",
        "post_parent": 0,
        "guid": "http://ajaxforever.local/?post_type=types&#038;p=17",
        "menu_order": 0,
        "post_type": "types",
        "post_mime_type": "",
        "comment_count": "0",
        "filter": "raw"
      }
    },
    "_links": {
      "self": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/matches/28"
        }
      ],
      "collection": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/matches"
        }
      ],
      "about": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/types/matches"
        }
      ],
      "wp:attachment": [
        {
          "href": "http://ajaxforever.local/wp-json/wp/v2/media?parent=28"
        }
      ],
      "curies": [
        {
          "name": "wp",
          "href": "https://api.w.org/{rel}",
          "templated": true
        }
      ]
    }
  }
]

Do I save something wrong in "matches" or "types"?

2017-05-08 8:31 GMT+02:00 Daniel Koch <notifications@github.com>:

**Comment by airesvsg** [comment]
Hi @jeroenb2511,
please open a new ticket [here](https://make.wordpress.org/core/reports/).

Thanks
