### ISSUE TITLE
Removing sizes array from Relationship Objects to make specific routers lighter

### ISSUE THREAD

**Issue by lithiumlab** [airesvsg/acf-to-rest-api#136]
Is it possible to remove the "sizes" array from routes when using the Image Field?
Sometimes in particular cases we don't need this in the app side of things. It is actually adding a lot of bloat to routes. ACF includes this for convenience but i'm not sure about a filter to remove this from routes at least for the case of an specific custom post type. Any suggestions?

**Comment by airesvsg** [comment]
Hi @lithiumlab,
Use the filter: `acf/rest_api/{type}/get_fields`
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy
Thanks

**Comment by lithiumlab** [comment]
Thanks a lot for the hint.
Excellent. I was able to do it in the following way:
```
add_filter( 'acf/rest_api/exercise/get_fields', function( $data ) {
	$data['acf']['video_animated_thumbnail']['sizes'] = '';
	$data['acf']['video_featured']['sizes'] = '';
	return $data;
} );
```
