### ISSUE TITLE
acf node value is an empty array instead of empty JSON node

### ISSUE THREAD

**Issue by papsl** [airesvsg/acf-to-rest-api#137]
I have a problem with deserializing WordPress post JSON response when acf-to-rest-api ( 3.0.1-beta) was enabled and the post was created without any advanced custom field. In this example JSON response would be:
```
...
acf":[],
...
```
This brings a problem when implementing a generic deserialization, we need to check if the value is empty array or object. I think this is the same problem as described in issue https://github.com/airesvsg/acf-to-rest-api/issues/133.
From a compatibility point of view probably empty JSON object would be best in this case:

```
...
acf: {},
...
```

**Comment by airesvsg** [comment]
Hello @papsl,

please use the snippet below to transform the answer.

```PHP
add_filter( 'rest_post_dispatch', function( $result ) {
	$data = $result->get_data();

	if ( isset( $data['acf'] ) && empty( $data['acf'] ) ) {
		$data['acf'] = new stdClass;
		$result->set_data( $data );
	}
	
	return $result;
} );
```

Thanks
