### ISSUE TITLE
Add endpoints to the taxonomies

### ISSUE THREAD

**Issue by tukera** [airesvsg/acf-to-rest-api#138]
HI, I was working with this plugins and I have one problem when I want to request custom fiels from the taxonomies.

At the moment if I request `http://localhost/wp-json/wp/v2/brand/36` I get all the data from the category but without the custom fields.

I can get this data when I use `http://localhost/wp-json/acf/v2/term/brand/36`

But in this case, I need to use two requests.

I would like to know if there is a way to get all just using the first request like when I use it with post.

The version I use is 2.2.1

**Comment by airesvsg** [comment]
Hi @tukera,
Please update to new version.
Thanks

**Comment by tukera** [comment]
HI @airesvsg I get the solution using this code in the function

```
function rest_prepare_brand( $response, $object ) {
    if ( $object instanceof WP_Term ) {
        $response->data['acf'] = get_fields( $object->taxonomy . '_' . $object->term_id );
    }

    return $response;
}

add_filter( 'rest_prepare_brand', 'rest_prepare_brand', 10, 2 );
```

**Comment by airesvsg** [comment]
yes, in the last version this issue was fixed.
Thanks.
