### ISSUE TITLE
Response Empty after Import

### ISSUE THREAD

**Issue by jakeols** [airesvsg/acf-to-rest-api#139]
Hi Guys,

This might be an issue with how I'm importing custom posts (using Ultimate CSV Importer- I have a CSV file with ~500 entries), but if anyone has any insight on why this is happening it would be much appreciated. 

I have a custom post type named locations, with ACF fields (lat/lng, etc.) After the import everything seems to look fine, but the acf response from `/acf/v3/locations` is empty.  (see below).

![screen shot 2017-05-24 at 2 49 03 pm](https://cloud.githubusercontent.com/assets/3232346/26420299/2b57ace4-4090-11e7-8ee4-dccab7e29d82.png)

It appears after re-saving the imported data (each custom post individually) the response is correct (though I can't go through ~500 entries and re-save each one). Anyone know why this would be happeing with the ACF data, but not the normal wp fields?

**Comment by josephdburdick** [comment]
I've encountered the same exact issue and the only solution I've found so far is manually saving. Not great.

**Comment by jakeols** [comment]
@josephdburdick Ugh, hoping that there's another way. Have you found that if you save data via the rest api, it's available without having to resave?

**Comment by josephdburdick** [comment]
@jakeols No I haven't tried that.

**Comment by josephdburdick** [comment]
@jakeols yo, I got some good news and bad news.

The good news is: I have been able to import my data and I have not needed to manually update every single field.

The bad news is: it wasn't cheap. I used the "elite", $200 version of [WP All Import](http://www.wpallimport.com/) and it worked.

**Comment by jakeols** [comment]
@josephdburdick Oh awesome, at least we know there's something out there that works.

I wrote a little node script to go through and insert the fields using babyparse / readfilesync but it'll be a huge pain to have to modify and test that every time I have to import fields.

**Comment by josephdburdick** [comment]
I was thinking about doing that but each row in my 600 item spreadsheet had 24 columns and I just didn't have the time to make an attempt

**Comment by josephdburdick** [comment]
But good to know it's possible, you should open source your process in a gist and link it back here for future folk

**Comment by kjtaylor13** [comment]
Hi, 

I'm having the exact same issue, don't want to purchase the $200 addon for my small hobby site, has anyone found a way to update the fields after an import that displays the data in the JSON. all I get at the moment is acf: [] for each one.

Thanks

Kevin

**Comment by jakeols** [comment]
@kjtaylor13 Hey, one option that I've found is to just write the rest interface directly, verses using this plugin (especially when you're really just using simple GET requests). Here's an example below 

```
// register the route
add_action( 'rest_api_init', function () {
	register_rest_route( '/locations/v1', '/all/', array(
		'methods' => 'GET',
		'callback' => 'locations_rest_functionality',
	) );
} );

// get custom fields/ etc. 
function locations_rest_functionality( $data ) {
	$locations = new WP_Query([
	    'post_status' => 'publish',
	    'post_type' => 'locations',
	    'posts_per_page' => -1
		]);
// here is where you can loop through each post and add any of the custom fields. ie. below, 'location type' is one of my ACF fields
	foreach ($locations->posts as $key => $post) {
			$locations->posts[ $key ]->location_type = get_post_meta( $post->ID, 'location_type', true );
		}
	return $locations->posts;
}
```

If for some reason this still isn't grabbing your post data, I can see if I can find the script that's mentioned above (it was for work though and may be gone / un-sharable).

**Comment by kjtaylor13** [comment]
Hi Jaekols, 

That's what I ended up doing. And it give's me more tailored results to what I need. So will be doing that in the future. 

I didn't realise how simple it was to add endpoints in WP.

Thanks

Kevin

**Comment by jakeols** [comment]
@kjtaylor13 No problem- it's been a life saver for me. That and finding out there's built in underscore templates in WP Core lol. I'll close this issue now as well.
