### ISSUE TITLE
ACF fields on POST user

### ISSUE THREAD

**Issue by DennisHalmstad** [airesvsg/acf-to-rest-api#14]
Hello.

When trying to create a user and appending ACF fields i cant get it to work.
looking at ur example 
`<form action="http://localhost/wp-json/wp/v2/posts/1" method="POST">
    <?php 
        // http://v2.wp-api.org/guide/authentication
        wp_nonce_field( 'wp_rest' ); 
    ?>
    <label>Title: <input type="text" name="title"></label>
    <h3>ACF</h3>
    <label>Site: <input type="text" name="fields[site]"></label>
    <button type="submit">Save</button>
</form>`

i tried the same but with users instead
`<form action="http://localhost/v3/wp-json/wp/v2/users" method="POST">
    <?php
    // http://v2.wp-api.org/guide/authentication
    wp_nonce_field( 'wp_rest' );
    ?>
    <label>username: <input type="text" name="username"></label>
    <label>email: <input type="text" name="email"></label>
    <label>password: <input type="password" name="password"></label>
    <h3>ACF</h3>
    <label>phone: <input type="text" name="fields[phone]"></label>
    <button type="submit">Save</button>
</form>`

The user is created but no acf data is stored, there is a custom field created and i have tried alot of different rule types.

**Comment by airesvsg** [comment]
Hello @DennisHalmstad,
Please, read this issue: https://github.com/airesvsg/acf-to-rest-api-example/issues/1

**Comment by DennisHalmstad** [comment]
hi and Ty @airesvsg .
But this is not as related as you may think. The issue you are referring is how to update an acf field on an existing user. 

I want to make a registration form using Angular, and collect some additional fields store them in user meta via ACF

Looking at the example above on a regular post using endpoint http://localhost/wp-json/wp/v2/posts/1 and sending  name="fields[site]" i tried to do something similar with users, the user is created. But (its not logged in) but no acf fields are stored.

Either the example isnot valid or something is handled differently on users

**Comment by airesvsg** [comment]
Hi @DennisHalmstad,
Please, try again.

Cheers

**Comment by DennisHalmstad** [comment]
no luck so far. 

using form
`<form action="http://localhost/v3/wp-json/wp/v2/users" method="POST">
    <?php    // http://v2.wp-api.org/guide/authentication
    wp_nonce_field( 'wp_rest' );
    ?>
    <label>username: <input type="text" name="username"></label>
    <label>email: <input type="text" name="email"></label>
    <label>password: <input type="password" name="password"></label>

    <h3>ACF</h3>
    <label>phone: <input type="text" name="fields[phone]"></label>
    <button type="submit">Save</button>
</form>`

> _wpnonce:a1993422da
> _wp_http_referer:/v3/objekt-zum-verkaufen/alles-objekt/
> username:5464356
> email:yuytr@email.com
> password:23423434
> fields[phone]:234324

**Comment by airesvsg** [comment]
Hi @DennisHalmstad,

Download my example theme:
[acf-to-rest-api-users.zip](https://github.com/airesvsg/acf-to-rest-api/files/165498/acf-to-rest-api-users.zip)

Note that you must be **logged in** with a user who has the privilege to create users.

**Comment by DennisHalmstad** [comment]
Sorry for late response. Its the logged in part that makes it problematic for me, since i want to set the information during registration (using a register user form) i can create the user and want to set acf(meta) values during post.
