### ISSUE TITLE
v3 endpoint fatal error.

### ISSUE THREAD

**Issue by vititu** [airesvsg/acf-to-rest-api#142]
When using v3, when going to "wp-json/wp/v2/posts" or "wp-json/acf/v3/posts", for example, I just get this error:

<b>Fatal error</b>:  Using $this when not in object context in <b>/{sitepath}/wp-content/plugins/acf-to-rest-api-3.0.0-beta/v3/lib/endpoints/class-acf-to-rest-api-controller.php</b> on line <b>54</b><br />

**Comment by airesvsg** [comment]
Hi @vititu,
What's the WordPress Version? 
Whats Plugins you are using?
Thanks

**Comment by vititu** [comment]
Hello, @airesvsg.
WordPress: 4.7.5

**Plugins:**
ACF to REST API
Admin Menu Editor
Advanced Custom Fields PRO
Better REST API Featured Images
Top 10
WP Migrate DB

**Comment by aksperiod** [comment]
I am also also having this problem. The only plugin we share is ACF PRO-- maybe it's the pro version?

**Comment by tannusesquerdo** [comment]
Same problem too. =/

**Comment by airesvsg** [comment]
Hi @tannusesquerdo,
Whats the WordPress & PHP Version?
Whats Plugins you are using?
Thanks

**Comment by husani** [comment]
Hi @airesvsg, I'm seeing this as well.

Fatal error: Using $this when not in object context in /acf-to-rest-api/v3/lib/endpoints/class-acf-to-rest-api-controller.php on line 54

WP v4.7.5
PHP v5.3.10-1ubuntu3.26

Can you reopen this issue? Happy to provide more info.

**Comment by airesvsg** [comment]
I removed the anonymous function in the current version ( 3.1.0 ).
Please, test again.

https://github.com/airesvsg/acf-to-rest-api/releases/tag/3.1.0

Thanks

**Comment by husani** [comment]
Hi @airesvsg, the update you made in v3.1.0 solved this issue for me, thank you!

**Comment by airesvsg** [comment]
The fix here 😄 
https://github.com/airesvsg/acf-to-rest-api/commit/6f7bff02aee8c0d33a87c0d11b72d05debc246f2#diff-08c6172184449b0af4a717e8ab2f86da
