### ISSUE TITLE
custom_post_type

### ISSUE THREAD

**Issue by florianschommertz** [airesvsg/acf-to-rest-api#143]
If I understand you right this should be working in v3:
http://localhost/wp-json/acf/v3/products/

The Result is a 404 in Postman while posts/pages work just perfectly

Do I need to register my custom name in some extra place? - it works fine in the backend and has »plenty« of ACF fields.

German WP btw.

Kind Regards
florian

**Comment by airesvsg** [comment]
Hi @florianschommertz,
please read it: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/
Thanks

**Comment by florianschommertz** [comment]
Hi Aires Gonçalves thank you for this super quick answer!

Will read.
