### ISSUE TITLE
Append ACF Field Label Value to JSon response

### ISSUE THREAD

**Issue by FMR1971** [airesvsg/acf-to-rest-api#144]
Hi Aires,

With ACF To Rest Api I can show in Wp Rest Api the values of the Field Name.
So if I have a custom field with Field Label “Year”, Field Name “year” and a value “2017” in json response I find:

“acf”: {
“year”: “2017”
},

but is it possible to show in Rest the Field Label too?
Or is it possible to show in Json response not the Field Name and his value but the Field Label with the value of Field Name?

I make this question because I’d like to translate the name of the field, but I can’t translate a field name but only a field label.
I hope I’ve been sufficiently clear exposing my problem.

Thank You for Your attention.

Filippo

**Comment by airesvsg** [comment]
Hi @FMR1971,
Use the filter `acf/rest_api/{type}/get_fields`. 
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

**V3**
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {

	return $data;
} );
```

**V2**
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $request, $response ) {
	if ( $response instanceof WP_REST_Response ) {
		$data = $response->get_data();
	}
	// 
	return $data;
}, 10, 3 );
```
Thanks

**Comment by FMR1971** [comment]
Hi Aires,

thank You very much for your answer.
I don't understand if I have to change the wildcard *{type}* with my custom
post type.

With Postman I call the url http://paolinocapri.com/en/wp-json/wp/v2/project
to show the custom fields of the portfolio items (project).
So your hook which were in this case?

add_filter( 'acf/rest_api/project/get_fields', function( $data,
$request, $response ) {	if ( $response instanceof WP_REST_Response )
{		$data = $response->get_data();	}	// 	return $data;}, 10, 3 );

Thank You very much

Filippo

2017-06-01 13:18 GMT+02:00 Aires Gonçalves <notifications@github.com>:

**Comment by bastienrobert** [comment]
Hi @airesvsg, can you please set an example ? My issue is approximately the same : i've a field and I want to set the label on the ACF API response, something like :
```
{
  ...
  "acf": {
    "photos_content": {
      "label": "Photos",
      "content" : [HERE IS AN ARRAY BECAUSE THE PHOTOS_CONTENT FIELD IS A REPEATER]
    }
  }
  ...
}
```
@FMR1971, any update on this ?
