### ISSUE TITLE
Gravity Forms to Custom Post Type Issue

### ISSUE THREAD

**Issue by siebird** [airesvsg/acf-to-rest-api#145]
I have a weird issue going on–not sure if it's Gravity Forms, ACF, or this plugin.

I have a Gravity Form form setup that creates a new custom post entry on submit. This works and all data is saved to the custom post type in WordPress. However, when I request the endpoint for that entry it returns blank. 

I need to login to WordPress, view the custom post entry and save it. Once saved through the admin panel, the endpoint works. 

Have any ideas what could be going on?

**Comment by airesvsg** [comment]
Hi @siebird,
Can you export the data and send for me? ( airesvsg@gmail.com )
Thanks

**Comment by siebird** [comment]
Sure, what data would you like exported?

**Comment by leepeterson** [comment]
Having the exact same issue. DIdn't think I'd find someone else with a similar use case. Latest ACF, latest GF, latest ACF->REST v3beta. 404 errors for rest.js and rest.css files. This is a brand new site as of 30 minutes ago. Only created 1 post type and enabled the basic plugins like usual. Not sure how to fix this one.

**Comment by airesvsg** [comment]
Hi @leepeterson,
Can I send for you a new version for you test?
I sent it to @siebird and it worked, if it works for you, I'll release this version.
Thanks
