### ISSUE TITLE
Problem sending POST data: rest_no_route

### ISSUE THREAD

**Issue by marseca** [airesvsg/acf-to-rest-api#147]
Hi!

I am trying to insert  a "incidence" into wordpress. Incidences is a custom post type that I create using Custom Post Types UI plugin. When I created I set "Show in REST API" as true. This "incidences" has two ACF fields: email and description.

To send this information I am using Postman with this data:
![captura de pantalla 2017-06-16 a las 19 56 28](https://user-images.githubusercontent.com/6795828/27238662-0eac761a-52ce-11e7-84fa-f03126cc81b2.png)

But the server responds 404: rest_no_route...But! I can GET the list of "incidences" using the same URL.
![captura de pantalla 2017-06-16 a las 20 00 42](https://user-images.githubusercontent.com/6795828/27238780-80b70e82-52ce-11e7-9ee5-6778b91c4ba3.png)

Is there some reason to this?

Wordpress 4.7.5
ACF 3.0.1-beta 
Advanced Custom Fields 4.4.11
Custom Post Type UI 1.5.3	
JSON Basic Authentication 0.1

**Comment by airesvsg** [comment]
Hi @marseca,
Please, read it: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by marseca** [comment]
Yes, I  properly authenticated with Basic Authentication.
I can insert data with this WP URLS:
http://localhost:8888/test/wp-json/wp/v2/incidences
![captura de pantalla 2017-06-16 a las 21 20 14](https://user-images.githubusercontent.com/6795828/27241655-0175d584-52da-11e7-83cc-e389da24bc03.png)


I only have problems when I  using ACF To Rest API. 

In short:
http://localhost:8888/test/wp-json/wp/v2/incidences - Works GET and POST
http://localhost:8888/test/wp-json/acf/v3/incidences - Only works GET

**Comment by marseca** [comment]
No work any ACF route with POST action

**Comment by airesvsg** [comment]
Hi @marseca,
Please, send me your files and database for my email (airesvsg@gmail.com).
Thanks

**Comment by airesvsg** [comment]
Hi **Hector**, 
I received your files.
Thanks

**Comment by amannn** [comment]
I've got the same issue. Could it be that this isn't possible as the `/wp-json/acf/v3/{post-type}` endpoint in the [README](https://github.com/airesvsg/acf-to-rest-api#endpoints) is specified as non-editable?

If someone wants to create a custom post with ACF values, is the expected workflow to create it first at `/wp-json/wp/v2/{post-type}` and then use the id in the result to write to `/wp-json/acf/v3/{post-type}/{id}`?

**Comment by WebAppEasy** [comment]
I just use the `/wp-json/wp/v2/{post-type}` to create new posts with the ACF fields.
Just fill in the body of the request all your ACF fields like: `fields[{acf_fieldname}]` and make sure the content type is FormUrlEncoded and **not JSON**.

The `/wp-json/acf/v3` only supports editable functions with an existing post. And there you will also only see the ACF fields. So if you also want to use the standard WP field, you can use the `/wp-json/wp/v2` in combination with ACF.

**Comment by stephanedemotte** [comment]
@airesvsg do you have a release date for create new post-type with the v3 ?

**Comment by airesvsg** [comment]
Hi @stephanedemotte!

No make sense this endpoint to be creatable, beacause we'll need the object to create the relation between them.

Please use the WordPress endpoints. 
https://github.com/airesvsg/acf-to-rest-api/issues/147#issuecomment-312624693

Thanks

**Comment by stephanedemotte** [comment]
So we have to create a new post with `wp-json/wp/v2` and edit it with `wp-json/acf/v3` ?

Thanks for this useful plugin !

**Comment by airesvsg** [comment]
@stephanedemotte Yes, you can also to use the endpoints `wp-json/wp/v2` to edit. 

:smiley: :+1:
