### ISSUE TITLE
Modify the response.

### ISSUE THREAD

**Issue by madmax124** [airesvsg/acf-to-rest-api#148]
My current json response is:
- acf: { new:false, time:[{"A":"10","B":"20"}] }

Required json response
 - acf: { new:false, time:{"A":"10","B":"20"} }

I want to remove the square brackets [] from acf_fc_layout.

Please help.

**Comment by airesvsg** [comment]
Hi @madmax124,
Use the filter `acf/rest_api/{type}/get_fields`. 
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

**V3**
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
	// your code here
	return $data;
} );
```

**V2**
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $request, $response ) {
	if ( $response instanceof WP_REST_Response ) {
		$data = $response->get_data();
	}
	// your code here
	return $data;
}, 10, 3 );
```
Thanks
