### ISSUE TITLE
404 error for /wp-json/acf/v2/post/

### ISSUE THREAD

**Issue by kdpuvvadi** [airesvsg/acf-to-rest-api#15]
Installed ACF TO REST API plugin on fresh install of wordpress with 2 acf fields created.

**Comment by airesvsg** [comment]
Hi @kdpuvvadi,

Please, see this issue: https://github.com/airesvsg/acf-to-rest-api/issues/11#issuecomment-178271552

**Comment by airesvsg** [comment]
Hi @kdpuvvadi,

The endpoint `/wp-json/acf/v2/post/` doesn't exists, you need to inform the post ID `/wp-json/acf/v2/post/{post_id}`.
