### ISSUE TITLE
Return a post per subfield

### ISSUE THREAD

**Issue by dsabatier** [airesvsg/acf-to-rest-api#150]
Hey all,

I've had a lot of luck resolving issues going through the docs and previous issues but I am not sure where to start with my current problem:

I have a post type, Exhibits, which has a repeater field called Sessions.  Sessions contains a location, start_time and end_time. What I am hoping to put together is a response that will return one object per session found, and then also be able to make use of order_by and per_page.

My data right now, from the regular wp/v2/exhibits route is something like this:

```
{
  id: 111,
  ...other post info (content, title, etc)
  acf: {
    sessions: [
      {
         uid: "50913flahd",
         day: "07/29/2017",
         start_time: "12:00",
         end_time: "13:00",
         location: { ... }
      },
      {
         uid: "3948fkjhd",
         day: "07/28/2017",
         start_time: "13:00",
         end_time: "14:00",
         location: { ... }
      }
    },
    id: 222,
    ...
    acf: {
    sessions: [
      {
         uid: "54145flahd",
         day: "07/29/2017",
         start_time: "14:00",
         end_time: "15:00",
         location: { ... }
      },
      {
         uid: "3948fkjhd",
         day: "07/28/2017",
         start_time: "15:00",
         end_time: "16:00",
         location: { ... }
      }
    },
```
But what I need is something like this (a new object for each session with all of the related posts info):

```
  [
      {
         id: 111
          ...other post info (content, title, etc),
         uid: "54145flahd",
         day: "07/29/2017",
         start_time: "12:00",
         end_time: "13:00",
         location: { ... }
      },
      {
         id: 111
          ...other post info (content, title, etc),
         uid: "3948fkjhd",
         day: "07/29/2017",
         start_time: "13:00",
         end_time: "14:00",
         location: { ... }
      },
]
```

Am I barking up the wrong tree in my approach?  I could use some help making use of the API, or if I'm going about this the wrong way I'm open to suggestions.  Thanks in advance, hopefully this is enough info.

**Comment by dsabatier** [comment]
I wound up just writing a sql query for this but I would be curious to see how one might accomplish it another way :)

**Comment by airesvsg** [comment]
Hi @dsabatier,
Use the filter `acf/rest_api/{type}/get_fields`. 
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

**V3**
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
  if ( ! empty( $data['sessions'] ) ) {
    foreach ( $data['sessions'] as &$s ) {
      $s['post_info'] = get_post( $s['id'] );
    }
  }
  
  return $data;
} );
```

Thanks

**Comment by dsabatier** [comment]
Thanks, I tried that before but there must have been an issue with my implementation.  I will give it another go and see how it differs from the sql query.  Thanks for the great plug-in!
