### ISSUE TITLE
Cannot update item

### ISSUE THREAD

**Issue by rmohan92** [airesvsg/acf-to-rest-api#151]
Hey,

I'm trying to update ACF fields using the plugin.
Im using curl statements, but Im getting 'cannot_update_item' error 500.

Here is the code thats supposed to update the fields:
    
    $external_url = 'http://xxx.com/wp-json/acf/v3/pages/2/pub_name/';

    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $external_url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "PUT",
        CURLOPT_HTTPHEADER => array(
            'Content-Type: application/json;charset=UTF-8',
            'Authorization: Basic ' . base64_encode($username . ':' . $password),
            'cache-control: no-cache',
        ),
        CURLOPT_POSTFIELDS => $json_result->acf->pub_name,
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

The $json_result->acf->pub_namevariable contains a string.

Any idea what I'm doing wrong?

Thanks

Edit: The flow of the program is - User saves data on 'website1', once the data is saved it should change on 'website2'. Website1 and Website2 have idenctical ACF fields - api plugins etc

**Comment by airesvsg** [comment]
Hi @rmohan92,
please replace it:
```PHP
CURLOPT_POSTFIELDS => $json_result->acf->pub_name,
```
to
```PHP
CURLOPT_POSTFIELDS => json_encode( array( 'fields' => array( 'pub_name' => 'My test' ) ) )
```
Use the plugin below to use basic authentication:
https://gist.github.com/airesvsg/e8eeb54cf724284cbe5cf80a2b0451a1

Thanks

**Comment by meowsus** [comment]
@airesvsg Dude, ya saved my life!
