### ISSUE TITLE
field names for related field of type User

### ISSUE THREAD

**Issue by bjoernklose** [airesvsg/acf-to-rest-api#152]
Hey there and thanks for the excellent plugin.

I'm working with an ACF Field that has the field type **User**

To be able to properly set it, I'm preloading all users via the regular `/users` wp-api route.

Interestingly enough, the format for both differs quite a bit, so I was wondering if there'll be a chance to make them show up in the same format:

Example:
https://developer.wordpress.org/rest-api/reference/users/ and
http://v2.wp-api.org/reference/users/ lists
`id, username, name, first_name, last_name, email`

while my `acf` field now has the following:

`ID, nichname, display_name, user_firstname, user_lastname, user_email`

I'm working around this for now, but still wanted to point this out as it might lead to confusion for others.

Thanks

Best wishes
Björn

**Comment by airesvsg** [comment]
Hi @bjoernklose,
In that issue https://github.com/airesvsg/acf-to-rest-api/issues/153#issuecomment-316070237 I used post type to format, so you'll need to change to user.
Thanks
