### ISSUE TITLE
Apply same post format as WP JSON if ACF return format is Post Object

### ISSUE THREAD

**Issue by tolgap** [airesvsg/acf-to-rest-api#153]
I would like to apply the same WP Rest API formatting to my ACF field values if the return format of that field is `Post object`. Right now, we can't reuse any code we write for a detail page and it's nested ACF related posts, because they are two completely different formats, see:

```
[
  {
    "id": 2,
    "date": "2017-06-30T11:29:19",
    "date_gmt": "2017-06-30T11:29:19",
    "guid": {
      "rendered": "http:\/\/localhost:8080\/?page_id=2"
    },
    "modified": "2017-06-30T15:47:57",
    "modified_gmt": "2017-06-30T15:47:57",
    "slug": "sample-page",
    "status": "publish",
    "type": "page",
    "link": "http:\/\/localhost:8080\/",
    "title": {
      "rendered": "Sample Page"
    },
    "content": {
      "rendered": "<p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:<\/p>\n<blockquote><p>Hi there! I&#8217;m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin&#8217; caught in the rain.)<\/p><\/blockquote>\n<p>&#8230;or something like this:<\/p>\n<blockquote><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.<\/p><\/blockquote>\n<p>As a new WordPress user, you should go to <a href=\"http:\/\/localhost:8080\/wp\/wp-admin\/\">your dashboard<\/a> to delete this page and create new pages for your content. Have fun!<\/p>\n",
      "protected": false
    },
    "excerpt": {
      "rendered": "<p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this: Hi there! I&#8217;m a bike messenger [&hellip;]<\/p>\n",
      "protected": false
    },
    "author": 1,
    "featured_media": 0,
    "parent": 0,
    "menu_order": 0,
    "comment_status": "closed",
    "ping_status": "open",
    "template": "",
    "meta": [
      
    ],
    "acf": {
      "related_posts": [
        {
          "ID": 1,
          "post_author": "1",
          "post_date": "2017-06-30 11:29:19",
          "post_date_gmt": "2017-06-30 11:29:19",
          "post_content": "Welcome to WordPress. This is your first post. Edit or delete it, then start writing!",
          "post_title": "Hello world!",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "open",
          "ping_status": "open",
          "post_password": "",
          "post_name": "hello-world",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2017-06-30 11:29:19",
          "post_modified_gmt": "2017-06-30 11:29:19",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/localhost:8080\/?p=1",
          "menu_order": 0,
          "post_type": "post",
          "post_mime_type": "",
          "comment_count": "1",
          "filter": "raw"
        }
      ]
    }
  }
]
```

As you can see, the `related_posts` key is a post as well, but has a completely different format to the parent post.

I have seen issue #109 but no solution was provided there for this particular issue.

Is this possible using filters right now? If so. how?

**Comment by hbwoodrose** [comment]
same issue here :(

**Comment by airesvsg** [comment]
Hi @tolgap,
I used this solution https://github.com/airesvsg/acf-to-rest-api/issues/109#issuecomment-286403063 and it worked for me.
![image](https://user-images.githubusercontent.com/396668/28292780-13debd02-6b27-11e7-85f0-5d6febcba416.png)
![related-posts](https://user-images.githubusercontent.com/396668/28292763-f2285efc-6b26-11e7-9cb0-fe4d2e971a94.png)
Thanks

**Comment by tolgap** [comment]
@airesvg but that related post does not look anything like the parent post. It's just a flat json.

**Comment by airesvsg** [comment]
@tolgap I did this test, I related posts with pages and _vice versa_.

![1-field-groups](https://user-images.githubusercontent.com/396668/28295760-8b7c5e20-6b39-11e7-99ef-8f523aaafab9.png)

![2-field-group-posts](https://user-images.githubusercontent.com/396668/28295761-8b7dd908-6b39-11e7-9623-9dc00ccb1d61.png)

![3-field-group-pages](https://user-images.githubusercontent.com/396668/28295763-8b80dff4-6b39-11e7-8cc2-ab6c4549a398.png)

![4-posts](https://user-images.githubusercontent.com/396668/28295759-8b7c47dc-6b39-11e7-85ce-8d6fad345911.png)

![5-post-hello-world](https://user-images.githubusercontent.com/396668/28295762-8b7defce-6b39-11e7-941d-6e4e6380cee3.png)

![6-post-my-second-post](https://user-images.githubusercontent.com/396668/28295764-8b83fbd0-6b39-11e7-89e9-0edb20fe33a4.png)

![7-pages](https://user-images.githubusercontent.com/396668/28295765-8b976e0e-6b39-11e7-821c-300c0c2b175f.png)

![8-page-sample-page](https://user-images.githubusercontent.com/396668/28295830-300c9216-6b3a-11e7-92c6-95ea7b3d3f5b.png)

![9-page-lorem-ipsum](https://user-images.githubusercontent.com/396668/28295767-8b9a0d62-6b39-11e7-9091-27dfd1e8a6eb.png)

<p align="center"><img src="https://user-images.githubusercontent.com/396668/28295766-8b98f0f8-6b39-11e7-8ed4-35ac4c00a495.png"></p>

![11-answer](https://user-images.githubusercontent.com/396668/28295768-8b9f2da6-6b39-11e7-98c8-31fa30dd4f6b.png)

**Comment by tolgap** [comment]
@airesvsg ah I see what you mean 😄 . But that wasn't what I mean. Sorry if my last comment came out a bit irritated, I just typed it quickly on my phone 😅 .

What I mean is:

When I request a post using `/wp-json/v2/posts/1`, the JSON schema is like this:

```
  {
    "id": 2,
    "date": "2017-06-30T11:29:19",
    "date_gmt": "2017-06-30T11:29:19",
    "guid": {
      "rendered": "http:\/\/localhost:8080\/?page_id=2"
    },
    "modified": "2017-06-30T15:47:57",
    "modified_gmt": "2017-06-30T15:47:57",
    "slug": "sample-page",
    "status": "publish",
    "type": "page",
    "link": "http:\/\/localhost:8080\/",
    "title": {
      "rendered": "Sample Page"
    },
    "content": {
      "rendered": "<p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:<\/p>\n<blockquote><p>Hi there! I&#8217;m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin&#8217; caught in the rain.)<\/p><\/blockquote>\n<p>&#8230;or something like this:<\/p>\n<blockquote><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.<\/p><\/blockquote>\n<p>As a new WordPress user, you should go to <a href=\"http:\/\/localhost:8080\/wp\/wp-admin\/\">your dashboard<\/a> to delete this page and create new pages for your content. Have fun!<\/p>\n",
      "protected": false
    },
    "excerpt": {
      "rendered": "<p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this: Hi there! I&#8217;m a bike messenger [&hellip;]<\/p>\n",
      "protected": false
    },
    "author": 1,
    "featured_media": 0,
    "parent": 0,
    "menu_order": 0,
    "comment_status": "closed",
    "ping_status": "open",
    "template": "",
    "meta": []
  }
```

Which is great. That's much better than a flat JSON representation of the `wp_posts` table.

When I use ACF and this plugin, and add things with return format `post_object`, they look completely different though:

```
      {
          "ID": 1,
          "post_author": "1",
          "post_date": "2017-06-30 11:29:19",
          "post_date_gmt": "2017-06-30 11:29:19",
          "post_content": "Welcome to WordPress. This is your first post. Edit or delete it, then start writing!",
          "post_title": "Hello world!",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "open",
          "ping_status": "open",
          "post_password": "",
          "post_name": "hello-world",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2017-06-30 11:29:19",
          "post_modified_gmt": "2017-06-30 11:29:19",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/localhost:8080\/?p=1",
          "menu_order": 0,
          "post_type": "post",
          "post_mime_type": "",
          "comment_count": "1",
          "filter": "raw"
        }
```

What I would like, is for things with return format `post_object` to look more like the response from `wp-json/v2/posts/1`.

**Comment by airesvsg** [comment]
Hi @tolgap,
Try it:
```PHP
add_filter( 'acf/rest_api/post/get_fields', function( $data, $request, $response ) {
  if ( $response instanceof WP_REST_Response ) {
    $data = $response->get_data();
  }

  if ( ! empty( $data ) && isset( $data['acf']['related_posts'] ) ) {
    foreach ( $data['acf']['related_posts'] as &$rel ) {
      rest_api_format( $rel );
    }
  }

  return $data;
}, 10, 3 );

function rest_api_format( &$object ) {
  if ( isset( $object->post_type ) ) {
    $post_type_object =  get_post_type_object( $object->post_type );
    
    $request = new WP_REST_Request( 
      'GET',
      sprintf( '/wp/v2/%s/%d', ! empty( $post_type_object->rest_base ) ? $post_type_object->rest_base : $post_type_object->name, $object->ID )
    );
    
    $response = rest_do_request( $request );
    
    if ( ! $response->is_error() ) {
      $object = $response->get_data();
    }   
  }
}
```
Thanks

**Comment by tolgap** [comment]
@airesvsg I ended up doing exactly that, thanks!

Here is the PR if anyone is curious: https://github.com/paramander/wp-headless-theme/pull/1/files

**Comment by qikkeronline** [comment]
HI @tolgap - I'm using this approach (not the exact same logic though, modified to my needs) to convert a regular post object to an object that matches the scheme that the api uses. And it works great - thanks!

However, when i invoke the function that uses this logic, and use it's output in a field in a json api response, then all following fields seem to take the post ID from the last post that was in the relationship or post object field in stead.

I've traced this back to WP_REST_Posts_Controller::prepare_item_for_response (which is called by an instance of WP_REST_Request). There it does a `setup_postdata` call, but this is not reset at any point. 

Are you experiencing similar issues? i have also tried using your logic 1:1 and it yields the same result for me.

The original function I had for this (mostly based on your logic), and that has the issue:

```
		function convert_post_object_to_rest_response($post)
		{

			global $wp_rest_server;
			$post_type = get_post_type_object($post->post_type);

			$request = WP_REST_Request::from_url(rest_url(sprintf('wp/v2/%s/%d', $post_type->rest_base, $post->ID)));
			$request = rest_do_request($request);
			$data = $wp_rest_server->response_to_data($request, isset($_GET[ '_embed' ]));

			return $data;

		}
```
I have for now managed to work around this by also passing the original post id as parameter to the same function, and by setting `$GLOBALS[ 'post' ] = $original_post_id;` just before i return the data.

**Comment by qikkeronline** [comment]
Have reported this on core trac btw: https://core.trac.wordpress.org/ticket/43502#ticket

**Comment by tolgap** [comment]
@qikkeronline I haven't seen that issue myself. But I haven't really put much time into it, nor used this solution in `the_loop`.

**Comment by qikkeronline** [comment]
Allright, thanks! The ticket on core is picked up and it will be fixed in WP 4.9.5.

For the people who are also looking for this, below is the function I wrote. What it does is converting the post object that any relationship or post object field returns, and converts it to an object that matches the scheme of the API. this means that all of these fields will now return a normal post in the rest api format, also containing all of it's child ACF fields etc.

```
<?php

	function QikkerAcfPostObjectFix()
	{

		function qikker_fix_acf_post_ojects($value, $original_post_id, $field)
		{

			if ($field[ 'return_format' ] !== 'object') {

				return $value;

			}

			remove_filter('acf/format_value/type=relationship', 'headless_theme_format_post_object_value', 20);
			remove_filter('acf/format_value/type=post_object', 'headless_theme_format_post_object_value', 20);

			if (is_array($value)) {

				foreach ($value as $post) {

					$formatted[] = convert_post_object_to_rest_response($post, $original_post_id);

				}

			} else {

				$formatted = convert_post_object_to_rest_response($value, $original_post_id);

			}

			add_filter('acf/format_value/type=relationship', 'headless_theme_format_post_object_value', 20, 3);
			add_filter('acf/format_value/type=post_object', 'headless_theme_format_post_object_value', 20, 3);

			return $formatted;

		}

		function convert_post_object_to_rest_response($post, $original_post_id)
		{

			global $wp_rest_server;
			$post_type = get_post_type_object($post->post_type);

			$request = WP_REST_Request::from_url(rest_url(sprintf('wp/v2/%s/%d', $post_type->rest_base, $post->ID)));
			$request = rest_do_request($request);
			$data = $wp_rest_server->response_to_data($request, isset($_GET[ '_embed' ]));

			// For the line below, see https://core.trac.wordpress.org/ticket/43502#ticket
			$GLOBALS[ 'post' ] = $original_post_id;

			return $data;

		}

		add_filter('acf/format_value/type=relationship', 'qikker_fix_acf_post_ojects', 20, 3);
		add_filter('acf/format_value/type=post_object', 'qikker_fix_acf_post_ojects', 20, 3);

	}

	add_action('rest_api_init', 'QikkerAcfPostObjectFix');
```

**Comment by timbomckay** [comment]
@qikkeronline Can you explain why you're removing & adding the same filter so many times?

**Comment by tolgap** [comment]
@timbomckay 

The lowest `add_filter` are the ones to actually use it. The lines where they remove and add it is so that they can use recursion, but only do nesting once.

**Comment by fredericpfisterer** [comment]
@timbomckay How can I do nesting twice ? I have a post object inside a relationship field and I can't get acf and _embed data returned in the rest api using your code.

**Comment by thelucre** [comment]
@fredericpfisterer You can remove the calls to `remove_filer` and `add_filter` inside the filter callback to get true recursion.

**Comment by supunbatagoda** [comment]
> @airesvsg I ended up doing exactly that, thanks!
> 
> Here is the PR if anyone is curious: https://github.com/paramander/wp-headless-theme/pull/1/files

Hi @tolgap I applied your changes, but in my scenario It's works only post type 'post' only. I just want to add more post type. could you please give any help it would be great. 
I really appreciate.
Thanks mate.
![Selection_107](https://user-images.githubusercontent.com/5137720/78999280-eca05580-7b67-11ea-84a4-91286a694ae6.png)

**Comment by simongoot** [comment]
@supunbatagoda It is the rest_base that is not defined for custom post types, so you need a fallback to the post_type name as the rest_base if no other is defined.

```
$post_type_object = get_post_type_object( $post->post_type );

        // If rest_base is defined, use it, otherwise fallback to post type name
        if(isset($post_type_object->rest_base) && !empty($post_type_object->rest_base)) {
           $rest_base = $post_type_object->rest_base;
        } else {
            $rest_base = $post->post_type;
        }

        $request = WP_REST_Request::from_url( rest_url( sprintf( 'wp/v2/%s/%d', $rest_base, $post->ID ) ) );
```

**Comment by thisischrisj** [comment]
Another option is to just use ACF filters instead to catch all post objects field types wherever they are in the tree:

```
function acf_post_object_value($value, $post_id, $field)
{
	if($field['return_format'] == 'object')
	{
		if(is_array($value))
		{
			for($i=0; $i < count($value); $i++)
			{
				$value[$i] = get_post($value);
				$value[$i]->acf = get_fields($value[$i]->ID);
			}
		}
		else
		{
			$value = get_post($value);
			$value->acf = get_fields($value->ID);
		}
	}

	return $value;
}
add_filter('acf/format_value/type=post_object', 'acf_post_object_value', 20, 3);
```

Note that the priority is set to 20. It must be > 10 otherwise `$value` will contain the post ID and not the post object. You can also adjust the filter to only match certain field names or keys.
