### ISSUE TITLE
Gatsby Static Site Generator plugin for acf-to-rest-api

### ISSUE THREAD

**Issue by sebastienfi** [airesvsg/acf-to-rest-api#154]
Hi guys,

Just to let you know that the acf-to-rest-api endpoints are [integrated into a plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress) for [Gatsby](https://github.com/gatsbyjs/gatsby), a blazing-fast static site generator for React. So now you can easily build a static site with React using Wordpress as a back-end.

Not all the endpoints are enabled yet, what would you like to see enabled at that point ?
- [x] v2 : posts
- [x] v2 : pages
- [x] v2 : tags
- [x] v2 : categories
- [x] v2 : medias
- [x] v2 : types
- [x] v2 : users
- [x] v2 : statuses
- [x] v2 : taxonomies
- [x] v3 : posts
- [x] v3 : pages
- [x] v3 : tags
- [x] v3 : categories
- [x] v3 : medias
- [x] v3 : types
- [x] v3 : users
- [x] v3 : statuses
- [x] v3 : taxonomies
- [x] v3 : custom post types

**Comment by airesvsg** [comment]
Hi @sebastienfi,
please read it: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/
Thanks

**Comment by sebastienfi** [comment]
Thanks ! I've integrated the custom post types.
Give it a try !
