### ISSUE TITLE
Add new data to repeater without sending full data array

### ISSUE THREAD

**Issue by linasslepikas** [airesvsg/acf-to-rest-api#155]
Hello there, 
first of all thank you for this plugin, great job! I have one question/problem about how to update set of repeater field data without having to get all existing data, then push to that array new data values and send it back to API - this is how it is done in your example. When I send just new values, API removes old ones and leaves new ones, does not matter if it is PUT or POST request. Any help would much appreciated to avoid big set of data to be sent each time. Thank you!

**Comment by airesvsg** [comment]
Hi @linasslepikas,
Please, use the filter `acf/rest_api/{type}/prepare_item`. 
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

How to use:
```PHP
add_filter( 'acf/rest_api/post/prepare_item', function( $data, $request ) {
  // insert your logic here
  return $data;
}
```

Thanks

**Comment by kmaric69** [comment]
Hi @airesvsg ,
First of all I love your plugin very much :) great work on that.

Could you explain how to use this filter? I'm new to ACF Rest API and I have the same issue as @linasslepikas. What kind of logic do I need to insert to update just one field?

I see that it works when I send back the whole response with the updated subfield I want to change, but I would like to avoid sending the whole response every time.

Thank you in advance :)
