### ISSUE TITLE
Not showing "settings" in plugins page

### ISSUE THREAD

**Issue by jbwestphal** [airesvsg/acf-to-rest-api#156]
I just installed the plugin, v3 beta, and didn't show the menu "Settings", for configurate the plugin. I'm using the latest Wordpress version.

**Comment by airesvsg** [comment]
Hi @jbwestphal,
What's the plugin folder name?
If the plugin folder name is different this **acf-to-rest-api**, please rename it.

Can you see the second step? 
https://github.com/airesvsg/acf-to-rest-api#request-api-version

Thanks

**Comment by jbwestphal** [comment]
Oh, that's why! I already managed throught add_filters(), thanks, it's working =)
