### ISSUE TITLE
Endpoint only returns ten items

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [airesvsg/acf-to-rest-api#157]
First of all: Thank you for this nice plugin. However, I stumbled over something strange: The routes work for me, but whatever I try, the returned json arry contains maximum ten array items. I tried this with several custom post types and with the posts itself. 

While I have only 8 posts in my news section, I have a CPT with more than 450 entries and another with around 25 enries. The posts json retuns the 8 items correct, but the other two CPT only return the last ten entries.

When I use the endpoint media, the returned json as well returns only the last ten entries. And as if that is not enough, the endpoint users only returns one entry, the user with the id 1.

I rechecked this with postman on chrome, as well as firefox. Am I missing something? Help is gladly appreciated.

Greetings from Germany

**Comment by sixtyseven-multimedia** [comment]
Well, I am getting closer to the problem. Seem sthat there is a per_page parameter that has a default value of 10 and a maximum value of 100. So adding ?per_page=100 to the endpoints gives me more results. But that does not really solves my problem. How can I overcome this 100 entries level?

**Comment by airesvsg** [comment]
Hi @sixtyseven-multimedia,
Please try it: https://github.com/airesvsg/acf-to-rest-api/issues/89#issuecomment-262862145
Thanks
