### ISSUE TITLE
v3 taxonomy is empty

### ISSUE THREAD

**Issue by stephanedemotte** [airesvsg/acf-to-rest-api#158]
Hi, i try to get taxonomy from acf-to-rest-api, but i got an empty array....

Here the response with wp
<img width="753" alt="screen shot 2017-07-20 at 1 04 50 pm" src="https://user-images.githubusercontent.com/2158130/28429820-1ace7112-6d4c-11e7-9dd0-6e318b75c12c.png">

Here with acf
<img width="522" alt="screen shot 2017-07-20 at 1 05 42 pm" src="https://user-images.githubusercontent.com/2158130/28429837-29d0861e-6d4c-11e7-9c46-1d7f7ce62bd1.png">

Anyone an idea ?

**Comment by airesvsg** [comment]
Hi @stephanedemotte,
Please, use the param [hide_empty](https://developer.wordpress.org/reference/classes/wp_term_query/__construct/#parameters):
http://dtp-testimony-api.demotte.net/wp-json/acf/v3/masks_tags?hide_empty=0

Thanks
