### ISSUE TITLE
Slow requests using this plugin with ACF Pro Repeater

### ISSUE THREAD

**Issue by alexkappel** [airesvsg/acf-to-rest-api#16]
Without plugin and no ACF fields = instant
Using: /wp-json/acf/v2/post/{id} OR /wp-json/wp/v2/post/{id}

With plugin and a couple of meta fields and repeaters = 25 seconds
Using: /wp-json/acf/v2/post/{id} OR /wp-json/wp/v2/post/{id}

Any chance to tweak the code for this proccess?

**Comment by airesvsg** [comment]
Hi @alexkappel,
I use the functions of ACF. 

Please, send me your files and database for my email (airesvsg@gmail.com).

Thanks

**Comment by airesvsg** [comment]
Hi @alexkappel,
I use the functions of ACF. 

Please, send me your files and database for my email (airesvsg@gmail.com).

Thanks

**Comment by tankbar** [comment]
Worked a lot better with PHP7 in nginx. I'll get back if we stumple upon more problems with this.

**Comment by motmotstudiostudio** [comment]
Hi there, has this issue been resolved? I ran into exactly the same problem.
