### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by gck303** [airesvsg/acf-to-rest-api#160]
I am able to retreive ACF data. However, when I try updating the ACF fields I get a 403 rest_forbidden error. 

What could be wrong? I have put my python code below, but I suspect that there in an authorization that needs enabling in WordPress. 

Both the 'get' calls work fine, but neither the put nor post calls do. 

Many thanks for a fantastic plugin!

ACF to REST - 3.0.1
ACF - 4.4.11
WP - 4.7.3
WC - 2.6.14
_________________________________
acfapi = API(
    url="http://camleyphoto.staging.wpengine.com/",
    consumer_key="ck_d358b71ea2cba9d23f3ec8439e9e01b574ce4dd0",
    consumer_secret="cs_786c71191f03a4079741ba248a5560450f5d2abc",
    wp_api=True,
    version="acf/v3"
)

acf_data = {
           "fields" : {
              "camley_cost_price" : "987987",
                      }
                }

print(acfapi.post("posts/59938/camley_cost_price", acf_data).json())
print(acfapi.post("posts/59938", acf_data).json())

print(acfapi.put("posts/59938/camley_cost_price", acf_data).json())
print(acfapi.put("posts/59938", acf_data).json())

print(acfapi.get("posts/59938/camley_cost_price").json())
print(acfapi.get("product/72380").json())

**Comment by airesvsg** [comment]
Hi @gck303,
The link below has some orientations about how to works the authentication in the "rest api".
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Thanks
