### ISSUE TITLE
Plugin settings not displaying in WordPress dashboard

### ISSUE THREAD

**Issue by wickedurge** [airesvsg/acf-to-rest-api#162]
The page title says the core of the issue. I've tried the plugin using both the WP plugin directory and this repo with no luck. All I can do is activate and deactivate the plugin.

The fields do appear in the REST API, but I have no way of controlling which fields are visible and which aren't. 
 
[Screen shot](http://imgur.com/a/N6wrc)

I'm running version 3.0.1-beta on WordPress 4.8.

**Comment by airesvsg** [comment]
Hi @wickedurge,
Please read it: https://github.com/airesvsg/acf-to-rest-api/issues/156
Thanks

**Comment by gck303** [comment]
Thank you. When I installed it the folder was called 'acf-to-rest-api-master'.

I have renamed the directory on the server and now the settings link appears!

George

**Comment by wickedurge** [comment]
Oh! I see now. Thank you for the help.

**Comment by airesvsg** [comment]
Hi @wickedurge,
Whats version you are using?
This setting only available on V3.
Thanks

**Comment by wickedurge** [comment]
I'm running Version 3.0.1-beta

**Comment by airesvsg** [comment]
Whats your acf version?

**Comment by wickedurge** [comment]
ACF Pro: Version 5.5.14
ACF: Version 4.4.11

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api#field-settings

```PHP
// Enable the option show in rest
add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );

// Enable the option edit in rest
add_filter( 'acf/rest_api/field_settings/edit_in_rest', '__return_true' );
```
