### ISSUE TITLE
ACF Fields not retrieved for terms

### ISSUE THREAD

**Issue by MaximeCulea** [airesvsg/acf-to-rest-api#163]
When a taxonomy is `show_in_rest => true`, the ACF fields attached to this taxonomy's terms should appear in response. 
But they do not :(

**Comment by airesvsg** [comment]
Hi @MaximeCulea,
please follow that issue: https://github.com/airesvsg/acf-to-rest-api/issues/158
Thanks

**Comment by MaximeCulea** [comment]
@airesvsg 
Just submitted a patch, I let you review it.
Thx.

**Comment by MaximeCulea** [comment]
What the relation ? Oo
Anyway, got the patch.
Waiting your feedback, thx.

**Comment by mathiasmadsen** [comment]
I have the same issue and tried with the fix above. Nu success, unfortunately.

**Comment by MaximeCulea** [comment]
Working like a charm for me 👌

**Comment by mathiasmadsen** [comment]
Sorry, works now. I guess I was met by a caching issue :)
Thanks for the patch!
