### ISSUE TITLE
Strange response

### ISSUE THREAD

**Issue by KuneStudio** [airesvsg/acf-to-rest-api#165]
Hi !

When I try to call /wp-json/acf/v3/centers , or /wp-json/acf/v3/centers/ , response is: 
`[{"id":63,"acf":{"location":"Bern"}},{"id":62,"acf":[]}]`
Why do I only get the ID and not the rest of the post ? Like the title and the content ?
Thanks a lot !

**Comment by airesvsg** [comment]
Hi @KuneStudio,
Use the WordPress endpoint to retrieve others data.
`/wp-json/wp/v2/centers` 
Thanks
