### ISSUE TITLE
Cannot Update ACF Field

### ISSUE THREAD

**Issue by roydezign** [airesvsg/acf-to-rest-api#167]
I cannot update the ACF field and I believe its due to the ACF field not being in the main wp-json/wp/v2 options for the method PUT. It shows it in the methods under wp-json/acf/v3. I need to be able to update the ACF field along with the normal Wordpress fields so how can I add the ACF key to the main REST options?

**Comment by airesvsg** [comment]
Hi @roydezign,
Please, provide me more information. 

How you are send your fields? [Read it](https://github.com/airesvsg/acf-to-rest-api#editing-the-fields)

Thanks

**Comment by roydezign** [comment]
@airesvsg I followed your instructions to add the field to REST and make it editable. I don't see why those options aren't standard. I also was confused because in the REST API is show ACF but will only update if you add fields:{field_name: 'content'}; instead of acf:{field_name:'content'} in the http request. I got it working now with those two changes.

**Comment by airesvsg** [comment]
Hi @roydezign,
Options pages doesn't have the same struct of posts.

Please, use the endpoint **/wp-json/acf/v3/options/{id}**.

Thanks
