### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by techpines** [airesvsg/acf-to-rest-api#17]
So this plugin looks great, but is there any authentication?

It kind of looks like if this plugin is activated, anybody could change whatever data they want to in the database.  Unless the edit capabilities are disabled by default...  

I just didn't see anything in the docs, thanks!

**Comment by zedley** [comment]
Your authentication question really applies to the API in general, not this ACF plugin in particular. Have you checked out http://v2.wp-api.org/guide/authentication/?

**Comment by techpines** [comment]
Cool, I thought that might be the case, thanks!
