### ISSUE TITLE
Removing some meta fields from lists

### ISSUE THREAD

**Issue by enhancers** [airesvsg/acf-to-rest-api#172]
Hi,
I'm trying to remove some of the ACF fields from the wp query since they have a huge performance impact on lists and are totally useless.

I already managed to tweak the response with "acf/rest_api/custom_post_type/get_fields" but remove fields there is not affecting performances at all.

What is the best way to selectively remove some ACF fields from lists in order to improve performances?

Many thanks

**Comment by airesvsg** [comment]
Hi @enhancers,
try to use it:
https://github.com/airesvsg/acf-to-rest-api#cache

Thanks
