### ISSUE TITLE
How to post into a repeater or sub field

### ISSUE THREAD

**Issue by gustavokrause** [airesvsg/acf-to-rest-api#173]
I would like to post into a repeater from the REST API, I tried something like that but it doesn't work.

`fields[repeater_name][sub_field_name]`

How can I set the form field name to post as a sub field?

**Comment by airesvsg** [comment]
Hi @gustavokrause,
Please, try it:
```
fields[repeater_name][0][sub_field_name]
fields[repeater_name][1][sub_field_name]
fields[repeater_name][...][sub_field_name]
```

Thanks

**Comment by gustavokrause** [comment]
Tks, It worked here! I guess it will solve what I need.
