### ISSUE TITLE
How to create a Custom Post that include relationships fields

### ISSUE THREAD

**Issue by aymeric75** [airesvsg/acf-to-rest-api#174]
Hello,

I have a Custom Post Type named "Reservation" with several fields like "arrival", "departure", but also "Chambre" and "evenement" which are relationship fields (i.e they corresponds to post types Chambre and Evenement respectively).

My question is:

Is there a way using the act-to-rest-api to easily build the JSON code for the Custom Post I just discribed ?

Thank you

**Comment by airesvsg** [comment]
Hello @aymeric75,
Please read it: https://github.com/airesvsg/acf-to-rest-api/issues/109#issuecomment-286403063

Thanks
