### ISSUE TITLE
Wordpress 4.8 breaks the plugin

### ISSUE THREAD

**Issue by bovas85** [airesvsg/acf-to-rest-api#176]
Hi there, I can't see the "settings" section in the plugins page for act-to-rest-api, and in advanced custom fields I don't see the switches to show / edit the custom field in the api.

<img width="690" alt="screen shot 2017-09-15 at 12 51 35" src="https://user-images.githubusercontent.com/16958684/30481063-b120aef6-9a14-11e7-862a-a072698620bc.png">

<img width="1007" alt="screen shot 2017-09-15 at 12 50 56" src="https://user-images.githubusercontent.com/16958684/30481036-8e642104-9a14-11e7-8ac8-6758258d0ff3.png">

**Comment by airesvsg** [comment]
Hi @bovas85,
please rename the plugin folder to: acf-to-rest-api and activate again.

Thanks

**Comment by bovas85** [comment]
Hi @airesvsg , that's the folder name in the plugins but it doesn't show any setting there.

I'm getting it to show in the rest call now, but I still can't choose whether to have it be editable or not

**Comment by airesvsg** [comment]
Hi @bovas85,
Please, copy the filters below and paste in your `functions.php` to enable the settings.
```
// Enable the option show in rest
add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );
// Enable the option edit in rest
add_filter( 'acf/rest_api/field_settings/edit_in_rest', '__return_true' );
```
https://github.com/airesvsg/acf-to-rest-api#field-settings

Thanks

**Comment by khejit** [comment]
@airesvsg 
I have a fresh WP 4.8 installation, ACF 4.4.11 and ACF to REST API 2.2.1.
I copied provided filters to functions.php and re-activated plugin, plugins folder is called acf-to-rest-api, and I do not see settings of this plugin nor options "Show in REST API", "Edit in REST API".

**Comment by airesvsg** [comment]
Hi @khejit,
I tested it now and I saw the options.
Thanks

![names](https://user-images.githubusercontent.com/396668/30643557-d9361c30-9de5-11e7-881e-7398e97bd215.png)

![plugins](https://user-images.githubusercontent.com/396668/30643559-daaa315a-9de5-11e7-8c53-77f64ba2f75b.png)

**ACF 4.4.11**
![acf-free](https://user-images.githubusercontent.com/396668/30643571-e3d6deae-9de5-11e7-89be-2f518deeaf1d.png)

**ACF PRO 5.6.2**
![acf-pro](https://user-images.githubusercontent.com/396668/30643577-e7188022-9de5-11e7-897b-9a87f72026f9.png)

**Comment by sethcmiller** [comment]
Hi @airesvsg,
Those fields are not showing up in my experience. I have deactivated them, reactivated the plugins and tried creating new fields, etc and they still aren't showing up for me. Please see screenshots below:
![image](https://user-images.githubusercontent.com/32143464/30662744-035d41ac-9dfd-11e7-822a-c24f64a84892.png)
![image](https://user-images.githubusercontent.com/32143464/30662755-0ac88b86-9dfd-11e7-8070-efa1ff60801a.png)

Any other recommendations?
Thanks,
Seth

**Comment by airesvsg** [comment]
Hello @sethcmiller,

Did you use those filters?
https://github.com/airesvsg/acf-to-rest-api#field-settings

Thanks

**Comment by sethcmiller** [comment]
Thanks for the reply, @airesvsg,
Yes, I am using them in my theme's functions.php file:
![image](https://user-images.githubusercontent.com/32143464/30663361-3f256974-9dff-11e7-8f91-6e2e99349351.png)
Any other ideas?
Seth

**Comment by EvanAgee** [comment]
Ditto, any fix for this?

**Comment by airesvsg** [comment]
@sethcmiller Can you send your files ( theme and database dump )  to my email?
airesvsg@gmail.com

@EvanAgee In my tests, I can't simulate the error.

Thanks

**Comment by adamjw3** [comment]
@airesvsg I had the same issue when i had got the plugin from wordpress. If i use the beta version from git it works.

How do you get all the fields back? acf and standard wordpress in one call for a post or group of posts?

**Comment by bovas85** [comment]
There are other plugins that work

**Comment by airesvsg** [comment]
Please, send me your files.
airesvsg@gmail.com

**Comment by adamwright32** [comment]
Which plugins work? Many thanks. Will send files Monday

**Comment by bovas85** [comment]
It's recommended to use REST API Enabler

**Comment by adamwright32** [comment]
@airesvsg i've sent those files to you

**Comment by airesvsg** [comment]
Hi @adamwright32,
I haven't received your files yet.
Thanks

**Comment by adamwright32** [comment]
@airesvsg just sent again but this time via we transfer

**Comment by airesvsg** [comment]
Hi @adamwright32,
please, put the filters in the top of **functions.php** and it's will work.
I sent for your email the **functions.php**.
Thanks

**Comment by mathishuettl** [comment]
Hello,

same problems.

Wordpress Version: 4.8.2
ACF Pro Version: 5.6.2
Theme: Twentyseventeen

I added the Filters in top of my functions.php

I don't see the options

**Comment by adamwright32** [comment]
@airesvsg thats still not work, sent you an email.

**Comment by obedparla** [comment]
Same issue here. Added filters to functions.php and still doesn't work.

Wordpress: 4.8.2
ACF: 5.6.2
ACF to rest api: both 2.2.1 (latest from WP plugins) and the beta version 3.0.1 from github. 

Deactivated plugins a few times, recreated CFs and nothing.

**Comment by vicocotea** [comment]
Almost same issue for me.
I can't see the 'Settings' link in plugins page. I tried to enable V3 with : 
```
define('ACF_TO_REST_API_REQUEST_VERSION', 3);
```
and also :
```
add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );
add_filter( 'acf/rest_api/field_settings/edit_in_rest', '__return_true' );
```
but V3 API calls are not working (404) and buttons Edit/Show in rest aren't visible.
I can see acf fields in V2 api for posts (/wp-json/wp/v2/posts) but not for categories and tags.

I have a multisite install and I also use bedrock https://roots.io/bedrock/
I'll try asap to replicate this issue in single install without bedrock.

And thanks @airesvsg for this great plugin

**Comment by vicocotea** [comment]
Just tried in another website without multisite and without bedrock.
And issues are still there.

So this not related to multisite and/or bedrock.

**Comment by adamwright32** [comment]
@airesvsg any update on this issue, @vicocotea are you using acf pro version as well?

**Comment by vicocotea** [comment]
@adamwright32 yes, pro version.

**Comment by vicocotea** [comment]
I just tried with a wp basic install :
- wp 4.8.2
- twentyseventeen theme
- acf 4.4.12
- with or without acf pro 5.4.6
and still have the same issues (no v3 api call, no buttons in acf and acf fields in rest call for categories)

**Comment by vicocotea** [comment]
Humm sorry, I didn't see that v3 was on github not on wordpress plugin repository.
So I installed v3 (3.0.1-beta) and it works a lot better :)

I still not see the `Settings` button in plugins page. But I can now : 
- call the v3 api
- see acf fields in taxonomy api calls
- enable/disable Show/edit in rest api for each acf field

So I switch to v3 and hope the beta is pretty stable.

Thanks @airesvsg and sorry for the misunderstanding.
Maybe you can update the readme and/or publish the v3 on wordpress repository

**Comment by sebastienfi** [comment]
I migrated to WP 4.8.2 with ACF PRO and a lot of other plugins, and nothing broke with the latest version of `acf-to-rest-api`

**Comment by vicocotea** [comment]
Just looked a little bit more at this plugin (v3) maybe it can help.
Setting : 
`define('ACF_TO_REST_API_REQUEST_VERSION', 3);`
hide the `Settings` button in plugin page.

**Comment by adamwright32** [comment]
@vicocotea did you get it working?

i have the settings available but when i go to "http://localhost:8888/wp-json/acf/v3/article"

i got the below and no data from fields

[{"id":2381,"acf":[]},{"id":1637,"acf":[]},{"id":909,"acf":[]}]

**Comment by vicocotea** [comment]
@adamwright32 Yes it works with v3.
What's `article` ?

I just had an issue with `post_tag` and used this solution #43 

@airesvsg is it normal that I need this solution #43 in v3 (for post_tag/tags) ?

**Comment by adamwright32** [comment]
@vicocotea sorry i'm not sure what the fix is. 

what do i need to do?

**Comment by adamwright32** [comment]
@vicocotea article is a custom post type, i have other ones and they all return without content 

e.g http://localhost:8888/wp-json/acf/v3/ebook

`[{"id":2693,"acf":[]},{"id":2692,"acf":[]},{"id":2691,"acf":[]},{"id":2690,"acf":[]},{"id":2689,"acf":[]},{"id":2688,"acf":[]},{"id":2687,"acf":[]}]`

**Comment by vicocotea** [comment]
Sorry @adamwright32 I don't know. I just use posts, categories and tags.

**Comment by medinazdago** [comment]
@adamwright32 try with:
`//Adding post_types to wp-api rest
add_action( 'init', 'my_custom_post_type_rest_support', 25 );

function my_custom_post_type_rest_support() {

    global $wp_post_types;

//be sure to set this to the name of your post type!
    $post_type_name = 'property';

    if( isset( $wp_post_types[ $post_type_name ] ) ) {

        $wp_post_types[$post_type_name]->show_in_rest = true;
// Optionally customize the rest_base or controller class
        $wp_post_types[$post_type_name]->rest_base = $post_type_name;
        $wp_post_types[$post_type_name]->rest_controller_class = 'WP_REST_Posts_Controller';

    }

}`
