### ISSUE TITLE
Accessing custom fields on objects returned in custom fields

### ISSUE THREAD

**Issue by zedley** [airesvsg/acf-to-rest-api#18]
This is kind of an annoying question, and I apologize for that. I have a custom field on a post type (events) that is a post_object of another post type (documents). That documents post type also has its own set of fields. 

When I access the documents field on the events post through the API, I get the document post object but it does not have the document ACFs associated with it. I'm can't figure out if this is a hook or a filter I can access via your plugin, or if the proper answer is somewhere else in the REST API plugin or in ACF's hooks.

Thanks for any help you can give, even if the answer is just, "Nope, not here!"

**Comment by airesvsg** [comment]
Hi @zedley,

Please, see this issue: https://github.com/airesvsg/acf-to-rest-api/issues/9

Thanks

**Comment by zedley** [comment]
I did not check closed issues and am a bad person. Thanks!
