### ISSUE TITLE
Duplicate Url 

### ISSUE THREAD

**Issue by rafatriolo** [airesvsg/acf-to-rest-api#182]
Hi there, first of all it's a great plugin and it help's me a lot. But when I'm adding some images to a single post, and I put a url value into this images, it attach this images to this post, if I want to use this images to another post, this images come with the url to the previous post. Is this a way to not attach this images so I can use the same images to other post e put different urls on them. I don't know if a made my self clear. 

Tks

**Comment by airesvsg** [comment]
Hi @rafatriolo,
I didn't understand. Can you explain with more details?
Thanks

**Comment by rafatriolo** [comment]
Hi @airesvsg, tks for the fast reply. I want to attach the same image in two different posts. So when I put some information in url field of an image, and attach this image to another post, it comes with the url from the previous post. For example: I have post A with url field on his gallery, when I try to create a gallery on post B with same images from gallery in post A, this images comes with the url´s of the gallery on post A.

**Comment by rafatriolo** [comment]
![posta](https://user-images.githubusercontent.com/13166395/31340286-0c9fe088-acdc-11e7-8af7-4daf85d31d7a.PNG)
![postb](https://user-images.githubusercontent.com/13166395/31340287-0ca84d2c-acdc-11e7-9111-73bfd694f828.PNG)

**Comment by rafatriolo** [comment]
The image above, is from 2 different post. The url of this are the same and I want this url field to be different so I be able to change the url field from different posts

**Comment by airesvsg** [comment]
@rafatriolo please create a new issue [here](https://support.advancedcustomfields.com/new-ticket/).

Thanks
