### ISSUE TITLE
Get custom post types in a category

### ISSUE THREAD

**Issue by adamwright32** [airesvsg/acf-to-rest-api#183]
I want to return all custom post types posts (a list of articles) that are in a specific category.

e.g i have ebook, quickview, story post types.

All in category "insight"

How do i return them in the json?

if i do http://localhost:8888/wp-json/wp/v2/categories?slug=insight

its just returns an empty json 

[ ]

**Comment by airesvsg** [comment]
Hello @adamwright32,
your endpoint isn't correct, try it:
```
http://localhost:8888/wp-json/wp/v2/insight
```
To filter your custom post type use the parameter `categories`:
```
http://localhost:8888/wp-json/wp/v2/ebook?categories=insight
```
Visit the link below for more details
https://developer.wordpress.org/rest-api/reference/posts/#arguments

Thanks
