### ISSUE TITLE
Option Values Not Appearing

### ISSUE THREAD

**Issue by erwstout** [airesvsg/acf-to-rest-api#184]
Perhaps I am doing something wrong, but when trying to view option page field values, the response returned is empty. 

WP Version: 4.8.2
acf-to-rest-api version: 3.1.0
ACF Pro Version: 5.6.3 

I have an ACF Options page called "Sitewide Options" and it appears the ID is 148. When I use this ID to try get the fields using `http://mysite.dev/wp-json/acf/v3/options/148` it just returns a blank `acf: []` array.

Any thoughts? Am I using the wrong ID?

**Comment by airesvsg** [comment]
Hello @erwstout,

If you use that snippet:
```PHP
acf_add_options_page();
```
The endpoint is:
`http://mysite.dev/wp-json/acf/v3/options/options`

But if you register this way:
```PHP
acf_add_options_page(array(
	'page_title' => 'Theme General Settings',
	'menu_title' => 'Theme Settings',
	'menu_slug'  => 'theme-general-settings',
	'capability' => 'edit_posts',
	'redirect'   => false,
	'post_id'    => 'theme-general-settings'
));
```

Your endpoint is:
`http://mysite.dev/wp-json/acf/v3/options/{post_id}`
```PHP
acf_add_options_page(array(
	...
	'post_id'    => 'theme-general-settings'
));
```
The result is:
`http://mysite.dev/wp-json/acf/v3/options/theme-general-settings`

Thanks

**Comment by erwstout** [comment]
Awesome, that helped. Thank you @airesvsg

**Comment by petercrimson** [comment]
Hello and thank you for this great plugin.

Here is my issue:
http://mysite.dev/wp-json/acf/v3/options/theme-general-settings 
example does not work for me. It returns an empty array
http://mysite.dev/wp-json/acf/v3/options/theme-general-settings/field_name 
returns the field value

Do I miss anything?
Thank you

WP Version: 4.9.5
acf-to-rest-api version: 3.1.0
ACF Pro Version: 5.6.9

**Comment by evvvritt** [comment]
Hi @airesvsg , I'm also getting an empty array.

1. add_acf_options_page() with `post_id` set to "theme-general-settings"
2. "Show in REST API" set to `true`
3. GET request to `/wp-json/acf/v3/options/theme-general-settings` returns empty array
4. GET request to `.../{field_name}` returns empty array

[ACF Field JSON (Gist)](https://gist.github.com/evvvritt/e6a17783ac32eeef95a6b5016452639a)
WP Version: 4.9.8
acf-to-rest-api: 3.1.0
ACF Pro Version: 5.7.2

Any other insights? Thanks

**Comment by mattkaye** [comment]
> Hello @erwstout,
> 
> If you use that snippet:
> 
> ```
> acf_add_options_page();
> ```
> 
> The endpoint is:
> `http://mysite.dev/wp-json/acf/v3/options/options`
> 
> But if you register this way:
> 
> ```
> acf_add_options_page( array(
> 	'page_title' => 'Theme General Settings',
> 	'menu_title' => 'Theme Settings',
> 	'menu_slug'  => 'theme-general-settings',
> 	'capability' => 'edit_posts',
> 	'redirect'   => false,
> 	'post_id'    => 'theme-general-settings'
> ) );
> ```
> 
> Your endpoint is:
> `http://mysite.dev/wp-json/acf/v3/options/{post_id}`
> 
> ```
> acf_add_options_page( array(
> 	...
> 	'post_id' => 'theme-general-settings'
> 	...
> ) );
> ```
> 
> The result is:
> `http://mysite.dev/wp-json/acf/v3/options/theme-general-settings`
> 
> Thanks

This bit of documentation should be added to the README. It's not clear unless someone stumbles across this. Great plugin 👍

**Comment by bkrsmanovic** [comment]
Helpful tip who ever is stuck here. Save once Options page, otherwise you will always get empty array []. Just save it and you will see empty results with your fields.
