### ISSUE TITLE
Ready for Release?

### ISSUE THREAD

**Issue by drewcovi** [airesvsg/acf-to-rest-api#185]
Super glad I found your repo, but any chance of getting this pushed to the wordpress plugins? its stuck at 2.2.1

**Comment by airesvsg** [comment]
Hello @drewcovi,
Yes, it's ready. I'll release this week.
Thanks

**Comment by drewcovi** [comment]
hello @airesvsg!

Any reason the acf fields

**Comment by drewcovi** [comment]
Thanks!!

**Comment by airesvsg** [comment]
Done
