### ISSUE TITLE
url's don't include www

### ISSUE THREAD

**Issue by Laurensvdmaas** [airesvsg/acf-to-rest-api#189]
Hi,

My website can only run on www, and whenever you make a call to anything with acf fields, the url for images don't include www.

Is there a hook that i can use to fix this?

**Comment by airesvsg** [comment]
Hello @Laurensvdmaas,
The error isn't in my plugin, please open a new ticket here:
https://support.advancedcustomfields.com/new-ticket/

But you can use the filter `acf/rest_api/{type}/get_fields` to fix it.
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
  // your code here
  return $data;
} );
```

Thanks
