### ISSUE TITLE
Use rest_base for routes instead of post type name

### ISSUE THREAD

**Issue by LachlanArthur** [airesvsg/acf-to-rest-api#19]
If I create a post type like this:

    register_post_type('story', [
        ...
        'rest_base' => 'stories',
        ...
    ]);

Then the Wordpress API routes look like this: `/wp/v2/stories/:id`
But this plugin uses the post type name to make the routes, so they look like this: `/acf/v2/story/:id`

The ACF routes should use the `rest_base` of the post type to generate the routes. This also makes dealing with the attachment routes easier, because their `rest_base` is already set to `media` (see [class-acf-to-rest-api.php#L53](https://github.com/airesvsg/acf-to-rest-api/blob/master/class-acf-to-rest-api.php#L53))

**Comment by airesvsg** [comment]
Hi @LachlanArthur,
I'll fix soon.

Thanks
