### ISSUE TITLE
api v3 is returning empty array for acf options page

### ISSUE THREAD

**Issue by PMS72** [airesvsg/acf-to-rest-api#191]
### While v2 is returning all the data I need.

How come? And can I safely use version 2 for my project? Because I really need these ACF options pages. Am I doing something wrong, or is this a known issue?

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api/issues/184#issuecomment-338277335

**Comment by PMS72** [comment]
@airesvsg thank you very much
