### ISSUE TITLE
Not recognizing custom taxonomies

### ISSUE THREAD

**Issue by dambrogia** [airesvsg/acf-to-rest-api#197]
Awesome plugin, I've been using it on multiple projects for the last year or so - so first and foremost, thanks for your contributions to the community!

What I ran into today was not being able to return an endpoint for a custom taxonomy - more specifically a tag I've created for a custom post type:

    Post Type: Product (Woocommerce)
    Taxonomy: product_tag 

I have other custom post types that I've made for the site I'm creating, and those showed up correctly, so I'm not sure why the taxonomies are not showing up. 

I refreshed my rewrites endpoints inside WP Admin > Settings > Permalinks to ensure that everything was up to snuff. 

I went to the default endpoint of the API - `http://domain.dev` to return a list of available endpoints / options for the API. This response was missing anything related to the `product` and taxonomies related to it. 

For the mean time, I can use the `wp-ajax.php` route to work around this, but any info on why this happens or how this can be updated would be awesome.

`http://domain.dev/wp-json/acf/v3/product_tag/` response: 

    {
        "code": "rest_no_route",
        "message": "No route was found matching the URL and request method",
        "data": {
            "status": 404
        }
    }

From the `wp_term_taxonomy` table:

`http://domain.dev/wp-json/acf/v3/` response:

    {
        "namespace": "acf/v3",
        "routes": {
            "/acf/v3": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": {
                            "namespace": {
                                "required": false,
                                "default": "acf/v3"
                            },
                            "context": {
                                "required": false,
                                "default": "view"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3"
                }
            },
            "/acf/v3/posts/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/posts": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/posts"
                }
            },
            "/acf/v3/pages/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/pages": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/pages"
                }
            },
            "/acf/v3/media/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/media": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/media"
                }
            },
            "/acf/v3/humans/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/humans": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/humans"
                }
            },
            "/acf/v3/pups/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/pups": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/pups"
                }
            },
            "/acf/v3/product/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/product": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/product"
                }
            },
            "/acf/v3/categories/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/categories": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/categories"
                }
            },
            "/acf/v3/tags/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/tags": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/tags"
                }
            },
            "/acf/v3/comments/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/comments": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/comments"
                }
            },
            "/acf/v3/options/(?P<id>[\\w\\-\\_]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/users/(?P<id>[\\d]+)/?(?P<field>[\\w\\-\\_]+)?": {
                "namespace": "acf/v3",
                "methods": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    },
                    {
                        "methods": [
                            "POST",
                            "PUT",
                            "PATCH"
                        ],
                        "args": []
                    }
                ]
            },
            "/acf/v3/users": {
                "namespace": "acf/v3",
                "methods": [
                    "GET"
                ],
                "endpoints": [
                    {
                        "methods": [
                            "GET"
                        ],
                        "args": []
                    }
                ],
                "_links": {
                    "self": "http://domain.dev/wp-json/acf/v3/users"
                }
            }
        },
        "_links": {
            "up": [
                {
                    "href": "http://domain.dev/wp-json/"
                }
            ]
        }
    }

**Comment by airesvsg** [comment]
Hello @dambrogia,

Use *show_in_rest* parameter to expose your toxomomies.

Thanks

**Comment by dambrogia** [comment]
@airesvsg You were correct, sorry for the (extremely) delayed reply.

Thanks for the resolution!
