### ISSUE TITLE
Can't Update Options using v3

### ISSUE THREAD

**Issue by ghurson** [airesvsg/acf-to-rest-api#198]
wordpress version: 4.9.1, plugin version: 3.1.0

First off, huge fan of the plugin! Thanks so much for all you've done.

I've got an issue updating a global option. It's in an ACF options field group with the default 'option' id in the acf_add_options_page() settings, and I can "GET" the value just fine - I just can't "PUT" any data in. I always get the "Cannot update item" 500 error. I'm localizing my script, so I have a valid nonce. I can use the ajax calls to update ACF fields that aren't on standard post items, and I can update non-ACF content both using the same nonce. Also, when I change the nonce value in the below call, I get the "Invalid Nonce" error, so I don't think my issue is authentication, right?

My field "option_to_update" is a single textarea field, I want to update it to say "updated". Any ideas what might be causing this?

```JS
jQuery.ajax({
    url: wpApiSettings.root + 'acf/v3/options/options/option_to_update',
    method: 'POST',
    beforeSend: function (xhr) {
        xhr.setRequestHeader('X-WP-Nonce', wpApiSettings.nonce);
    },
    data: {
        "fields": {
            "option_to_update": "updated"
        }
    },
    dataType: 'json',
}).done(function (response, status) {
    console.log(response, status);
});
```

**Comment by Chris-AdHome** [comment]
I am also seeing this all PUT requests are failing, POST requests are working however...

**Comment by airesvsg** [comment]
Hello @ghurson,
Please, follow that issue:
https://github.com/airesvsg/acf-to-rest-api/issues/205

Thanks
