### ISSUE TITLE
Example to put the data

### ISSUE THREAD

**Issue by rizqinizamil** [airesvsg/acf-to-rest-api#2]
Hi @airesvsg,
Can you give me an example how to put/post data using the plugin. I want to using AJAX to post. I have an example code, but it didn't work. Maybe you can take a look.

```
$( '#post-submission-form' ).on( 'submit', function(e) {
        e.preventDefault();
        var title = $( '#post-submission-title' ).val(),
            content = $( '#post-submission-description' ).val(),
            username = $('#post-submission-username').val(),
            display_name = $('#post-submission-display_name').val(display_name),
            categories = $('#post-submission-category').val(),
            tags = $('#post-submission-tag').val(),
            featured_image = $('#post-submission-image').val(),
            copyright = $('#post-submission-copyright').val(),
            website = $('#post-submission-website').val(),
            status = 'publish';

        var data = {
            title: title,
            content: content,

           // ACF Fields:
            username: username,
            display_name: display_name,
            category: categories,
            tag: tags,
            featured_image: featured_image,
            copyright: copyright,
            website: website,
            status: status
        };

        $.ajax({
            method: "POST",
            url: POST_SUBMITTER.root + 'wp/v2/posts',
            data: data,
            beforeSend: function ( xhr ) {
                xhr.setRequestHeader( 'X-WP-Nonce', POST_SUBMITTER.nonce );
            },
            success : function( response ) {
                console.log( response );
                alert( POST_SUBMITTER.success );
            },
            fail : function( response ) {
                console.log( response );
                alert( POST_SUBMITTER.failure );
            }

        });

    });
```

**Comment by airesvsg** [comment]
Hi @rizqinizamil,

I did a simple theme, follows the link below:
[example.zip](https://github.com/airesvsg/acf-to-rest-api/files/82569/example.zip)

Your user has permission to edit?

You forgot the post ID.
```JS
$.ajax({
...
url: POST_SUBMITTER.root + 'wp/v2/posts', //POST_SUBMITTER.root + 'wp/v2/posts/1'
...
});
```

**Comment by rizqinizamil** [comment]
Wow.. thanks @airesvsg, will take a look.

**Comment by rizqinizamil** [comment]
Hi @airesvsg,

How can I get `postID` if I want to put a new post? Do I need to add `postID` parameter?
Sorry if it's a silly question.

Thanks again.

**Comment by airesvsg** [comment]
Hi @rizqinizamil,

I'll fix an error that found when creating a post. The plugin in this moment, only save the fields, when you create the post by admin.

**Comment by rizqinizamil** [comment]
Thanks @airesvsg. I'll be waiting for it.

**Comment by airesvsg** [comment]
I already have the solution, I will test more before updating the repository.

**Comment by airesvsg** [comment]
Hi @rizqinizamil,
Now you can test your first code to create a new post.

Thanks

**Comment by rizqinizamil** [comment]
Hi @airesvsg,

Does I still need `postID` to create post? If so, how can I get it for new post.
Sorry again for silly question.

**Comment by rizqinizamil** [comment]
When I use you example theme I got error `Illegal invocation`

**Comment by airesvsg** [comment]
Hi @rizqinizamil,

You don't need the `postID` to create post.
Look: [example.zip](https://github.com/airesvsg/acf-to-rest-api/files/90291/example.zip)

**Comment by airesvsg** [comment]
Hi @rizqinizamil,

See a more complete example:
https://github.com/airesvsg/acf-to-rest-api-example

Live:
http://airesgoncalves.com.br/acf-to-rest-api/

:+1:
