### ISSUE TITLE
Plugin don't retrieve all fields

### ISSUE THREAD

**Issue by bachilli** [airesvsg/acf-to-rest-api#20]
The plugin is not retrieving all fields, only relational/post object fields. Is that a problem?

Ex:

Text, URL and other simple fields don't get up;

**Comment by bachilli** [comment]
* In custom post types

**Comment by airesvsg** [comment]
Hi @bachilli,
what's the url?

Thanks

**Comment by bachilli** [comment]
Hi @airesvsg. The problem is with ACF Pro, not with your plugin.

Thanks!

Em seg, 14 de mar de 2016 às 15:48, Aires Gonçalves <
notifications@github.com> escreveu:

**Comment by airesvsg** [comment]
:smile: :+1:
