### ISSUE TITLE
Adding posts GUID

### ISSUE THREAD

**Issue by nikosolihin** [airesvsg/acf-to-rest-api#200]
How could I add each post's guid to the response? Currently wp-json/acf/v3/{post-type} returns an array of posts with the keys 'id' &'acf'. I'd like to also put 'guid' there.

I know I can modify the source 'class-acf-to-rest-api-controller.php' at line 95. But is there a cleaner "plugin-like" way to do this?

**Comment by airesvsg** [comment]
Hello @nikosolihin,
you can use the WordPress endpoints to receive the GUID.
```
wp-json/wp/v2/{post-type}
```
or the filter `acf/rest_api/{type}/get_fields`.
The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $request ) {
	if ( isset( $request['guid'] ) ) {
		$guid = $request['guid']['raw'];
	} elseif ( method_exists( $request, 'get_param' ) ) {
		$guid = get_the_guid( $request->get_param('id') );
	}

	$data['acf']['guid'] = $guid;


	return $data;
}, 10, 2 );
```

Thanks

**Comment by nikosolihin** [comment]
Thanks!
