### ISSUE TITLE
Add tag field to image ACF Gallery REST response

### ISSUE THREAD

**Issue by willybrauner** [airesvsg/acf-to-rest-api#202]
I'm trying to add a tag field  to image Gallery REST response. 
I Currently achieve to display tags from each image from ACF gallery with these multiple steps : 

- get all images from the gallery via REST API
- check there ID
- get all medias from WP via REST API
- check there ID
- compare IDs from images and medias, if it's match : 
- get all tags of this section of medias (custom field added to all medias)
- compare mediasTag iD with tagsId, if it's match : 
- I finally get the list of tagId I need for each image of the gallery...

I'm pretty sure there is a better way to achieve this.
 
Below an extract example of what I would like to receive from REST.

```
"acf": {
 "gallery": [
  {
    "id": 173,
    "title": "03",
    "filename": "03.jpg",
    "url": "http://localhost:8888/03.jpg",
    "alt": "",
    "author": "1",
    "description": "",
    tags : // HERE I WOULD LIKE TO DISPLAY TAGS SLUG ARRAY ABOUT EACH IMAGE LIKE 
    ...
```

Thanks for your advices !

**Comment by willybrauner** [comment]
Any suggestions ?

**Comment by airesvsg** [comment]
Hi @willybrauner,

please use the filter `acf/rest_api/{type}/get_fields`.

The wildcard **{type}** can be: post | user | comment | attachment | custom post type | taxonomy

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
  // your code here
  return $data;
} );
```

Thanks
