### ISSUE TITLE
Adding title to response data not working

### ISSUE THREAD

**Issue by arjendejong12** [airesvsg/acf-to-rest-api#203]
Hello,

I'm trying to add the post title to a custom post type's response $data, but it's not appearing. It only works when I add it to the $data['acf'] array.

```php
add_filter( 'acf/rest_api/locaties/get_fields', function( $data ) {
	$title = get_the_title( $data['id'] );
	$data['acf']['title'] = $title; // works
	$data['title'] = $title; // does not work
	return $data;
}, 10, 2 );
```

Is it possible to solve this? It's looks like the same thing you do [here](https://github.com/airesvsg/acf-to-rest-api/issues/41#issuecomment-222460783), but that is also not working.

**Comment by airesvsg** [comment]
Hello @arjendejong12 ,
Yes, any modifications should be happen, because this filter is only to modify act data.

Thanks
