### ISSUE TITLE
Are PUT HTTP Requests Working?

### ISSUE THREAD

**Issue by Chris-AdHome** [airesvsg/acf-to-rest-api#205]
Can you confirm that PUT HTTP requests are supported and working?

I am getting `{"code":"cant_update_item","message":"Cannot update item","data":{"status":500}}` on all my PUTs

The same code run through a POST works fine.

Please advise.

**Comment by airesvsg** [comment]
Hello @Chris-AdHome,

Yes, PUT HTTP requests works.

See in the link bellow the editable methods:
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L39

Thanks

**Comment by Chris-AdHome** [comment]
Using Basic Authentication:

[When I set my request to POST in Postman I am able to successfully update ACF fields.](http://mapleleaffs18.staging.wpengine.com/wp-content/uploads/2018/01/POST.png)

[When i set my request to PUT in Postman I am not able to successfully update ACF fields.
](http://mapleleaffs18.staging.wpengine.com/wp-content/uploads/2018/01/PUT.png)
I don't change any other setting, other than flipping the PUT to POST and vis-a-versa.

**Comment by airesvsg** [comment]
Ok, this problem isn't in my plugin.
I using the interface of WordPress classes to handle with it.

Please, open a new issue here:
https://wordpress.org/support/bb-login.php?redirect_to=https://core.trac.wordpress.org/newticket

Thanks

**Comment by Chris-AdHome** [comment]
Thanks Aires!

Where you able to replicate the issue with PUTs??

**Comment by Chris-AdHome** [comment]
[Working with the WordPress team to resolve this issue](https://wordpress.org/support/topic/class-wp-rest-server-php-put-failure/#post-9913657) - please feel free to contribute if you wish -
 thanks Aires!

**Comment by bondseid** [comment]
I am also having this issue. Please post an update if you find a solution! Thank you

**Comment by Chris-AdHome** [comment]
There is an easy solution... and I am being serious. Don't use PUT - this of course means you cannot use the [Node-WPAPI](http://wp-api.org/node-wpapi/) unfortunately... 

You could probably override the code in Node-WPAPI to force it (by hacking the code) to use a POST instead of PUT - I've seen a few people talking about that over in the WordPress.org support forums [using the WP  Backbone JS REST API library](https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/)

If you take that path, you then of course have to watch updating the library... find if you're a small shop, but not a good fix for bigger companies.

**Comment by Chris-AdHome** [comment]
Hi @airesvsg 

[WordPress has gotten back to me](https://wordpress.org/support/topic/class-wp-rest-server-php-put-failure/#post-9913657)

Any thoughts?

> I did a quick scan of class-wp-rest-server.php and did not see anything that would support PUT data transfer, it relies on getting data through $_POST. Admittedly, I may have missed something. I’m not that familiar with the API, my initial comment was based on general WP ?advice I’ve been operating under for years, that PUT should be avoided. It can sometimes work, but is unreliable and is best avoided. There’s no reason to expect that to continue into the API, but from your anecdotal experience, perhaps it should.

>Instead of searching for working examples of PUT use, I’d advise searching through the API source code for where PUT data would be handled. From that, if it exists, you could deduce the proper way to use it.

**Comment by airesvsg** [comment]
https://developer.wordpress.org/rest-api/extending-the-rest-api/routes-and-endpoints/#http-methods

**Comment by ziudeso** [comment]
With JWT I got it to work, just replace "acf" with "fields" in ur body, here's an example:
`localhost:7888/wp-json/sportspress/v2/events/26495`
`Authorization: Bearer XXXXX`
`Content-Type: application/json`
Body, instead of "acf" use "fields" key:
`
{
"fields": {
	"videos": "some video url"
}
}
`

**Comment by andercard** [comment]
This was opened more than a year ago and still does not work that bad :(
