### ISSUE TITLE
How to create pagination in this Posts API with acf-to-rest-api? 

### ISSUE THREAD

**Issue by fathan** [airesvsg/acf-to-rest-api#206]
How to create pagination in this Posts API with acf-to-rest-api?

**Comment by airesvsg** [comment]
Hi @fathan,
use the param `per_page`, see details here: https://developer.wordpress.org/rest-api/reference/posts/#arguments

http://localhost/wp-json/acf/v3/posts?per_page=2

Thanks

**Comment by fathan** [comment]
ok thanks @airesvsg for your solution.
