### ISSUE TITLE
rest api show password protected post

### ISSUE THREAD

**Issue by stephanedemotte** [airesvsg/acf-to-rest-api#207]
Hi, 

I can view post protected by password...

![screen shot 2018-02-02 at 10 32 57 am](https://user-images.githubusercontent.com/2158130/35740978-81ae0f8e-0804-11e8-8d61-7ed68387216e.png)

**Comment by airesvsg** [comment]
Hi @stephanedemotte,
You use something to authenticate?

At this time, you can use the filter `acf/rest_api/item_permissions/get`.

Thanks

**Comment by stephanedemotte** [comment]
Hummm... dont want to use auth plugin..

I talk about this type of protection, very simple >

![screen shot 2018-02-02 at 11 02 37 am](https://user-images.githubusercontent.com/2158130/35742546-c0861e8c-0808-11e8-9bf4-bb6c8c003870.png)

**Comment by stephanedemotte** [comment]
with `acf/rest_api/item_permissions/get` we can limit access to `/wp-json/acf/v3/posts/{id}` but the post is show in `/wp-json/acf/v3/{post-type}`

**Comment by airesvsg** [comment]
Yes, I understood your question. I asked you about authentication, because that protection maybe isn't necessary if you authenticate.

**Comment by stephanedemotte** [comment]
no auth require :)
we juste want to hide some post, but we want yo share it with "some" people

**Comment by airesvsg** [comment]
Yes, auth not required, but the WordPress endpoint just hide the content.

Please, try the snippet bellow.

The wildcard `{type}` can be: `post | page | custom post type`

```
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $request ){
	if ( isset( $request['id'] ) && post_password_required( $request['id'] ) ) {
		$password = isset( $_GET['password'] ) && ! empty( $_GET['password'] ) ? wp_unslash( $_GET['password'] ) : NULL;
		if ( $password !== get_post_field( 'post_password', $request['id'] ) ) {
			$data['acf'] = array();
		}
	}
	return $data;
}, 10, 2 );
```

Thanks

**Comment by stephanedemotte** [comment]
you are a killer.

Thanks man !

**Comment by airesvsg** [comment]
: )
