### ISSUE TITLE
Update User Field with JWT Auth

### ISSUE THREAD

**Issue by jigsawsoul** [airesvsg/acf-to-rest-api#208]
Hi,

I am trying to update a users custom field although I am going a 401 response, I am using JWT tokens for auth. If this plugin tested and working with JWT?

Many thanks.

**Comment by danilopaulinodasilva** [comment]
Did you see [this](https://github.com/airesvsg/acf-to-rest-api-example/issues/1)?

**Comment by sorensenjg** [comment]
I'm currently able to update the user fields through JWT auth but can't seem to update ACF custom fields. Does anyone have a solution to this?

{
      first_name: 'Justin', <-- this will update
      acf: {
        phone: '4088923955', <-- this will not update
        notifications: [] <-- this will not update
      }
}

Tried:
- POST and PUT
- Setting the location to "current user" is "logged in"
- Different content-types

Using:
- Advanced Custom Fields PRO v5.7.6
- ACF to REST API v3.1.0
- JWT Authentication for WP-API v1.2.4

**Comment by Twansparant** [comment]
Same here... Was there a fix?
