### ISSUE TITLE
Get specific data only with endpoints

### ISSUE THREAD

**Issue by mvnguyen83** [airesvsg/acf-to-rest-api#21]
Hi, 
I've a question if it's possible to get specific data within the api of a page or post using endpoints? Like I have a page: http://mvnguyen.com/wp-json/acf/v2/page/4/ and all I want is the social_links repeater by just add on the field name like so: http://mvnguyen.com/wp-json/acf/v2/page/4/social_links. Or it's already there but I don't how to do it. 
Thanks

**Comment by airesvsg** [comment]
Hi @mvnguyen83,
This feature is only available in **options** endpoint, maybe I'll implement it.

Thanks

**Comment by mvnguyen83** [comment]
That'll be awesome!
Thanks @airesvsg and keep me updated if you do.

**Comment by airesvsg** [comment]
OK, I'll let you know.  :+1:

**Comment by airesvsg** [comment]
Hi @mvnguyen83,
Please, update your plugin.
Thanks

**Comment by mvnguyen83** [comment]
Great! You're the man @airesvsg! Thanks
