### ISSUE TITLE
Get post by date like orderby in Wp-rest-api 

### ISSUE THREAD

**Issue by MaloRchrd** [airesvsg/acf-to-rest-api#210]
All is in the title. 
I'm using ACF to rest for the first time for an event based wordpress app. 
It works great thanks but the thing is I can't filter the post by date. 
Is there any trick on how to do it ?

**Comment by MaloRchrd** [comment]
Sorry my mistake just found the way

**Comment by betoflakes** [comment]
How?

**Comment by airesvsg** [comment]
Hi @betoflakes,

You can use the WordPress REST API arguments.

https://developer.wordpress.org/rest-api/reference/posts/#arguments

Thnaks
