### ISSUE TITLE
ACF fields for taxonomy Tags

### ISSUE THREAD

**Issue by carned** [airesvsg/acf-to-rest-api#212]
Hi,
I added an "image" field to Tag and Categories using Advanced Custom Fields.

When I go to .../wp-json/acf/v3/ I see just [].

For taxonomy categories it works!

Thanks a lot

**Comment by carned** [comment]
Sorry, the problems is only on Tag taxonomy. For categories it works fine.

**Comment by airesvsg** [comment]
Hi @carned,

Yes, because you need to specify what do you want to list.

Please, look this snippet and the endpoints:

```PHP
add_action( 'init', function() {

	register_post_type( 'book', array(
		'public'       => true,
		'label'        => __( 'Books' ),
		
		// rest api parameters
		'show_in_rest' => true,
		'rest_base'    => 'books',
	) );

	register_taxonomy( 'genre', 'book', array(
		'label'        => __( 'Genre' ),
		'rewrite'      => array( 'slug' => 'genre' ),
		'hierarchical' => true,

		// rest api parameters
		'show_in_rest' => true,
		'rest_base'    => 'genres'
	) );

} );
```

Book endpoint:
http://localhost/wp-json/acf/v3/books

Genre endpoint:
http://localhost/wp-json/acf/v3/genres

Thanks
