### ISSUE TITLE
POST to type "Gallery" field

### ISSUE THREAD

**Issue by marshalloram** [airesvsg/acf-to-rest-api#213]
I can't find any documentation, issues or information on how to update a Gallery filed. I can POST or PUT to /acf/v3/posts/{id}/{gallery_field} however whatever json I send it's way just erases the array of images. just sending an array of objects with the uri's doesn't work, sending base/64 coded uri's doesn't work.

- Is this supported?
- If so, what shape does the json object/array need to be in. e.g. what are the critical fields?

**Comment by airesvsg** [comment]
Hello @marshalloram,

You need to send the ID of attachment:
![gallery-01](https://user-images.githubusercontent.com/396668/36566623-cd9f2488-1802-11e8-9331-3de5dfdc400a.png)

First, I updated the field with the attachment 15:
![gallery-02](https://user-images.githubusercontent.com/396668/36566671-e90aedce-1802-11e8-985d-2907e99ff6f7.png)

After, I updated the field with the attachment 19:
![gallery-03](https://user-images.githubusercontent.com/396668/36566674-ec095c0e-1802-11e8-8a76-993ac40c0759.png)

Thanks

**Comment by marshalloram** [comment]
Awesome thank you for the quick response! Yeah I worked out how to create the media item (mostly) first, then I wasn't sure what I needed to send into the gallery field. So POST appends them to existing images, PUT replaces the entire gallery?

**Comment by Chris-AdHome** [comment]
Let me know if you are able to PUT to successfully update your content, I didn't have any luck using ACF to REST API with PUT requests.

**Comment by marshalloram** [comment]
Cool. Yeah I can successfully POST or PUT both doing the same thing and replacing the entire gallery images with the newly supplied array of IDs.

**Comment by marshalloram** [comment]
I'm using JWT auth, don't think that changes anything though.

**Comment by Chris-AdHome** [comment]
JWT Auth shouldn't change anything.

Are you using Curl or WGET commands? A third party library? or Postman to run your REST PUT's and POST's requests?

**Comment by marshalloram** [comment]
I'm using Postman to the run the PUTs and POSTs.

Thank you so much for this awesome plugin, it's a massive time saver!

**Comment by Chris-AdHome** [comment]
I'm not the authour, I'm just another web developer who ran into some issues with this plugin -specifically using PUT requests.

Let me know if you try using PUT request outside of Postman, and if they work. Much appreciated!

**Comment by marshalloram** [comment]
Cool, well thank you for the help @Chris-AdHome it much appreciated and now nice documented here. Cheers, I'll keep you POSTed.

**Comment by airesvsg** [comment]
@Chris-AdHome Please, see in the [link](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L39) below all editable methods:

```PHP
...
const EDITABLE = 'POST, PUT, PATCH';
...
```
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L39

In the same [class](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L313), we have this comment:

```PHP
/*
 * HTTP method override for clients that can't use PUT/PATCH/DELETE. First, we check
 * $_GET['_method']. If that is not set, we check for the HTTP_X_HTTP_METHOD_OVERRIDE
 * header.
 */
``` 

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L313

Thanks

**Comment by airesvsg** [comment]
@Chris-AdHome  Please, watch this video:
[![issue 213](http://i3.ytimg.com/vi/vD8thj2fPLY/maxresdefault.jpg)](https://youtu.be/vD8thj2fPLY)

Thanks

**Comment by Chris-AdHome** [comment]
Thank you for doing that!

Obviously there is something on my end of things and this has confirmed it.
