### ISSUE TITLE
acf/rest_api/options/get_fields filters

### ISSUE THREAD

**Issue by stephanedemotte** [airesvsg/acf-to-rest-api#214]
Hi, how can we filters options pages ?

I've try with `acf/rest_api/options/get_fields` with no success.

Can we do that ?
Thanks !

**Comment by airesvsg** [comment]
Hi @stephanedemotte,

Using the wildcard in the singular, like:

```PHP
add_filter( 'acf/rest_api/option/get_fields', function( $data ) {
...
} );
```

For more details, please read this comment: https://github.com/airesvsg/acf-to-rest-api/issues/184#issuecomment-338277335

Thanks
