### ISSUE TITLE
Post objects do not run content through wpautop

### ISSUE THREAD

**Issue by trattles** [airesvsg/acf-to-rest-api#215]
**Symptom**

When adding an ACF field of type "Post Object', the return data for this does not run WYSIWYG fields through wpautop. This means that default WYSIWYG fields such as "content" do not get <p> tags added to them.

**To Reproduce**

Add a Post Object field to any post. Make sure the post object you add has the default content box. Enter some text, hit return, enter more text. (this would return <p> tags around each return you just hit normally).

Attach the post object to the "post object" acf field you added.

Hit this post in the rest API.

You'll see your post object field inside the ACF property, but the "post_content" field will not have been run through wpautop. I believe the normal rest API returns a "rendered" prop underneath things like content for this reason.

**Comment by airesvsg** [comment]
Hi @trattles,

Use the filter `acf/rest_api/{type}/get_fields`, see below:

The wildcard **{type}** can be: post | page | custom post type | tax

**my_field** = field name for your post object.

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $response ) {
	if ( isset( $data['acf']['my_field'] ) ) {
		$data['acf']['my_field']->post_content = wpautop( $data['acf']['my_field']->post_content );
	}

	return $data;
}, 10, 2 );
```

Thanks
