### ISSUE TITLE
add custom filter - acf/v3

### ISSUE THREAD

**Issue by yooniks9** [airesvsg/acf-to-rest-api#218]
Hello there

How do I add filter on this endpoint?

endpoint = /wp-json/acf/v3/options/global-settings

I need to do str_replace for the json

Please help, Thank you

**Comment by airesvsg** [comment]
Hello @yooniks9,

please read it: https://github.com/airesvsg/acf-to-rest-api/issues/214#issuecomment-368074454

Thanks
