### ISSUE TITLE
Getting only acf key in wp-json

### ISSUE THREAD

**Issue by leo9618** [airesvsg/acf-to-rest-api#219]
Previously, I had seen that wp-json return me a key acf in that key , i used to get the acf custom fields inside the key, but now its not showing me nothing. 

Please help me in this case

Now its showing

![screenshot from 2018-03-13 13-13-53](https://user-images.githubusercontent.com/37325277/37386019-980e477a-277c-11e8-9b19-5dd34f139728.png)

I had tried using this but still its showing the same result

$types = ['post', 'page', 'product'];

foreach ($types as $type) {
  add_filter( 'acf/rest_api/'.$type.'/get_fields', function( $data, $response ) use ($types) {

    if ( $response instanceof WP_REST_Response ) {
      $data = $response->get_data();
    }

    array_walk_recursive( $data, 'deepIncludeACFFields', $types );

    return $data;

  }, 10, 3 );
}

function deepIncludeACFFields( &$item, $key, $postTypes ) {
  if ( isset( $item->post_type ) && in_array( $item->post_type, $postTypes ) ) {
    $item->acf = get_fields( $item->ID );
  }
}

**Comment by airesvsg** [comment]
Hi @leo9618,
use `show_in_rest` to expose the ACF fields for your custom post type.

```php
add_action( 'init', function() {
	$args = array(
		'public'       => true,
		'label'        => 'Books',
		'show_in_rest' => true,
	);
	register_post_type( 'book', $args );
} );
```

Thanks

**Comment by leo9618** [comment]
I had tried it , still no effect 
Here is my code in function.php

  add_action( 'init', function() {
	$args = array(
		'public'       => true,
		'label'        => 'movie',
		'show_in_rest' => true,
	);
	register_post_type( 'movie', $args );
} );

and also tried it from cpt ui 

![screenshot from 2018-03-15 11-42-13](https://user-images.githubusercontent.com/37325277/37447099-7a61867c-2846-11e8-8ac0-01a36de9cbef.png)
