### ISSUE TITLE
Filtering with filters

### ISSUE THREAD

**Issue by fcordillot** [airesvsg/acf-to-rest-api#222]
Hi! 👋

I have a question about filters.

I have 3 post_types:
- Chapters
- Categories
- Stories

When I retrieve a Category, I get:
```
{
    "id": 73,
    "acf": {
        ...
        "chapter_id": 58,
        // Got with get_fields()
        "chapter": {
            "description": "Chapter 01 - Description",
            "title": "Chapter 01"
        },
        ...
    }
}
```

When I retrieve a Story, I get:
```
{
    "id": 190,
    "acf": {
        ...
        "category_id": 58,
        // Got with get_fields()
        "category": {
            "description": "Category 03 - Description",
            "title": "Category 03",
            "chapter_id": 62
        },
        ...
    }
}
```

I can filter stories by `category_id` with `/stories?category_id={id}` (it's an ACF field) but, I can't filter stories by `chapter_id` (not an ACF field, only got by `get_fields()`). Any idea?

**Comment by airesvsg** [comment]
Hi @fcordillot,

Please, read it: https://github.com/airesvsg/acf-to-rest-api/issues/13#issuecomment-189403357

Thanks

**Comment by fcordillot** [comment]
That doesn't answer my question...

My Stories Post Type only has an ACF fields called `category_id`
My Categories Post Type only has an ACF fields called `chapter_id`

Steps:
1. Via filter, I retrieve the Category related to my Story.
2. When I got the Category, I retrieve the Chapter related to the Category of my Story.
3. I put my Category and my Chapter into the `acf` Object.

How can I filter my stories by the `chapter_id` only retrieved via a filter (not related to a Story but only on Category)
