### ISSUE TITLE
Add featured image URL and post slug to acf post object

### ISSUE THREAD

**Issue by hartey11** [airesvsg/acf-to-rest-api#226]
Hi,

How do you add additional fields to a post object within an acf field. I'm trying to add the featured image url so we don't have to make a second request to get it and I'd also like to include the slug if possible?

thanks in advance!

**Comment by airesvsg** [comment]
Hi @hartey11,

Use the filter `acf/rest_api/{type}/get_fields`, see below:

The wildcard **{type}** can be: post | page | custom post type | tax

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
  // Your code here

  return $data;
}, 10 );
```

Thanks
