### ISSUE TITLE
How to get post id on 'acf/rest_api/{type}/get_fields' filter

### ISSUE THREAD

**Issue by diegoprates** [airesvsg/acf-to-rest-api#227]
How can I get the current post id of the post being filtered for this function?

```
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    $data['acf']['testing_id'] = "Get post id here...";
    return $data;
}, 10, 2 );
```

In the response I can see that `$data['id']` exists but I can't use it.

**Comment by diegoprates** [comment]
Just found it

```
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $obj ) {
    $data['acf']['testing_id'] = $obj['id'];
    return $data;
}, 10, 2 );
```

**Comment by airesvsg** [comment]
```
add_filter( 'acf/rest_api/{type}/get_fields', function( $data, $request ) {
	$id = $request->get_param( 'id' );
	
	return $data;
}, 10, 2 );
```

**Comment by diegoprates** [comment]
Yes, but this assumes that you have ID on request like `wp-json/acf/v3/{type}/7`

**Comment by airesvsg** [comment]
You argument `$obj` is `WP_REST_Request`.

Please, read about ArrayAccess:
http://php.net/manual/en/class.arrayaccess.php

https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/rest-api/class-wp-rest-request.php#L29

Thanks
