### ISSUE TITLE
How can I suppress a field in the response 

### ISSUE THREAD

**Issue by jeffersonrbr** [airesvsg/acf-to-rest-api#228]
I'm trying to suppress (hide) a field in the request of all items and not show in response. If I send the parameter slug[] I'm want to show it, for example
**acf/v3/{post_type}?slug[]=SOME_SLUG**
here I want to show the custom field "content"

**acf/v3/{post_type}**
here i want to suppress the field "content"

**Comment by airesvsg** [comment]
Hi @jeffersonrbr,

Use the filter `acf/rest_api/{type}/get_fields`, see below:

The wildcard **{type}** can be: post | page | custom post type | tax

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
	if ( ! isset( $_GET['slug'] ) || empty( $_GET['slug'] ) ) {
		unset( $data['acf']['content'] );
	}

	return $data;
} );
```
Thanks
