### ISSUE TITLE
When ACF is bundled in my theme (not installed as a plugin) the `acf` object it not added to REST API

### ISSUE THREAD

**Issue by wondergryphon** [airesvsg/acf-to-rest-api#234]
ACF Pro is able to be bundled into custom themes. This process is detailed here: https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/

When using this method (instead of installing the ACF plugin), the `acf` data object is not included in my site's JSON data. 

Can you clarify how to fix this?

Thank you!

**Comment by airesvsg** [comment]
Hi @wondergryphon,
Please, read it: https://github.com/airesvsg/acf-to-rest-api/issues/229
Thanks

**Comment by wondergryphon** [comment]
Thank you for the quick reply @airesvsg :) 

Would be great if this was part of FAQ / readme file.

Much appreciated.
