### ISSUE TITLE
filter post by acf field 

### ISSUE THREAD

**Issue by kaito-kaito** [airesvsg/acf-to-rest-api#24]
Hi everyone. 
How are you? Hope you are doing well. 
I have A question about filtering  in ACF to REST API plugin. 
Can I filter posts by custom field of an array? 
See this please: http://i.imgur.com/u2eQydP.png
I want to filter posts that has specific id in anime-related field. 
Hope you understand me. 
Thank you for your time.

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
It's possible, but it will be very expensive to process.
Thanks

**Comment by kaito-kaito** [comment]
What do you mean by "expensive to process"?

**Comment by airesvsg** [comment]
For each post:
1. get the field "anime-related";
2. deserialize the field data;
3. compare;
4. add filtered data in another array.
