### ISSUE TITLE
Updating a file field type

### ISSUE THREAD

**Issue by yannandco** [airesvsg/acf-to-rest-api#240]
Hello,
i'm trying to update a file field.
Request is a POST to
`https://amisosr.yannandco.com/wp-json/acf/v3/facture/90/`
- Facture is a custom type
- 90 is the ID

JSON sent is:
`{
	"acf":{
		"facture":306
	}
}`
- 306 is the id of the media already uploaded
- "facture" is the name of the file field

Result is 
`{
    "code": "cant_update_item",
    "message": "Cannot update item",
    "data": {
        "status": 500
    }
}`

Did i do something wrong? Can you help me?
Thank you in advance

**Comment by jimlundblad** [comment]
Solved:

post to the related post or page, by using fields: ´{ 'key' : 'value' }´ not ´acf :{...}´
