### ISSUE TITLE
Replace dash in the field name

### ISSUE THREAD

**Issue by kaito-kaito** [airesvsg/acf-to-rest-api#25]
Hi there. 
How can I replace dash in the field name? I mean is there any filter to use this php function str_replace("-", "_", $field)? 
So, If I have a field called (my-category).. I want it to be my_category when it is displayed in API

**Comment by airesvsg** [comment]
Hi @kaito-kaito,

Follow the code below.

You must replace **{type}** by: post, page, user, term, comment, media, options or custom post type.
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
	if ( isset( $data['acf'] ) && ! empty( $data['acf'] ) ) {
		foreach( $data['acf'] as $k => $v ) {
			if ( strpos( $k, '-' ) !== false ) {
				unset( $data['acf'][$k] );
				$k = str_replace( '-', '_', $k );
				$data['acf'][$k] = $v;
			}
		}
	}
	
	return $data;
} );
```

If I want to replace in my Custom Post Type ( **book** ).
```PHP
add_filter( 'acf/rest_api/book/get_fields', function( $data ) {
...
} );
```

Thanks

**Comment by kaito-kaito** [comment]
Thank you for helps but it gave me 500 error when I access to the given post type

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
Your PHP version supports anonymous functions?
If not support, please use the code below.

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', 'acf_rest_api_replace_keys' );
function acf_rest_api_replace_keys( $data ) {
if ( isset( $data['acf'] ) && ! empty( $data['acf'] ) ) {
        foreach( $data['acf'] as $k => $v ) {
            if ( strpos( $k, '-' ) !== false ) {
                unset( $data['acf'][$k] );
                $k = str_replace( '-', '_', $k );
                $data['acf'][$k] = $v;
            }
        }
    }

    return $data;
}
```

Thanks

**Comment by kaito-kaito** [comment]
Still the same :(

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
what file you pasted the code?

please, send me this file.
airesvsg@gmail.com

Thanks

**Comment by kaito-kaito** [comment]
in** function.php** of my theme.

**Comment by kaito-kaito** [comment]
Fatal error: Cannot use object of type WP_REST_Response as array in functions.php on line 391

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
in my environment I received the variable $data as array.
in the below code I converted object to array.
```PHP
add_filter( 'acf/rest_api/book/get_fields', function( $data ) {
	$data = (array) $data; // casting object to array
	if ( isset( $data['acf'] ) && ! empty( $data['acf'] ) ) {
		foreach( $data['acf'] as $k => $v ) {
			if ( strpos( $k, '-' ) !== false ) {
				unset( $data['acf'][$k] );
				$k = str_replace( '-', '_', $k );
				$data['acf'][$k] = $v;
			}
		}
	}
	
	return $data;
} );
```

Thanks

**Comment by kaito-kaito** [comment]
It works now but there is another issue. 
It works only when using wp-json/acf/v2/{type}/post_id
But when I visit the normal URL for WP-REST-API Nothing change
Also there is an extra fields appear when using this filter.

I apologise for the inconvenience.
Thank you for your time.

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
please, use the below code:

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
	if ( method_exists( $data, 'get_data' ) ) {
		$data = $data->get_data();
	} else {
		$data = (array) $data;
	}
	
	if ( isset( $data['acf'] ) && ! empty( $data['acf'] ) ) {
		foreach( $data['acf'] as $k => $v ) {
			if ( strpos( $k, '-' ) !== false ) {
				unset( $data['acf'][$k] );
				$k = str_replace( '-', '_', $k );
				$data['acf'][$k] = $v;
			}
		}
	}

	return $data;
} );
```
Thanks

**Comment by kaito-kaito** [comment]
Finally it works :dancer: 
Thank you so much for helping me. 
Thank you for your time. 

Best regards

**Comment by airesvsg** [comment]
:smiley: :+1:

**Comment by kaito-kaito** [comment]
Hi. 
Sorry for disturbing you.
I have another question please. I'm working with relationship field in ACF as object. Is there any way to display the taxonomy term ID that is attached to that post. Because in API it displays the title, date, and so on. 
Hope you understand me. 
Thank you.

**Comment by airesvsg** [comment]
Hi @kaito-kaito,
Please, open a new issue, because if other people have the same problems, will be easier to find the solution.

Thanks
