### ISSUE TITLE
[QUESTION] Modify images urls

### ISSUE THREAD

**Issue by LucasKovacs** [airesvsg/acf-to-rest-api#256]
How can I modify the images URLs:

On the JSON response I have something like this:

"acf": {
    "hero_image": "http://localhost:8080/wp-content/uploads/2018/02/overview.jpg"
}

I'd like to get an url like this:

"acf": {
    "hero_image": "/wp-content/uploads/2018/02/overview.jpg"
}

How can I achieve this?

Thanks!

**Comment by LucasKovacs** [comment]
@airesvsg any help, please?

**Comment by LucasKovacs** [comment]
Never mind...

Just if anyone is interested:

`
function remove_base_url($data) {

    $protocol = 'http';
    
    if ($_SERVER['HTTPS'] == 'on') {
        
        $protocol = 'https';
    }
    
    $port = getenv('CGB_WEBSITE_BACKEND_PORT') ?? null;
    $server_port = '';
    
    if (!is_null($port)) {
        
        $server_port = ':' . $port;
    }
    
    $base_url = $protocol . '://' . getenv('SERVER_NAME') . $server_port;
    
    return strtr($data, [$base_url => '']);
}

add_filter( 'wp_get_attachment_url', 'remove_base_url' );
`

**Comment by airesvsg** [comment]
Hi @LucasKovacs,

You can use the command **search-replace** of WP-CLI, for more details, please read the link below.

https://developer.wordpress.org/cli/commands/search-replace/

Thanks
