### ISSUE TITLE
Get categories ACF

### ISSUE THREAD

**Issue by jrleonr** [airesvsg/acf-to-rest-api#27]
Hi there,

I'm trying to get ACF for the taxonomies. But I can't figure out how.

I've tried /wp-json/acf/v2/term/category/10, did not work. Also tried with the slug /category/{slug} and I'm getting an 301.

Any suggestions, please?

Thanks for the amazing work.

**Comment by airesvsg** [comment]
Hi @jrleonr,
Please, update your plugin.
Thanks
