### ISSUE TITLE
Cannot update WP post post_title field from /wp-json/acf/v3/ endpoint.

### ISSUE THREAD

**Issue by ztraboo** [airesvsg/acf-to-rest-api#273]
I’m currently using custom post types. Is there a clear way to update the WordPress post post_title field when making a HTTP POST request to /wp-json/acf/v3/{custom_post_type}/{id} endpoint? Do I have to rather submit to the /wp-json/wp/v2/{custom_post_type}/{id} endpoint to make the post_title field update occur? It would be nice to have one POST call if possible. Currently I’m updating other ACF fields with this POST call using the ACF endpoint.

**Comment by airesvsg** [comment]
Hi @ztraboo,

Please, use that endpoint to update the title:
`/wp-json/wp/v2/{custom_post_type}/{id}`

You need to autheticate to do it.
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Thanks

**Comment by ztraboo** [comment]
Thanks @airesvsg. I’ll do that. Do you know if acf fields can also be update from that endpoint?

**Comment by airesvsg** [comment]
Yes, you can!

**Comment by ztraboo** [comment]
Do you have an example of this update? I looked at the acf rest todo example and it was pointing to the wp endpoint. Guess that’s a good example. Please advise.

**Comment by ztraboo** [comment]
If we can use the wp endpoint then why should we install this plugin?

**Comment by ztraboo** [comment]
Thanks for your recommendation @airesvsg. Using `/wp-json/wp/v2/{custom_post_type}/{id}` allowed me to update the _post_title_ and _acf_ fields.

I was able to successfully use this JWT plugin (https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) and update the custom acf fields using the _"fields"_ value.

Located the JWT token by issuing
http://ew-localhost.com/wp-json/jwt-auth/v1/token
POST
content-type: application/json; charset=UTF-8
Pass in _"username"_ _"password"_ of Wordpress user to authenticate and receive Bearer token.

Defined a custom post type called _courses_ using this plugin (https://wordpress.org/plugins/custom-post-type-ui/) and allow REST API access.

Example call to update the custom post type _course_, post id = 91
http://localhost/wp-json/wp/v2/course/91
POST
content-type: application/json; charset=UTF-8
authorization: Bearer _JWT token goes here_

```
{
    "title": "This is a test title",
    "fields": {
      "course_short_description": "Example short description",
      "content_overview": "Sample content overview",
      "open_edx_meta": {
        "modified_by": [
          3
        ],
        "date_modified": "2018-10-12 23:10:26.139728"
      }
    }
}
```
