### ISSUE TITLE
Options page + Polylang

### ISSUE THREAD

**Issue by oguilleux** [airesvsg/acf-to-rest-api#274]
Hi there,

Thanks a lot for this awesome plugin it really saved my day !

I'm having trouble retrieving data from an option panel. It work but it's only retrieving the main language. When I try to pass <code>?lang=fr</code> in the url it still doesn't change the ouput.

My url looks like this : <code>mysite.com/wp-json/acf/v3/options/my-options?lang=en</code>

I'm using [Polylang Pro](https://polylang.pro/doc/rest-api/) with REST API support + [ACF Options for Polylang](https://github.com/BeAPI/acf-options-for-polylang) to translate the option panel.

Where can I filter content returned with language please ?

Thank you for your help,

Olivier

**Comment by leonardo-koslowski** [comment]
How did you solve this issue?

**Comment by leok85** [comment]
How did you solve this issue?

**Comment by oguilleux** [comment]
I can't remember, it was a long time ago.

Normally you don't this plugin anymore : https://www.advancedcustomfields.com/resources/wp-rest-api-integration/

**Comment by leok85** [comment]
Thanks, but this integration doesn't include options page in rest api :(
