### ISSUE TITLE
Hiding options page from the rest api

### ISSUE THREAD

**Issue by TylerBarnes** [airesvsg/acf-to-rest-api#278]
Hi, awesome plugin!

Is it possible to prevent access to a specific options page?
I want to store an API key there but I don't want it to be publicly available.

My field is registered via php and I've added this to the field.

```php
			'show_in_rest' => 0,
			'edit_in_rest' => 0,
```
It still shows up in the rest api though.

I figure I need to use a permissions filter

```php
add_filter( 'acf/rest_api/item_permissions/get', function( $permission ) {
  return current_user_can( 'edit_posts' );
} );
```

But I'm not sure how this filter can be used to disable getting a specific field.

Is there a way for me to prevent api access to a specific options page or field?

**Comment by stephanedemotte** [comment]
Same here `'acf/rest_api/item_permissions/get'` don't work anymore

**Comment by robertark** [comment]
To hide the options output, use this filter and return false like so:

`add_filter( 'acf/rest_api/option/get_fields', '__return_false');`
