### ISSUE TITLE
Trying to PUT or PATCH an ACF Repeater Field through REST API

### ISSUE THREAD

**Issue by tankbar** [airesvsg/acf-to-rest-api#28]
Hi!

Any experience with this or tips? We get an error when trying to do this and all the other ID's in the repeater array gets deleted.

In this example we wan't to PATCH an image field in a ACF repeater through the API.

**Comment by airesvsg** [comment]
Hi @tankbar,
Have you checked how I did in the example theme?
https://github.com/airesvsg/acf-to-rest-api-example

Below we have a table with what each method does.

| Method | Action |
|-----------|-----|
| POST | Create |
| GET | Retrieve |
| PUT | Update |
| DELETE | Delete | 

Thanks

**Comment by roladn** [comment]
can you please help with an php example of a POST or PUT  request . 
I'm doing the GET  request like 
`$site = Sites::findOrFail($id);
        $token=$this->token($site->url,$site->clientId,$site->clientSecret);
        $token=$token->getToken();
            $options  = array (
                  'http' => 
                      array (
                        'ignore_errors' => true,
                        'method' => 'GET',
                         ),
                    );
            $context  = stream_context_create( $options );
            $response = file_get_contents(
                $site->url.'/wp-json/acf/v2/options?access_token='.$token,
                false,
                $context
            );
            $articles = json_decode($response);
            echo "<pre>";
            print_r($articles);
            echo "</pre>";`
i'm having some problems to  update any of the options field .
Thanks for your great plugin .

**Comment by airesvsg** [comment]
Hi @roladn,
please, read the documentation about authentication
http://v2.wp-api.org/guide/authentication/
Thanks
