### ISSUE TITLE
How to post article with custom field use api

### ISSUE THREAD

**Issue by 631068264** [airesvsg/acf-to-rest-api#282]
I use `/wp-json/acf/v3/posts` to post an article . 
Get an error 
```
No matching URLs were found and route to request method
```

 I can use the same parameter with `/wp-json/wp/v2/posts` to post an article successfully.

After I post article with official api and then use  **acf api** to update it also failed 
```
{'code': 'cant_update_item', 'message': 'Cannot update item', 'data': {'status': 500}}
```

acf-to-rest-api can be used?

**Comment by airesvsg** [comment]
Hi @631068264,

Please, read the links below.
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
https://github.com/airesvsg/acf-to-rest-api#request-api-version

Thanks
