### ISSUE TITLE
Possible to group ACF output by ACF field group

### ISSUE THREAD

**Issue by mcrider** [airesvsg/acf-to-rest-api#29]
Is it possible to group fields in a post's JSON by the ACF field group? When I request my post's JSON through wp-api i get a flat list of fields underneath `acf`. I need something grouped so i can determine what module to display in my front-end but also there is a practical concern of fields from different field groups with the same name overriding each other in the output.

**Comment by airesvsg** [comment]
Hi @mcrider,
you can use the filter: **acf/rest_api/_{type}_/get_fields**

```php
add_filter( 'acf/rest_api/post/get_fields', function( $data ) {
	if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

	if ( isset( $data['acf'] ) && ! empty( $data['acf'] ) ) {
		$acf    = $data['acf'];
		$groups = array();

		$groups['group_1'] = array(
			'field_1' => $acf['field_1'],
			'field_2' => $acf['field_2'],
		);

		$groups['group_2'] = array(
			'field_1' => $acf['field_3'],
			'field_2' => $acf['field_4'],
		);

		$data['acf'] = $groups;
	}

	return $data;
});
```

Thanks

**Comment by mcrider** [comment]
Thanks for the assist :)
