### ISSUE TITLE
Filtering custom taxonomy by acf field value

### ISSUE THREAD

**Issue by geochanto** [airesvsg/acf-to-rest-api#299]
I have a custom taxonomy named `collection` with acf fields. If I go to my `https://example.dev/wp-json/wp/v2/collection`, I can see all the data with all acf fields included. I'm trying to set up a filter so that I can filter by acf field value by hitting`https://example.dev/wp-json/wp/v2/collection?featured=yes`

I previously did this for a custom post type, as described here: https://github.com/airesvsg/acf-to-rest-api/issues/123, and it worked.

**BUT**, it does not look like it's working for taxonomies. This does not work:
```
add_filter( 'rest_collection_query', function( $args ) {

    $ignore = array('featured');
  
    foreach ( $_GET as $key => $value ) {
      if (!in_array($key, $ignore)) {
        $args['meta_query'][] = array(
          'key'   => $key,
          'value' => $value,
        );
      }
    }
  
    return $args;

  });
```
I also looked at https://github.com/airesvsg/acf-to-rest-api-recursive, but I don't understand if and how I should use it here. 

FYI, here's how I'm creating a taxonomy:
```
function create_taxonomies() {
	// Add new taxonomy, make it hierarchical (like categories)
	$labels = array(
		'name'              => _x( 'Collections', 'taxonomy general name', 'textdomain' ),
		'singular_name'     => _x( 'Collection', 'taxonomy singular name', 'textdomain' ),
		'search_items'      => __( 'Search Collections', 'textdomain' ),
		'all_items'         => __( 'All Collections', 'textdomain' ),
		'parent_item'       => __( 'Parent Collection', 'textdomain' ),
		'parent_item_colon' => __( 'Parent Collection:', 'textdomain' ),
		'edit_item'         => __( 'Edit Collection', 'textdomain' ),
		'update_item'       => __( 'Update Collection', 'textdomain' ),
		'add_new_item'      => __( 'Add New Collection', 'textdomain' ),
		'new_item_name'     => __( 'New Collection Name', 'textdomain' ),
		'menu_name'         => __( 'Collections', 'textdomain' ),
	);

	$args = array(
		'hierarchical'      => true,
        'labels'            => $labels,
        'public'            => true,
		'show_ui'           => true,
		'show_admin_column' => false,
		'query_var'         => true,
        'rewrite'           => array( 'slug' => 'collection' ),
        'show_in_rest'      => true
    );

    register_taxonomy( 'collection', array( 'product' ), $args );
}
```

**Comment by geochanto** [comment]
Any update on this? Is it supported?

**Comment by airesvsg** [comment]
Hi @geochanto,

Please, pay attention in your variable `$ignored`.

Thanks

**Comment by geochanto** [comment]
> Hi @geochanto,
> 
> Please, pay attention in your variable `$ignored`.
> 
> Thanks

Sorry, can you please clarify what you mean? I added the field which I wanted to filter by in the `$ignore` array. Is there something else I should be doing, or doing differently?

**Comment by geochanto** [comment]
> Hi @geochanto,
> 
> Please, pay attention in your variable `$ignored`.
> 
> Thanks

@airesvsg sorry for misunderstanding. I thought I needed to add that field to `$ignore`. turns out it's the other way around. Thanks!

**Comment by geochanto** [comment]
@airesvsg I guess this is a non-issue and can be closed.
