### ISSUE TITLE
Plugin not activating

### ISSUE THREAD

**Issue by kdpuvvadi** [airesvsg/acf-to-rest-api#3]
I'm using bucket theme (if it is helpful) and it comes with acf pre bundled and acf to rest api plgin showing "activate advanced custom fields" and it is not activating, how can i possibly solve this,

**Comment by airesvsg** [comment]
Hi @kdpuvvadi,
I need more information. Can you share your project with me?
airesvsg@gmail.com

**Comment by kdpuvvadi** [comment]
@airesvsg check you inbox

**Comment by airesvsg** [comment]
@kdpuvvadi I answered your e-mail.

**Comment by kdpuvvadi** [comment]
check ur inbox

**Comment by kdpuvvadi** [comment]
got the files?

**Comment by airesvsg** [comment]
yes, check your email please.

**Comment by kdpuvvadi** [comment]
OMG! it is working man, thank you, thank you very much man, Thanks for time mate, you did a great job today.

**Comment by airesvsg** [comment]
:smile: :+1:

**Comment by karol-gontarski** [comment]
@airesvsg Hi! Can you share with us any solution?
