### ISSUE TITLE
/acf returns 404

### ISSUE THREAD

**Issue by 5tormTrooper** [airesvsg/acf-to-rest-api#30]
I've installed the latest WP REST API v2.0-beta13 and ACF to REST API v2.2.0 and I can't seem to get the request to return a response with the /acf/v2 URL. 
I'm trying to get the the ACF Pro fields for a custom post type. This example works (without the custom fields obviously):
http://whiskynotes.co/wp-json/wp/v2/note/31 
and this one doesn't:
http://whiskynotes.co/wp-json/acf/v2/note/31

I've added show_in_rest to the custom post type and have no other supporting functions for this. I feel like this should be something simple but I just can't figure it out. Please help!

**Comment by CesarDenis** [comment]
@5tormTrooper I'm having this problem too, open a issue now about it.

**Comment by airesvsg** [comment]
I'm already doing some tests.

**Comment by airesvsg** [comment]
Hi,
you are using a plugin to register the custom post type?
It's works for me, look: [vid01.mov](http://airesgoncalves.com.br/screenshot/acf-to-rest-api/issues/30/vid01.mov)
Thanks

**Comment by CesarDenis** [comment]
@airesvsg Yes I am using. Only difference is that I'm including the [plugin in theme](https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/).

**Comment by airesvsg** [comment]
Hi @CesarDenis,
What's the plugin that you are using to register custom post types?
Please say me the name and version.
Thanks

**Comment by 5tormTrooper** [comment]
@CesarDenis @airesvsg Aha! Thanks for that video :)

The difference between mine and yours is that I was [including it in theme via the functions file](https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/) instead of having it as normal activated plugin. I tried switching over to the standard plugin method and now it works!

I'm happy to do it this way, but maybe you'd like to investigate how to allow for included versions of ACF?

P.S. Was not using a plugin for custom post type, just the standard function.

**Comment by CesarDenis** [comment]
@airesvsg I am not use plugin fot custom post.
Like @5tormTrooper,I added the plugin by admin and it worked. But in my case in my project needed to include ACF PRO in theme.

**Comment by airesvsg** [comment]
Please add the code below in your **functions.php**
```PHP
add_action( 'rest_api_init', array( 'ACF_To_REST_API', 'init' ), 5 );
```
Thanks

**Comment by CesarDenis** [comment]
Tks @airesvsg. Work for me. 😄 
It would be nice to put this solution in the instructions.
