### ISSUE TITLE
Only the first acf field is shown at Posts

### ISSUE THREAD

**Issue by isengartz** [airesvsg/acf-to-rest-api#307]
I have created a new Custom Field Group linked with Posts.
![Screenshot from 2019-07-29 15-38-40](https://user-images.githubusercontent.com/10381621/62049057-1a7e7d80-b217-11e9-9859-8fe1d995d5e3.png)

I created a post and assigned some values to the 3 fields:
![Screenshot from 2019-07-29 15-38-55](https://user-images.githubusercontent.com/10381621/62049110-371ab580-b217-11e9-973b-4dc97d538330.png)

When I access the API Only the first is shown:

![Screenshot from 2019-07-29 15-39-03](https://user-images.githubusercontent.com/10381621/62049128-413cb400-b217-11e9-9498-c65c1a45c5f4.png)

I deleted the field group and recreated more than 2 times ( with different names each time both group and fields ) but Im keep getting the same issue over and over again

**Comment by isengartz** [comment]
After some debugging:
This issue happens for posts too and it happens at the LAST page/post created.
![Screenshot from 2019-07-30 09-20-17](https://user-images.githubusercontent.com/10381621/62105511-48ad9d00-b2ab-11e9-9c5b-e638324e0017.png)



> /v3/lib/class-acf-to-rest-api-acf-api.php

On line 86: If I `var_dump` the `$fields = get_fields( $this->id );` It only has the cta_head in the array. Although if I var_dump the get_fields(171) outside the method `public function get_fields( $request ) ` it returns all the fields

**Comment by isengartz** [comment]
Ok for anyone else that may get the same issue:

It was due to this piece of code that WPML suggest so it will pages / posts in ALL languages instead of the default one.

```add_action('rest_api_init', function() {
    if (defined('REST_REQUEST') && REST_REQUEST) {

        add_action('parse_query', function($q) {
                  $q - > query_vars['suppress_filters'] = true;
        });
    }
});```

**Comment by henrikwirth** [comment]
@isengartz How did you get both working? So that WPML is putting all the languages in the default api response and also that it doesn't interfere with ACF to Rest API?

**Comment by isengartz** [comment]
@henrikwirth I spent some time tweaking both acf plugin and wpml hook but didn't find out a solution. I contacted WPML support and they told me that they don't intend to make a fix from their side and I should contact the author of acf plugin to make it work with their crappy hacky code!!!! I think I'm going to use Polylang plugin instead that it was working fine.
