### ISSUE TITLE
Doesn't work with the WP API Swagger Generator

### ISSUE THREAD

**Issue by JoelStickney** [airesvsg/acf-to-rest-api#31]
https://github.com/starfishmod/WPAPI-SwaggerGenerator

Noted in that plugin: "This plugin works well with WP-APIv2 and any plugin that uses the WP_REST_Server class to register it's API's"

**Comment by airesvsg** [comment]
Hi @JoelStickney,
In my plugin doesn't have the schema definitions.
Soon I'll implement.
Thanks

**Comment by jeremyjoyce** [comment]
Hi @airesvsg,

Has this feature been implemented? I am not seeing ACF via the Swagger Generator.

Thanks!

**Comment by airesvsg** [comment]
Hi @jeremyjoyce,

This feature hasn't been implemented.

Thanks

**Comment by strarsis** [comment]
@airesvsg: Any plans for OpenAPI/swagger support in the near future?
