### ISSUE TITLE
Updating ACF fields from non-admin users.

### ISSUE THREAD

**Issue by nicer00ster** [airesvsg/acf-to-rest-api#311]
Hello,

I'm building a blog-style application and current I'm trying to update `post_likes` on each post. On the frontend you're able to update the `post_likes` as long as you're logged in as an administrator.

If I create a new account then the user is automatically assigned a `Subscriber` role and I think changing this to set it as an admin by default creates a big vulnerability in my app.

Currently when I ping `http://localhost:8000/wp-json/acf/v3/posts/1` with a `POST` request with the appropriate headers (JWT, Content-Type) as an Admin, it works and I need this to be the case for all users.

I imagine there is a way to alter the `functions.php` file to allow all user roles to update specific ACF fields, but I don't specialize in PHP and would love to get some insight on how to solve this.

**Comment by Monomachus** [comment]
Use the role Contributor

**Comment by nicer00ster** [comment]
@Monomachus Thanks for the reply! Should've done research on other user roles before opening this issue lol. The contributor role didn't work even though it states they should be able to publish posts & upload media etc. BUT the Author role is working. Thanks!

**Comment by Monomachus** [comment]
@nicer00ster Then I guess you can close this issue :D
