### ISSUE TITLE
Filtering by ACF

### ISSUE THREAD

**Issue by Spence1115** [airesvsg/acf-to-rest-api#314]
Hi

I've looked through other posts here and I'm deeply lost.

I have my api outputting the following
```JSON
acf: {
"metadata": {
"title": "Title",
"image": false,
"description": "Description",
"hideFromSearchResults": false
}
}```

I'm trying to add a filter to the URL so I can choose to filter out pages where hideFromSearchResults = true

I cannot get it to work. Can anyone help?

**Comment by airesvsg** [comment]
Hi,

Please, how you want to use this? You want to filter via url?

Thanks

**Comment by clmntrss** [comment]
Hello may I ask also how to filter by URL my ACF data 
Structure looks like this 

`contributor: [
{
ID: 60903,
post_author: "798",
post_content: "Content.",
post_title: "Name Firstname",
post_excerpt: "",
post_status: "publish",
comment_status: "closed",
ping_status: "closed",

}
],`

I would like to filter by contributor.id for example.

**Comment by Spence1115** [comment]
@airesvsg to the API, yes. So when visiting 

> /wp-json/wp/v2/posts

I want to be able to filter that down by some of the ACF fields, in this case acf.metadata.hideFromSearchResults

**Comment by allansolutions** [comment]
I would also like to see an example of how I can filter which pages are available via the REST api - I want to use ACF Pro on pages that are both publicly visible and protected - and I don't want any details of the protected pages to become accessible via the ACF REST API
