### ISSUE TITLE
Can't create/update custom field value

### ISSUE THREAD

**Issue by iMohamedSamir** [airesvsg/acf-to-rest-api#316]
Trying to post/put custom field named `sourceurl` with no luck at all
when I GET posts I get this:
`'acf': {'sourceurl': None},`
I tried to query it on `http://localhost/wp-json/wp/v2/posts/1717` and the same endpoint but with v3 and `application/json` in the headers like this:
`"acf": {"sourceurl": "https://example.com'}`, and this `"sourceurl": "https://example.com'`, didn't work. I don't know if this problem with me or its an issue.

I am working with this plugins:
JSON Basic Authentication
Advanced Custom Fields
ACF to REST API, _Obviously_

**Comment by iMohamedSamir** [comment]
@airesvsg  I think its not duplicated, in https://github.com/airesvsg/acf-to-rest-api/issues/289#issue-405556652 (Which I commented on) the author was getting an error, I am not getting anything at all.
I think you need to reconsider this label, and if possible to help me.

**Comment by iMohamedSamir** [comment]
Funny enough I found the "hacky" solution in https://github.com/airesvsg/acf-to-rest-api/issues/177 idk why it works, but it works, weirdly enough its just 1 item per request, fortunately I only have one field to post/put.

Not so helpful author tbh

**Comment by nourseofcourse** [comment]
Did you try: `{"fields": {"sourceurl": "https://example.com"}`

**Comment by iMohamedSamir** [comment]
@nourseofcourse tried it and it worked, thanks a lot
