### ISSUE TITLE
acf: false

### ISSUE THREAD

**Issue by imsunnle** [airesvsg/acf-to-rest-api#32]
Somehow whenever I hit this URL: http://staging2.marketplace.intelledox.com/wp-json/acf/v2/post/5225/

I was expecting all the fields in acf but only {"acf":false} was returned. Please help

**Comment by imsunnle** [comment]
Ok so I got this: http://staging2.marketplace.intelledox.com/wp-json/acf/v2/post/11 

and it gave me {"acf":{"video_url":"videohere","live_preview_url":"","requirements":""}}

video_url , video_url and requirements are all blank i'm not sure why

I'm using ACF and EDD-API

**Comment by airesvsg** [comment]
Hi @imsunnle,
When you edit the post **5225**, the ACF Fields are displayed?
Thanks

**Comment by imsunnle** [comment]
5225 is actually the id of a particular products/extensions I want to get data from.

Updated: using this http://staging2.marketplace.intelledox.com/wp-json/acf/v2/post/11 I was able to get the video_url:"videohere" but it's not the value of the particular product with ID : 5225 (http://staging2.marketplace.intelledox.com/wp-json/acf/v2/post/5225/video_url)

**Comment by imsunnle** [comment]
and yes when I edit post 5525 ACF fields were there:

![image](https://cloud.githubusercontent.com/assets/8956212/15309673/527df2d0-1c2c-11e6-8710-b0621e61e907.png)

using this : http://staging2.marketplace.intelledox.com/wp-json/acf/v2/post/5225/video_url I was able to get video_url only but not the whole acf object

**Comment by airesvsg** [comment]
Hi @imsunnle,
Please send me your files with database dump. ( airesvsg@gmail.com )
In my local test I'm not seeing errors.
Thanks

**Comment by imsunnle** [comment]
I got this issue solved by just simply removing my functions.php as well as the plugin and started to install everything again. 

Thanks @airesvsg for your help.
