### ISSUE TITLE
Donation Notice

### ISSUE THREAD

**Issue by rubas** [airesvsg/acf-to-rest-api#324]
I do understand your motivation for adding a donation banner in the version `3.2.0` but please consider the implication of your global banner for every user.

There are many ways to ask for support and donations but this is not the way. It is too intrusive and creates a lot of confusion with  "normal" users. This is not something we can roll out ... 

 ```PHP
add_action( 'admin_menu', function() {
   remove_action( 'admin_init', array( 'ACF_To_REST_API_Donation', 'init' ) );
} );
```

**Comment by anugupta** [comment]
Adding a donation notice for EVERY backend user isn't really on, dude.

**Comment by airesvsg** [comment]
Hi @anugupta,

Would you buy a license to remove the donation notice? What do you think about this?

I want to have only one way to monetize the plugin.
Donations are rare, but I am grateful to everyone who uses my plugin and donates.

Thanks

**Comment by noeltock** [comment]
Donations are great, but the notice can't be persistent for every user (i.e. without the option to hide/close it).

@rubas @anugupta I wrote/reverted to:

```php
add_action( 'admin_init', 'remove_acf_donate');
function remove_acf_donate(){
    remove_action('admin_notices', array('ACF_To_REST_API_Donation', 'donation_notice'), 10);
}
```
