### ISSUE TITLE
Rest API Cache Management

### ISSUE THREAD

**Issue by mnguye08** [airesvsg/acf-to-rest-api#35]
Hi @airesvsg,
sorry to bother you again!
I have a new problem: the cache management.
How can I cache the json response (Redis, Memcache, ...). I've tried several plugins and librairies (Simple Cache, Redis Object Cache, jp-rest-cache) with no result.
Thanks

**Comment by airesvsg** [comment]
Hi @mnguye08,
I last saturday I launched the plugin **WP REST API Cache**.
https://github.com/airesvsg/wp-rest-api-cache
Thanks

**Comment by mnguye08** [comment]
Thanks @airesvsg!

**Comment by mnguye08** [comment]
Thanks @airesvsg!
