### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by gpezier2** [airesvsg/acf-to-rest-api#36]
Hi,

Thanks for your great plugin !
Please could you tell me how we can get the draft content, with an URL like : /wp-json/wp/v2/posts/?status=draft ?

Indeed, for your information actually we use the plugin https://wordpress.org/plugins/live-drafts/ in order to have, in same time, 2 versions of a post : published & draft

But maybe you know the better way (new filter or other plugin ... ) to have :
- 2 versions for a post : published and  draft
- get from the API a draft version of a post

Thanks by advance for your help

Best regards

**Comment by airesvsg** [comment]
Hi @gpezier2,
draft content aren't allow to get them.
![draft](https://cloud.githubusercontent.com/assets/396668/15512204/1acd7bb0-21b5-11e6-813d-0eceb9722671.png)
For more details, please open a new issue [here](https://github.com/WP-API/WP-API/issues/new).
Regards

**Comment by gpezier2** [comment]
Hi,

Thanks for your answer, but there is really no other solution ? 
Indeed how can we have a preview mode ?

Actually we have a SPA project (Single Page Application) and we need to have a preview mode before publish a content.

How can we do this, as simple as possible ?

Thanks by advance for your help

**Comment by airesvsg** [comment]
Hi @gpezier2,
If you want get draft content, you must be logged in your application.
http://v2.wp-api.org/guide/authentication/
Thanks
