### ISSUE TITLE
Not detecting ACF Pro in Mylisting Theme

### ISSUE THREAD

**Issue by bruce12345** [airesvsg/acf-to-rest-api#360]
Hi, we're using this theme https://mylistingtheme.com/ 
ACF pro is bundled with the theme. (you don't see it in the plugins though)
When installing acf-to-rest-api it doesn't detect that ACF Pro is present, so you cannot go to the settings page. Is there anyway to enable this?

**Comment by gtsvetanov** [comment]
Hello, 

Can you provide an information about following points:
- Can you use freely the ACF Pro or you know that this theme depends on it?
- In which folder is located your ACF pro plugin? Is it in any of these folders:
```
wp-content/plugins/advanced-custom-fields-pro/
wp-content/plugins/acf-pro/
wp-content/plugins/advanced-custom-fields/
```
- What is the OS of your hosting? 

I'm not familiar with your theme but if you can provide us it's directory tree we will be able to help easier :)

**Comment by bruce12345** [comment]
Hi Georgi,

The theme depends on ACF Pro
I believe the ACF Pro plugin is located in: Is it wp-content/themes/my-listing/includes/extensions/advanced-custom-fields

We host with Siteground so Fedora

**Comment by bruce12345** [comment]
Hi Georgi,

The vendor confirmed also:
The directory is includes/extensions/advanced-custom-fields/plugin Loaded in includes/extensions/advanced-custom-fields/advanced-custom-fields.php

**Comment by gtsvetanov** [comment]
Hello Bruce12345.

There is a check in class ACF_To_REST_API method is_plugin_installed() on line 112 :) Try to add the path of your acf.php to see what will happen. If this fix the issue then maybe @airesvsg must add a hook for adding custom paths in this check :)

**Comment by bruce12345** [comment]
Hi Georgi,

I added the path to line 112, but it doesn't work. I think it's still looking inside the plugin directory instead of in the theme directory because of $plugin or ABSPATH (?)

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api/issues/253#issuecomment-474680689
