### ISSUE TITLE
Can't update acf field inside a comment 

### ISSUE THREAD

**Issue by fabioquarantini** [airesvsg/acf-to-rest-api#37]
Hello, thanks for the great plugin.

I have a custom field  "rating"  which is assigned to every comment, 
I can read the value by doing :
GET http://website.com/wp-json/acf/v2/comment/2
and the response is 
{
  "acf": {
    "rating": "3"
  }
}

I need to update this value when a user submit a rating and the call looks like this:
PUT http://website.com/wp-json/acf/v2/comment/2
body is form-data
fields[rating] = 4

this is the response i get:
{
  "code": "cant_update_item",
  "message": "Cannot update item",
  "data": {
    "status": 500
  }
}

**Comment by airesvsg** [comment]
Hi @fabioquarantini,
when you edit the field, you are authenticated?
http://v2.wp-api.org/guide/authentication/
Thanks

**Comment by fabioquarantini** [comment]
Yes I'm using Basic Auth

**Comment by airesvsg** [comment]
OK, I'll test soon.

**Comment by airesvsg** [comment]
Hi @fabioquarantini,
please put this snippet in your **functions.php**
```PHP
add_filter( 'acf/location/rule_match/comment', function(){
	return true;
} );
```
Thanks

**Comment by fabioquarantini** [comment]
It works. Thanks

**Comment by ileafsolutions** [comment]
Hi, Could you help me in editing a notes field of acf. Here is the response which I have when called this http://test.localhost/wp-json/acf/v2/user/279 using the method GET
{
  "acf": {
"notes": [
      {
        "note": "test test",
        "user_id": "3",
        "col1": null,
        "user_name": "siteadmin",
        "col2": null,
        "created_at": "08/05/2016 09:08:55 am",
        "col3": null,
        "modified": "08/05/2016 09:09:39 am"
      },
      {
        "note": "test2 test2",
        "user_id": "3",
        "col1": null,
        "user_name": "siteadmin",
        "col2": null,
        "created_at": "08/05/2016 09:08:55 am",
        "col3": null,
        "modified": "08/05/2016 09:09:40 am"
      }
]

I would like to add another notes. I tried with PUT method and it says 
{
  "code": "cant_update_item",
  "message": "Cannot update item",
  "data": {
    "status": 500
  }
}

I have tried via postman.Its would be great if you could help me on this.
