### ISSUE TITLE
Unable to POST to a ACF. 

### ISSUE THREAD

**Issue by draganov12** [airesvsg/acf-to-rest-api#379]
Hi,

Im using a python script to automate my website. I have succeded in posting everything besides to the advanced custom fields. I've downloaded this plugin (both this and recursive) but still I face the same issue. 

To explain it more, I have for example a field called button_label. I want to give this field the value of "Hello World". When I post this value with my script I get the value of 'null' or ''. 

Any ideas how I can fix this? 

I appreciate all the help that I can get (bear in mind that I'm really new to programming).

**Comment by Nechir-89** [comment]
I do have same issue
here is what I try to post to my Booking posts
{
    "title":"New Post",
    "content": "user content",
    "acf": {
        "name": "name",
        "email": "email@gmail.com",
        "date": "07-07-21",
        "room_type": "Family",
        "number_of_rooms": "1",
        "adults": "1",
        "children": "0",
        "message": "nothing"
    },
    "status": "publish"
}

**Comment by Nechir-89** [comment]
I solved the issue by changing "acf" to "fields" name

{
    "title":"New Post",
    "content": "user content",
    "fields": {
        "name": "name",
        "email": "email@gmail.com",
        "date": "07-07-21",
        "room_type": "Family",
        "number_of_rooms": "1",
        "adults": "1",
        "children": "0",
        "message": "nothing"
    },
    "status": "publish"
}

**Comment by draganov12** [comment]
Thank you for your help!

It solved the issue for me as well. Thank you very much!



Den fre 7 maj 2021 kl 11:14 skrev Nechir dev ***@***.***>:
