### ISSUE TITLE
Filter fields

### ISSUE THREAD

**Issue by gpezier2** [airesvsg/acf-to-rest-api#38]
Hi,

- We have used this solution in order to  made a query on some ACF Fields : 
https://github.com/airesvsg/acf-to-rest-api/issues/13

- We have used this solution in order to remove some fields in the JSON  : 
https://github.com/airesvsg/acf-to-rest-api/issues/34

- We have used your new Plugin
https://github.com/airesvsg/wp-rest-api-cache

But we have 2 issues : 
1/ with the cache the fields we want to remove are not removed (it's OK without cache).
Indeed the cache plugin store the complete JSON and not the JSON filtered by our method add_filter('acf/rest_api/post/get_fields', function ($data) {...}
How can we correct that ?

2/ We have issue with performance when we search a new word (not cached) : about 3 seconds on our localhost with only 5 contents.
Do you have a solution ?
For example, I think it will be better to select in the query only fields needed instead of select all fields and remove fields in the JSON after ? 
So, do you know how improve the search ?

Thanks by advance for you help.

Best regards

**Comment by airesvsg** [comment]
Hi @gpezier2,
I'll test soon.
Thanks

**Comment by gpezier2** [comment]
Hi Aires,

I hope you are fine.
I saw you have updated plugin https://github.com/airesvsg/wp-rest-api-cache but we have same problem.

Did you reproduce my 2 points described in my first message ? 

Thanks a lot

**Comment by airesvsg** [comment]
Hi @gpezier2,
I did some tests and I recorded this video [acf-cache.mov](http://airesgoncalves.com.br/screenshot/acf-to-rest-api/issues/38/acf-cache.mov)
I can't see any problem.
Thanks

**Comment by gpezier2** [comment]
Thanks for your video 
It's OK by our side with your example (we have same result).

But our issue is more strange (we have just a clean process more long)
[Archive.zip](https://github.com/airesvsg/acf-to-rest-api/files/293691/Archive.zip)
In attachment you will find a video and our source code of our function in order to filter JSON

Do you know the reason ? 

Thanks again

**Comment by airesvsg** [comment]
Hi @gpezier2,
can you send me the database dump?
airesvsg@gmail.com
Thanks
