### ISSUE TITLE
Update empty

### ISSUE THREAD

**Issue by NickyBass** [airesvsg/acf-to-rest-api#4]
"Doc_documento" is a custom post_type"
Every time i try to update with POST this url:
wp-json/wp/v2/doc_documento/1

The response is  [acf] => stdClass Object ( [_empty_] => '' inside the object of that particular post.
Do you know why?

**Comment by NickyBass** [comment]
First i create the post with api, then i update the fields. But i think i need to update the plugin 'cause i have seen here #2 that you cannot update the fields if you didn't create the post on wp-admin.
Is that correct?

**Comment by NickyBass** [comment]
Fixed :+1: sorry for the issue :-)

**Comment by airesvsg** [comment]
:+1:
