### ISSUE TITLE
Retrieve posts in draft

### ISSUE THREAD

**Issue by mnguye08** [airesvsg/acf-to-rest-api#40]
Hi @airesvsg,
do you know how to retrieve posts in draft status?
I've tried ?status=draft but have an error (400 "rest_invalid_param").

I use Live Drafts plugin (https://wordpress.org/plugins/live-drafts/), WP OAuth Server (https://wp-oauth.com/), create a clientKey and clientSecret, generate a valid access_token and pass it to the webservice (/wp-json/wp/v2/posts/?status=draft&access_token=XXX).

Thanks for your help!

**Comment by airesvsg** [comment]
Hi @mnguye08,
your problem is Authentication, your **access_token** isn't correct.
Thanks

**Comment by mnguye08** [comment]
Hi @airesvsg,
why is it not correct? 
What is the good method? Do you have an example to implement it?
Thanks!

**Comment by airesvsg** [comment]
Hi @mnguye08,
I will prepare something to exemplify ( oAuth1 and Basic Authentication ).
Thanks
