### ISSUE TITLE
Rename from 'acf' in JSON

### ISSUE THREAD

**Issue by justinackermann** [airesvsg/acf-to-rest-api#41]
Is there a way to edit how the acf fields show in the JSON listing? For example I do not want my custom field to show under the field 'acf' but something custom. With the old plugin I was able to find how to change this but with V2 I am unable to find where this is set.

**Comment by airesvsg** [comment]
Hi @justinackermann,
you should use the filter "**acf/rest_api/_{type}_/get_fields**".

The wildcard **{type}** can be: post, page, user, term, comment, attachment, options or custom_post_type ( book )...

Thanks

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( isset( $data['acf'] ) ) {
        $data['key'] = $data['acf'];
        unset( $data['acf'] );
    }

    return $data;
} );
```

**Comment by justinackermann** [comment]
I think you misunderstood me or I am misunderstanding you. Currently my json is for example:
`acf: {
field_title: "data" }`

I would like it to be something like:
`custom_naming_scheme: {
field_title: "data" }`

**Comment by airesvsg** [comment]
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( isset( $data['acf'] ) ) {
        $data['custom_naming_scheme'] = $data['acf'];
        unset( $data['acf'] );
    }

    return $data;
} );
```

**Comment by misfist** [comment]
Thanks! This is just what I was looking for!
