### ISSUE TITLE
Does the plugins covers search posts by acf fields?

### ISSUE THREAD

**Issue by roshi-bushido** [airesvsg/acf-to-rest-api#42]
We are using this plugins and it rocks but we ran into problem where we need to search the posts any a custom field and I haven't found an answer anywhere. It would be a great feature to complement the plugin with.

**Comment by airesvsg** [comment]
Hi @roshi-bushido,
please read this issue: https://github.com/airesvsg/acf-to-rest-api/issues/13
Thanks
