### ISSUE TITLE
Checkbox update

### ISSUE THREAD

**Issue by theApprentice** [airesvsg/acf-to-rest-api#44]
Hi airesvsg, i've pretty much copied your js function to perform rest calls and also the php/html of the modal, all goes nice and smooth except when comes to updating checkboxes. If i check one of them when i create the post it works, if i want to modify the post i can check and the result is ok, but i'm unable to uncheck and send the status modification. Is there any shrewdness to implement to perform such task?

TY,
G.

**Comment by airesvsg** [comment]
Hi @theApprentice,
Sorry for the delay. 
Please, share your code with me.
airesvsg@gmail.com
Thanks

**Comment by theApprentice** [comment]
No worries airesvsg!
i guess it was my error, looks like if you have only one checkbox it doesnt update, i've just changed in favor of the radio button this morning and now all work ok!
ty anyway!
