### ISSUE TITLE
More READABLE options

### ISSUE THREAD

**Issue by webmaster-imaginet** [airesvsg/acf-to-rest-api#46]
Hi,

Can you add **READABLE** with some "general" options like:
/wp-json/wp/v2/posts
/wp-json/wp/v2/pages
/wp-json/wp/v2/categories
/wp-json/wp/v2/media
etc...

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api/issues/45

**Comment by airesvsg** [comment]
Hi @webmaster-imaginet,
Yesterday I released a new version ( 3.0.0-beta ).
Please, check it works for you.
Thanks
