### ISSUE TITLE
Empty fields JSON values

### ISSUE THREAD

**Issue by silentjohnny** [airesvsg/acf-to-rest-api#48]
I'm seeing the following behaviour:
- no ACF fields returns "acf":false
- empty array type field (e.g., relationship) returns ""
- empty scalar type field (e.g, number) returns ""
- empty object type field (e.g., link, image) returns false

In order to be consumed easily by any REST API client, wouldn't it make more sense to return null for empty scalar and object fields and [] for empty array fields?

Or is there another way to rewrite those values?

**Comment by airesvsg** [comment]
Hi @silentjohnny,
you can rewrite those values using the filter `acf/rest_api/{type}/get_fields`.

How to use:
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( isset( $data['acf'] ) && ! $data['acf'] ) {
        $data['acf'] = array();
    }

    return $data;
} );
```

The wildcard **{type}** can be: post, page, user, term, comment, attachment, options or custom_post_type ( book )...

Thanks

**Comment by silentjohnny** [comment]
@airesvsg that actually worked for now! Thanks for the explanation. 

I can see there is a problem in determining the correct values (with ACF storing empty strings and such), although I would prefer setting empty and null values to a literal "null" in JSON and only use "false" for actual boolean values.

Perhaps it would be a good idea to file an issue with Elliot Condon about the way empty values are stored? What are your thoughts on this?

**Comment by airesvsg** [comment]
Hi @silentjohnny,
Yesterday I released a new version ( 3.0.0-beta ).
Please, check it works for you.
Thanks

**Comment by egamboa** [comment]
I'm install the plugin, I'm running the right queries, I even update to the v3.
I'm getting some of the posts as: 
acf: false
I go an hit update in the post and I get the acf OBJ, I don't want to go and update +1000 posts in my dd or prod db. 

not sure if I have to change my urls to v3 or what. the plugin looks good, but some how it just ignores some of the posts meta.

**Comment by josephdburdick** [comment]
@egamboa check this issue out: https://github.com/airesvsg/acf-to-rest-api/issues/139

I found a solution...but it's not free.

**Comment by celsowhite** [comment]
Here is the answer to this https://github.com/gatsbyjs/gatsby/issues/4461#issuecomment-371775563.
