### ISSUE TITLE
How to filter custom post type

### ISSUE THREAD

**Issue by LOL2011** [airesvsg/acf-to-rest-api#51]
I have a custom post type ‘Files’ and have the plugins, ‘ACF to REST API’, ‘Advanced Custom Fields’ and ‘WP REST API’ installed.

I can get the JSON for ‘FILES’ using:

http://mywebsite.co.uk/wp-json/wp/v2/files/

I need to filter this using the custom fields set using ACF.

I can’t seem to find how I would do this and also I can’t seem to get any results via the endpoints specified by this plugin ie.

http://mywebsite.co.uk/wp-json/acf/post/ID

Can anyone help? I have spent all morning trying to get this working but am getting nowhere.

Many thanks

**Comment by airesvsg** [comment]
Hi @LOL2011,
please look this issue: https://github.com/airesvsg/acf-to-rest-api/issues/1#issuecomment-168877982

Endpoint to Files:
`/wp-json/acf/v2/{post-type}/{id}` => `/wp-json/acf/v2/files/{id}`

Thanks

**Comment by LOL2011** [comment]
Hi,

Thanks for your quick response, its much appreciated.

That answers my query regarding the end points so many thanks for that.  However, my main query is  how to filter the JSON using a custom field.  So for example, I would want to get all FILES with a custom field, "category" that equals 'whatever'.

I have tried using  '/wp-json/acf/v2/files/?filter[category]=whatever' but I get a 404.

If I use '/wp-json/wp/v2/files/?filter[category]=whatever', it displays all files and doesn't filter.

**Comment by airesvsg** [comment]
It is not supported.

**Comment by LOL2011** [comment]
oh no, don't suppose you could point me in the direction of another solution that does support it?

**Comment by bookwyrm** [comment]
@LOL2011 This may help if you're using the WP (not ACF) endpoint: <http://wordpress.stackexchange.com/questions/210597/query-wp-rest-api-v2-by-multiple-meta-keys>

**Comment by airesvsg** [comment]
```PHP
add_action( 'rest_api_init', 'register_file_route', 10 );

function register_file_route() {
	register_rest_route( 'namespace/v2', '/files', array(
		array(
			'methods'  => WP_REST_Server::READABLE,
			'callback' => 'get_file',
		),
	) );
}

function get_file( WP_REST_Request $request ) {
	$filter = $request->get_param( 'filter' );
	$data   = array();

	$args = array(
		'posts_per_page' => -1,
		'post_type'      => 'file',
	);

	if ( is_array( $filter ) && array_key_exists( 'category', $filter ) ) {
		$args['category_name'] = $filter['category'];
	}

	$files = get_posts( $args );

	if ( ! empty( $files ) ) {
		foreach( $files as $post ) {
			$acf = get_fields( $post->ID );
			if ( ! empty( $acf ) ) {
				$data[] = array_merge( array( 'id' => $post->ID ), $acf );
			}
		}
	}

	return $data;
}
```

List all: 
`/wp-json/namespace/v2/files`

Filter by category: 
`/wp-json/namespace/v2/files?filter[category]=whatever`

Thanks

**Comment by LOL2011** [comment]
Thats works brilliantly, thanks for your help, much appreciated!
