### ISSUE TITLE
Endpoint post type 404 error

### ISSUE THREAD

**Issue by jairgarcia** [airesvsg/acf-to-rest-api#52]
When i try to get the data from the post type product, i receive a error 404, here is my code:

```
$.ajax({ url: {homeURL} + '/wp-json/acf/v2/product/' + {id}, type: 'GET' })
							.done( function( data ) {
								console.log('Product data, acf ' , data);
							})
```

This is the error.
`
{"code":"rest_no_route","message":"No se encontr\u00f3 la ruta que coincida con la URL y el m\u00e9todo de la petici\u00f3n","data":{"status":404}}
`

I appreciate any help.

**Comment by airesvsg** [comment]
Hi @jairgarcia,
Please look it:
https://github.com/airesvsg/acf-to-rest-api/issues/22

Thanks

**Comment by jairgarcia** [comment]
I use woocommerce plugin, how i make show in rest = true, for to get the product post type?

Thanks

**Comment by airesvsg** [comment]
Please use the code below:

```PHP
function woocommerce_product_show_in_rest() {
	global $wp_post_types;

	if ( isset( $wp_post_types['product'] ) ) {
		$wp_post_types['product']->show_in_rest = true;
		// $wp_post_types['post']->rest_base = 'product';
		// $wp_post_types['post']->rest_controller_class = 'WP_REST_Posts_Controller';
	}
}

add_filter( 'init', 'woocommerce_product_show_in_rest', 11 );
```

Thanks

**Comment by jairgarcia** [comment]
Response: 

{"acf":false}

What i do?, thanks.

**Comment by airesvsg** [comment]
@jairgarcia please watch this video: [acf-to-rest-api-woocommerce.mov](http://airesgoncalves.com.br/screenshot/acf-to-rest-api/issues/52/acf-to-rest-api-woocommerce.mov)

**Comment by jairgarcia** [comment]
@airesvsg Thanks again. I found the error, i'm creating new products with the woocommerce api rest, but i see that i need to update each product created manually.
