### ISSUE TITLE
Filtrar Custom Post Type com os argumentos do ACF

### ISSUE THREAD

**Issue by alanbasilio** [airesvsg/acf-to-rest-api#53]
Oi Aires, estou tentando criar um filtro de busca para o plugin e não estou conseguindo.

http://asw.azlabs.com.br/wp-json/acf/rest_api/onde-encontrar/get_fields

Tenho dois valores pra serem retornados, city e uf.
Essa url está correta?

Meu filtro:
```PHP
add_filter( 'acf/rest_api/onde-encontrar/get_fields', function( $data, $request, $response ) {
    if ( $response instanceof WP_REST_Response ) {
        $data = $response->get_data();
    }

    if( isset( $data['acf'] ) ) {
        $data['acf']['city']->acf = get_fields( $data['acf']['city']->ID );
        $data['acf']['uf']->acf = get_fields( $data['acf']['uf']->ID );
    }   

    return $data;
}, 10, 3 );
```

Eu recebo uns erros quando uso esse filtro.

**Comment by airesvsg** [comment]
Oi @alanbasilio,
A URL que você está tentando acessar não está correta, tente:
http://asw.azlabs.com.br/wp-json/acf/v2/onde-encontrar/450 

Você não precisa usar o filtro para obter os valores do ACF.
