### ISSUE TITLE
Plugin returns false

### ISSUE THREAD

**Issue by ikristher** [airesvsg/acf-to-rest-api#55]
Hello,

I am downloading social media posts from different social networks and inserting them on custom post type. I was able to add the custom fields but the api returns false for acf. It only works when I press the update button in the backend manually. 

Here is my code

$post_id = wp_insert_post( $post );

update_field( 'social_meta', sanitize_text_field( json_encode( $feed ) ), $post_id );

**Comment by airesvsg** [comment]
Hi @ikristher,
please rewrite your question. I didn't understand.

Thanks

**Comment by ikristher** [comment]
Hello Sorry, basically whenever I add custom fields manually using the function and wp_insert_post() and update_field(), the api doesn't recognize the fields and it returns false. However it works after I update the newly inserted post in the WordPress back end.

**Comment by airesvsg** [comment]
Hi @ikristher,
please read this issue: https://github.com/airesvsg/acf-to-rest-api/issues/64
Thanks
