### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by roladn** [airesvsg/acf-to-rest-api#57]
I have add this snippet 
```PHP
add_filter( 'acf/location/rule_match/options_page', function(){
	return true;
} );
```
```PHP
add_filter( 'acf/rest_api/option/prepare_item', function( $item ){
	if ( isset( $item['id'] ) ) {
		$item['id'] = 'options';
	}
	
	return $item;
});
```

But this function is now showing the options function into every post type page 
![image](https://cloud.githubusercontent.com/assets/5981015/17588878/df570762-5fd1-11e6-9d5e-d359235b3a9c.png)

**Comment by airesvsg** [comment]
Hi @roladn,
please replace your first filter for this:

```php
add_filter( 'acf/location/rule_match/options_page', function() {
	$page = isset( $_GET['page'] ) ? $_GET['page'] : null;

	return 'acf-options' == $page;
} );
```

Thanks

**Comment by roladn** [comment]
Hello @airesvsg 
I changed as you said 
But it removed the  the custom fields at all pages .
and i changed the 
return 'acf-options' == $page;
To 
return 'theme-general-settings' == $page;
This change is OK at back-end of WP 
but now i can't update the fields using Rest API
![image](https://cloud.githubusercontent.com/assets/5981015/17591044/944cb1f8-5fdc-11e6-9049-62a9596f7a8c.png)

**Comment by roladn** [comment]
`$page = isset( $_GET['page'] ) ? $_GET['page'] : null;
    $token = isset( $_GET['access_token'] ) ? $_GET['access_token'] : null;
    if('theme-general-settings' == $page || $token){
    return true;
    }else{
    return false;
    }
`
I changed a bit  the function to this and now it look All right 

I don't know if this solution is optimized but it is woorking
