### ISSUE TITLE
Get all custom post types

### ISSUE THREAD

**Issue by JSeligsohn** [airesvsg/acf-to-rest-api#58]
I'm confused - is there not a way to get all posts (or custom posts types)? Why are only single posts supported?

There is no call like this: `/wp-json/acf/v2/posts`? What am I missing?

**Comment by airesvsg** [comment]
Hi @JSeligsohn,
If you want to get all posts, use: `wp-json/wp/v2/posts`.

Thanks

**Comment by JSeligsohn** [comment]
And what about custom post types?

**Comment by airesvsg** [comment]
`wp-json/wp/v2/{my-custom-post-type}`

**Comment by JSeligsohn** [comment]
Ah okay... you only do `wp-json/acf/...` if you need a specific field?

**Comment by airesvsg** [comment]
yes, only you want a specific group of fields ou single field too.

**Comment by JSeligsohn** [comment]
Perhaps you can point me in the right direction - something isn't working for me.
I have a custom post type called "establishments" ("establishment" for single post), and I want to GET all the establishment posts. Here is my ajax call:
```
var getEstablishments = function() {
        $.ajax({
          url: "/wp-json/wp/v2/establishments",
          dataType: 'json',
          success: loadEstablishments
        }).fail(function() {console.log("Cannot work.");})
        .complete(initializeMap);
      };
```
The call fails. If I take out `dataType` then I just get a string which is the html of my homepage. Not sure what I'm doing wrong. I also tried both "establishments" (plural) and "establishment" (single). 
I'm running the latest version of wordpress - 4.5.3 and have Advanced Custom Fields plugin (Version 4.4.8), WP REST API (v 1.2.5) and ACF to REST API (v 2.2.1) installed as well.

**Comment by airesvsg** [comment]
Hi @JSeligsohn,
Please read it: http://v2.wp-api.org/extending/custom-content-types/
You used `show_in_rest` when you registered your custom post type?

Thanks

**Comment by JSeligsohn** [comment]
Thanks - that worked. I hadn't worked with wordPress for a while so I was unfamiliar with how the new (for me, at least) REST API worked. I guess what I needed didn't even require your acf-to-rest-api plugin, did it?
