### ISSUE TITLE
Not receiving all fields after wp update

### ISSUE THREAD

**Issue by katiasmet** [airesvsg/acf-to-rest-api#59]
Today I updated Wordpress to version 4.6 and ever since I'm not receiving all the acf fields with the rest api. I'm receiving a few fields but not all of them (even with the same field-type). 

Yesterday it worked like a charm. How can I solve this?

**Comment by airesvsg** [comment]
Hi @katiasmet,
I tested here and I didn't see any errors. 

Please see the video below
[![ACF to REST API](http://img.youtube.com/vi/3ljwUSJhKuA/mqdefault.jpg)](http://www.youtube.com/watch?v=3ljwUSJhKuA)

Thanks

**Comment by katiasmet** [comment]
Hi @airesvsg 
Thank you for your fast answer! I still have the problem and I made a screencast to make it more clear. I can get some acf f.e. textfields, repeater field but not all text-fields which is pretty strange. 

[https://youtu.be/sOhfkQZtsXs](url)

Thanks!

**Comment by katiasmet** [comment]
It might be a bug in acf. I added a custom end point to my route and tried get_fields(post_id) for every post. I got the same values as your plugin does.

I solved this by doing get_field( field_key, post_id) for every post on the fields I needed :).
