### ISSUE TITLE
Filter for options exposes all fields to front-end users

### ISSUE THREAD

**Issue by ethanclevenger91** [airesvsg/acf-to-rest-api#60]
After all this time using GitHub, I'm _still_ not sure if notifications go out on closed issues, so thought I would create a new one.

In order to get Options pages working correctly, [you implemented a filter on ACF's rule matching](https://github.com/airesvsg/acf-to-rest-api/issues/56#issuecomment-235771884), but this filter isn't particularly nuanced (specifically the `is_admin` check), so if I'm allowing users to [edit fields from the front end](https://www.advancedcustomfields.com/resources/create-a-front-end-form/), it ends up displaying all options fields as well as those I intend to display.

**Comment by airesvsg** [comment]
Hi @ethanclevenger91,
This filter is used because ACF limits the visibility of the options values. This error isn't in my plugin, please open a new thread here: https://support.advancedcustomfields.com/forums/forum/add-ons/options-page/

Thanks

**Comment by ethanclevenger91** [comment]
Hey @airesvsg ,

I'm digging through and trying to find a way around this. Can you describe what exactly is happening in [this function](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-controller.php#L70)? The call to `update_field` will accept the name of the field rather than the key and should be available in all versions of ACF (I think), so I'm trying to understand why a simpler pass-through isn't an option, like:

```
public function update_item( $request ) {
        if ( $request instanceof WP_REST_Request ) {
		$key  = apply_filters( 'acf/rest_api/key', 'fields', $request, $this->type );

		if ( is_string( $key ) && ! empty( $key ) ) {
			$data  = $request->get_param( $key );

			$field = $request->get_param( 'field' );

			$this->format_id( $request );

                        update_field($key, $data, $this->id);
	
		        return new WP_REST_Response( $this->get_fields( $request ), 200 );
                }
	}
}
```

I'm sure there's something pretty nuanced you're trying to do instead so I'm trying to understand what that is before I run around making pull requests.
