### ISSUE TITLE
ACF in CPT categories not appearing

### ISSUE THREAD

**Issue by joDelicious** [airesvsg/acf-to-rest-api#61]
Hi !

I have added some ACF fields for CPT categories, but they do not appear thru the endpoint at `wp-json/wp/v2/categories`.
I am using a ACF color picker, but have also tried a simple text field, but with no success...

Is it supposed to work, or not implemented yet ?

Thank you !

Johan

**Comment by joDelicious** [comment]
OK, digging your closed issues, i saw that i could get the acf fields calling particular category ids via : 
`wp-json/acf/v2/term/category/{id}`

It would be awesome to integrate all acf fields related to categories at :
`wp-json/wp/v2/categories`

Please let me know if i missed something...

Thank you !
Johan

**Comment by airesvsg** [comment]
Hi @joDelicious,
please follow these issues:
https://github.com/airesvsg/acf-to-rest-api/issues/43
https://github.com/airesvsg/acf-to-rest-api/issues/45

Thanks

**Comment by joDelicious** [comment]
I've looked at the other issues, but I still can't get it to work...   It would be awesome for the feature to be implemented in a future release... Best regards.
