### ISSUE TITLE
No way to get a list of key/value pairs

### ISSUE THREAD

**Issue by dalemugford** [airesvsg/acf-to-rest-api#62]
Love the work so far, thank you! When I send a GET request to `http://findexapp.com/wp-json/acf/v2/user/1/[field]` it returns the currently set value for the field, and the same happens for `http://findexapp.com/wp-json/acf/v2/user/1`, wrapped in `acf`.

I assume this is of course intended. What I'm looking for is a way to list the available values that the field currently has. For example, with a Radio Button field that accepts custom values and adds them to the available values, there's no way to get a list of them for the custom field currently, unless I'm missing something.

It would be great to have a GET request that could just fetch the available field key/value pairs, e.g.

`http://findexapp.com/wp-json/acf/v2/user/1/fruit?show=all` that would return:

`
{
  "fruit": {
     "apple": "Apple",
     "pear": "Pear",
     "peach": "Peach"
  }
}
`

**Comment by airesvsg** [comment]
Hi @dalemugford,
yes, it's possible, but I did a bit different I added the choices in the answer.

Copy and paste the below code in your **functions.php**
```PHP
if ( class_exists( 'ACF_To_REST_API_Controller' ) ) {
	class My_Custom_Controller extends ACF_To_REST_API_Controller {
		protected function get_fields( $request, $response = null, $object = null ) {
			$data = parent::get_fields( $request, $response, $object );
			
			if ( $this->id && ! empty( $data['acf'] ) ) {
				$field_objects = $this->get_field_objects( $this->id );

				if ( ! empty( $field_objects ) ) {
					foreach ( ( array ) $data['acf'] as $k => $v ) {
						if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['choices'] ) ) {
							$data[$k]['choices'] = $field_objects[$k]['choices'];
							$data[$k]['value'] = $v;
						}
					}					
				}
			}

			return apply_filters( 'acf/rest_api/' . $this->type . '/get_fields', $data, $request, $response, $object );
		}
	}

	add_action( 'rest_api_init', function(){
		$controller = new My_Custom_Controller( 'post' );
		$controller->register_hooks();
		$controller->register_routes();
	}, 0 );
}
```

New answer format:
```JSON
"acf": {
	"my_field": {
		"choices": {
			"red": "Red",
			"blue": "Blue",
			"black": "Black",
			"white": "White"
		},
		"value": "white"
	}
}
```

Thanks

**Comment by dalemugford** [comment]
Awesome! I'll give it a go! Thanks for taking the time to answer!!

**Comment by dalemugford** [comment]
Didn't work :(

I changed the url to `return apply_filters( 'acf/v2/'` to match the act rest api route, as I got a `rest_no_route` for  `acf/rest_api/lures/get_fields`.

`lures` is the field name under the user with the id of 1 — and their are 5 radio options in the WP admin for that user, for this field.

Here's what I have:

`if ( class_exists( 'ACF_To_REST_API_Controller' ) ) {
    class My_Custom_Controller extends ACF_To_REST_API_Controller {
        protected function get_fields( $request, $response = null, $object = null ) {
            $data = parent::get_fields( $request, $response, $object );

            if ( $this->id && ! empty( $data['acf'] ) ) {
                $field_objects = $this->get_field_objects( $this->id );

                if ( ! empty( $field_objects ) ) {
                    foreach ( ( array ) $data['acf'] as $k => $v ) {
                        if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['lures'] ) ) {
                            $data[$k]['lures'] = $field_objects[$k]['lures'];
                            $data[$k]['value'] = $v;
                        }
                    }                   
                }
            }

            return apply_filters( 'acf/v2/' . $this->type . '/get_fields', $data, $request, $response, $object );
        }
    }

    add_action( 'rest_api_init', function(){
        $controller = new My_Custom_Controller( 'post' );
        $controller->register_hooks();
        $controller->register_routes();
    }, 0 );
}`

**Comment by airesvsg** [comment]
Hi @dalemugford,
The field is located to which group type (post, page, category, custom post type)?

Change the below code:
```php
if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['lures'] ) ) {
    $data[$k]['lures'] = $field_objects[$k]['lures'];
    $data[$k]['value'] = $v;
}
```

To:
```php
if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['choices'] ) ) {
    $data[$k]['lures'] = $field_objects[$k]['choices'];
    $data[$k]['value'] = $v;
}
```

`Choices` is default key in the ACF.

Thanks

**Comment by dalemugford** [comment]
Thanks :)

It's user. The field is 'lures', the field type is radio button, and there are 5 options currently. 

Okay so now it's:

`if ( class_exists( 'ACF_To_REST_API_Controller' ) ) {
    class My_Custom_Controller extends ACF_To_REST_API_Controller {
        protected function get_fields( $request, $response = null, $object = null ) {
            $data = parent::get_fields( $request, $response, $object );

            if ( $this->id && ! empty( $data['acf'] ) ) {
                $field_objects = $this->get_field_objects( $this->id );

                if ( ! empty( $field_objects ) ) {
                    foreach ( ( array ) $data['acf'] as $k => $v ) {
                        if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['choices'] ) ) {
						    $data[$k]['lures'] = $field_objects[$k]['choices'];
						    $data[$k]['value'] = $v;
						}
                    }                   
                }
            }

            return apply_filters( 'acf/rest_api/' . $this->type . '/get_fields', $data, $request, $response, $object );
        }
    }

    add_action( 'rest_api_init', function(){
        $controller = new My_Custom_Controller( 'user' );
        $controller->register_hooks();
        $controller->register_routes();
    }, 0 );
}`

**Comment by dalemugford** [comment]
the response from the server for `/wp-json/acf/v2/user/1` is:

`{
  "acf": {
    "lures": "Crankbait"
  }
}`

and for `wp-json/acf/v2/user/1/lures` is:

`{
  "lures": "Crankbait"
}`

**Comment by airesvsg** [comment]
Change:
```php
if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['choices'] ) ) {
    $data[$k]['lures'] = $field_objects[$k]['choices'];
    $data[$k]['value'] = $v;
}
```

To:
```php
if ( isset( $field_objects[$k] ) && isset( $field_objects[$k]['choices'] ) ) {
	$data['acf'][$k] = array();
    $data['acf'][$k]['choices'] = $field_objects[$k]['choices'];
    $data['acf'][$k]['value'] = $v;
}
```

**Comment by dalemugford** [comment]
Agh. Sorry!

Still getting `{
  "get_fields": false
}`

I'll attach a small php file with the snippet as it is. Thanks for trying!!
[snippet.php.zip](https://github.com/airesvsg/acf-to-rest-api/files/433785/snippet.php.zip)

**Comment by airesvsg** [comment]
Hi @dalemugford,
can you give access or send your files?
airesvsg@gmail.com

I tested your snippet and it's works.

Thanks

**Comment by dalemugford** [comment]
Oh!

What was the url you used?

What access do you need? FTP? WordPress?

I don’t have the code in the functions.php, I have it in a custom plugin I use on the site.

Dale M.
905-966-3693
dalemugford@me.com

**Comment by airesvsg** [comment]
I used the url `/wp-json/acf/v2/user/1`.

I need FTP and WordPress accesses.

**Comment by dalemugford** [comment]
I get:

`{
  "acf": {
    "lures": "Crankbait"
  }
}`

On that URL. The choices for the radio select are not shown, just the currently set value.

Dale M.
905-966-3693
dalemugford@me.com

**Comment by dalemugford** [comment]
How can I send you WP & FTP access?

**Comment by airesvsg** [comment]
airesvsg@gmail.com

**Comment by dalemugford** [comment]
I'm firing this up again... will send you an email.
