### ISSUE TITLE
acf: false

### ISSUE THREAD

**Issue by gbozzetti** [airesvsg/acf-to-rest-api#64]
Hi, i'm saving a new custom type post with the wp_insert_post() function and at the same time saving values in acf fields.

The new post and all the acf values are saved correctly (the post is in "pending" status).

Now if i publish the post using the "quick edit" panel in wordpress backend, the post change status correctly (and i can retrieve acf values also) but in the GET REST response i have a "false" result in acf array.

However, if i publish the post opening it in the "edit" panel and hitting the "publish" button, in the GET REST response i can find acf values correctly.

I'm usually publish "pending" posts using the bulk action and "quick edit" panel, so it's frustrating opening all posts one by one and click on "publish" button.

Thanks for your support.

**Comment by airesvsg** [comment]
Hi @gbozzetti,
sorry for the delay.

Can you provide some snippet of your code?

Thanks

**Comment by gbozzetti** [comment]
Hi @airesvsg, 

This is how i save a new custom type post with relative acf field

`$my_post = array(
			  'post_title'    => wp_strip_all_tags( $title ),
			  'post_content'  => $content,
			  'post_status'   => 'pending',
			  'post_type'   => 'listing',
			  'post_excerpt' => $excerpt
			);
$post_id = wp_insert_post( $my_post);
update_field( 'data_evento', $date->format('Ymd'), $post_id );`

This is what i obtain when i publish the post with classic procedure (open the post in admin area and hit the publish button):

![image](https://cloud.githubusercontent.com/assets/10655465/18782544/4d176a2c-8187-11e6-9823-460dd07dbd99.png)

And this is what i obtain when i publish the post using the "quick edit" panel in wordpress backend:

![image](https://cloud.githubusercontent.com/assets/10655465/18782585/79253bc6-8187-11e6-92f6-dca19de6f2b7.png)

Thanks for your support.

**Comment by airesvsg** [comment]
Hi @gbozzetti,
What's the version of your ACF?
Please read this: https://www.advancedcustomfields.com/resources/update_field/
Thanks

**Comment by gbozzetti** [comment]
Hi @airesvsg ,

Version 4.4.9

**Comment by airesvsg** [comment]
Hi @gbozzetti,
Your version already has the `update_field` function, please use it.

Thanks

**Comment by 64276** [comment]
He did use it, and I'm having the same problem.
