### ISSUE TITLE
GET request from wp, only custom field posts needed

### ISSUE THREAD

**Issue by st-small** [airesvsg/acf-to-rest-api#66]
Hi guys! I'm very happy to find this plugin, because all web admins told me that it is impossible to get custom fields in my requests... I'm not web programmer and can't write by PHP (and can't read too...),  I'm writing the app for iOS and need to have GET request like this: 
www.mysite.com/wp-json/wp/v2/posts?offer=true (where "offer" is my custom field) - I need to have posts only with field offer=true.

Thank you very much.

![2016-09-09 17 21 54](https://cloud.githubusercontent.com/assets/1850189/18390649/be0044ea-76b3-11e6-8c25-ad9cb5f6a654.png)

**Comment by airesvsg** [comment]
Hi @st-small,
please add this snippet in your `functions.php`.
```PHP
function rest_api_allow_meta_query( $valid_vars ) {
    $valid_vars[] = 'meta_key';
    $valid_vars[] = 'meta_value';

    return $valid_vars;
}

add_filter( 'rest_query_vars', 'rest_api_allow_meta_query' );
```

http://www.mysite.com/wp-json/wp/v2/posts?filter[meta_key]=offer&filter[meta_value]=1

Thanks

**Comment by st-small** [comment]
Thank you, https://github.com/airesvsg, very much! It is great!

**Comment by rainboxx** [comment]
Could this somehow be integrated into this plugin? I'm asking because the wordpress installation shouldn't be altered to be able to update easily in the future. Also for some hosted wordpress services, changing the `functions.php` might not be possible at all.

**Comment by airesvsg** [comment]
Hi @rainboxx,
I understand your situation, but at this moment I not plan to integrate it.
Thanks

**Comment by rainboxx** [comment]
@airesvsg: If you think the feature might be worth to be integrated I could provide a PR (with some help, since I cannot get the patch to work with 4.7).

If not, can you elaborate why this should not be integrated? I'm not fully aware of the whole architecture at work here.

**Comment by st-small** [comment]
@airesvsg after update my WP, your advices doesn't works... I don't understand but all filters are ignoring and I cant to get filtered fetch at my request. Can you help me?!

TNX.
