### ISSUE TITLE
Not Pulling all ACF Fields

### ISSUE THREAD

**Issue by Radizzt** [airesvsg/acf-to-rest-api#68]
Hello,

I think I install your plugin correctly, but when I try getting the value through a post.
I'm only getting one field for some reason - there should be nine.

http://www.oneupsports.com/wp-json/acf/v2/post/1105
![screen shot 2016-09-09 at 4 11 37 pm](https://cloud.githubusercontent.com/assets/7696084/18401369/375ff148-76a8-11e6-905e-9872a380f4c6.png)

I'm looking at the one field that it's being pull and it doesn't look like i did anything different with that than with the other.

any thoughts?

Thanks

Edit:
I started looking through the other issues and #64 seem to have the solution im looking for.

I'm dynamically inserting new posts, and unless i go in the post and hit "update" the field remain empty like the attached image above.
Afterward it looks like this:
![screen shot 2016-09-09 at 4 16 45 pm](https://cloud.githubusercontent.com/assets/7696084/18401529/dc9836d4-76a8-11e6-808a-eae455aa51a7.png)

Perhaps something can be implemented to fix this issue?

**Comment by airesvsg** [comment]
Hi @Radizzt,
sorry for the delay.

Please follow that issue: https://github.com/airesvsg/acf-to-rest-api/issues/64

Thanks
