### ISSUE TITLE
ACF Relationship with _links object

### ISSUE THREAD

**Issue by adalberth** [airesvsg/acf-to-rest-api#70]
Is it possible to add the _links object to the ACF relationship array objects. Now you only get a GUID on the object and not the REST url. So how do you link to the post?

**Comment by airesvsg** [comment]
Hi @adalberth,
please read this issue: https://github.com/airesvsg/acf-to-rest-api/issues/9
Thanks

**Comment by adalberth** [comment]
@airesvsg Ahh sorry - i didn't see that!

For relationships a create this snippet.. It works, but it could be prettier! 💃 
`php
add_filter( 'acf/rest_api/film/get_fields', function( $data, $request, $response ) {
  $relationships = &$data->data['acf']['relationship'];
  foreach ($relationships as $key => &$relationship) {
    $relationship = [
        'post' => $relationship,
        'data' => get_fields($relationship->ID)
    ];
  }
  return $data;
}, 10, 3 );
`
