### ISSUE TITLE
Filtering by name doesn't return ACF data

### ISSUE THREAD

**Issue by dellabravo** [airesvsg/acf-to-rest-api#73]
When hitting the WP REST API with the name filter instead of the post ID, the ACF relationship fields aren't populated.

Example:

`*/wp-json/wp/v2/opportunity/140` gives all ACF relationship field data

`*/wp/v2/opportunity/?filter[name]=cfo` has the ACF relationship fields, but they are empty

Note that all the other ACF fields come through ok, just not the relationship type ones, maybe because they're serialized array?

**Comment by airesvsg** [comment]
Hi @dellabravo,
Please read this: https://github.com/airesvsg/acf-to-rest-api/issues/24 and https://github.com/airesvsg/acf-to-rest-api/issues/66#issuecomment-245985760

Thanks
