### ISSUE TITLE
Fields with same name are both populated, how to use Field Key in post?

### ISSUE THREAD

**Issue by anagio** [airesvsg/acf-to-rest-api#74]
ACF allows field names and labels to be the same within a group. I've tried posting to the end point with `fields[field_57e804439802a]` but this is not setting the custom field. Only when I use the field name will it be set. The problem is having multiple fields with the same name, they all get populated.

Some of my code....

This works but populates all fields named `testfield`
```
        var fields = {
            "fields[testfield]": "test"
        };
```

This does not work
```
        var fields = {
            "fields[field_57e804439802a]": "test"
        };
```

Why would this not work with a field key? I see that `update_field` at https://github.com/airesvsg/acf-to-rest-api/blob/8a3147aafc3c1b6f7510ab4df19c1b778b069349/lib/endpoints/class-acf-to-rest-api-controller.php#L80

**Comment by airesvsg** [comment]
Hi @anagio,
please rename your field names.
Thanks
