### ISSUE TITLE
ACF Rest calls suddenly only returning 10 rows

### ISSUE THREAD

**Issue by rickrootunc** [airesvsg/acf-to-rest-api#76]
We are using the ACF to REST api to expose a centrally managed staff directory to multiple wordpress web sites. This has been working great until the other day when we updated the wp REST plugin to 2.0 beta 14 and the ACF plugin to 4.4.10

I do not know what the previuos versions were (the person who ran the updates did not make a note of it).

Now, instead of returning all of the staff, it is returning only 10 records - specifically the 10 most recently added.

I don't see any mechanism for restricting the number of posts so I don't know why this would've started happening.

Our ACF to REST plugin is 2.2.1

The json call being used by the front end:

/wp-json/wp/v2/staff?filter[posts_per_page]=-1

I can pass the &per_page parameter but it only allows me to set that between 0 and 100.  The filter seems to be getting ignored as it has no effect what I set that to.

Ideas/Suggestions?

Thanks!

Rick

**Comment by airesvsg** [comment]
Hi @rickrootunc,
please try it:

```PHP
add_filter( 'rest_staff_query', function( $args, $request ) {
    if ( array_key_exists( 'posts_per_page', $args ) ) {
        $args['posts_per_page'] = -1;
    }
    
    return $args;
} );
```

Thanks

**Comment by rickrootunc** [comment]
What file should I put that in and where in the file?

**Comment by airesvsg** [comment]
Hi @rickrootunc,
`functions.php`, puts the snippet in the end of file.

**Comment by mnguye08** [comment]
Hi @airesvsg,
I've tried your solution to put this in functions.php but it doesn't seem to work.
```
add_filter( 'rest_staff_query', function( $args, $request ) {
    if ( array_key_exists( 'posts_per_page', $args ) ) {
        $args['posts_per_page'] = -1;
    }

    return $args;
} );
```
Do you know why?
Thanks!

**Comment by maikel-exitable** [comment]
I am having the same problem, is this something that the module is supposed to do? 

Would like to return all results for every query. Limiting is not an issue in this setup.

**Comment by krishkusuma** [comment]
I got the same error too.
Still retrieve 10 records only after update the functions.php file.
Anyone can help ? Thanks

**Comment by jakeols** [comment]
For anyone else reading this, I've found it's worth it to just write custom rest handlers for when the API limit becomes annoying. You can define them pretty simply.

<b>ex:</b>

```
add_action( 'rest_api_init', function () {
	register_rest_route( '/locations/v1', '/all/', array(
		'methods' => 'GET',
		'callback' => 'locations_rest_functionality',
	) );
} );
```

You can use `wp_query` in your callback and set `posts_per_page = -1`.
