### ISSUE TITLE
/wp-json/acf/v2/ returns rest_no_route

### ISSUE THREAD

**Issue by benbabics** [airesvsg/acf-to-rest-api#77]
Hello,

I am brand new to acf-to-rest-api. I just upgraded  wp-rest-api from v1 to v2 yesterday, and noticed that my acf fields are no longer appearing in the response (it previously did for v1). So, I decided to look at acf-to-rest-api plugin for v2. I'm scratching my head because I'm not getting my expected response when hitting `/wp-json/acf/v2/`. What I'm getting looks like this:

```
{
code: "rest_no_route",
  message: "No route was found matching the URL and request method",
  data: {
    status: 404
  }
}
```

This also happens when I try to GET a post/id such as `/wp-json/acf/v2/post/6303`. I get the following again:

```
{
code: "rest_no_route",
  message: "No route was found matching the URL and request method",
  data: {
    status: 404
  }
}
```

So they seem related. Any help is much appreciated.

**Comment by airesvsg** [comment]
Hi @benbabics,
please regenerate your permalinks.

`Settings` > `Permalinks` > `Save Changes`

Thanks
