### ISSUE TITLE
Square Brackets JSON Array

### ISSUE THREAD

**Issue by hieuiee** [airesvsg/acf-to-rest-api#79]
Hey! How do I go about adding square brackets '[ & ]' on the beginning and ending of the JSON?

i.e.
My JSON currently shows this
`{"tracking_job":"tracking_job_photography"}`

and I'd like it to look like this
`[ {"tracking_job":"tracking_job_photography"} ]`

I've spent a few hours trying to figure it out without any luck. Any help would be much appreciated! :)

Cheers

**Comment by airesvsg** [comment]
Hi @hieuiee,
please try it:

You must replace **{type}** by: post, page, user, term, comment, media, options or custom post type.
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( isset( $data['acf'] ) ) {
        $data['acf'] = array( $data['acf'] );
    }

    return $data;
} );
```

If I want that return in Custom Post Type ( **book** ).
```PHP
add_filter( 'acf/rest_api/book/get_fields', function( $data ) {
...
} );
```

Thanks

**Comment by hieuiee** [comment]
Cheers for the quick reply!

It seems to be partially working. I might not have explained myself clearly enough (my bad)

I'm trying to filter/show only one custom field ( text ) in a page but at the moment, it's (/wp-json/acf/v2/page/{id}/text)  showing up as this;

{"text":"hello"} 

and I'd like it to show;

[ {"text":"hello"} ]

After plugging in your code, it adds square brackets to 
/wp-json/acf/v2/page/{id} only. 

{"acf":[{"text":"hello","text2":"hello2"}]}

However, the filtered page stays the same. Is there any way that those square brackets could be added to the filtered page?

Hope I've explained it better this time round.

Thanks heaps!

**Comment by airesvsg** [comment]
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( is_array( $data ) && ! empty( $data ) && ! isset( $data['acf'] ) ) {
        $data = array( $data );
    }

    return $data;
} );
```
