### ISSUE TITLE
is_plugin_active() function doesn't work correctly when plugins are included from another plugin

### ISSUE THREAD

**Issue by sarukuku** [airesvsg/acf-to-rest-api#8]
I'm building a plugin that converts a blank WP to a mobile application backend in one click. To make things easy for me I'm using a combo of `acf-pro`, the official `wp-api` plugin and your `acf-to-rest-api` plugin. I'm loading all these three plugins *inside* my plugin and this confuses the `is_plugin_active()` function in the `acf-to-rest-api` plugin. The current function tries to look for `acf-pro` and `wp-api` by using the WP `is_plugin_active()` function that checks if the required plugins are activated but only based on the hard coded paths.

Could the "existence" of these plugins be checked in a more general way? My suggestions would be to use something like `class_exists('acf')`and `class_exists('WP_REST_Controller')` instead of the `is_plugin_active()` and hard coded plugin paths. My case might sound a bit special but f.ex. including ACF to a theme is a very popular practice.

I can ofc fork this repository and do the changes I need but I'd prefer not to do such a thing if we could try and find a solution that would fit everyone and get merged to this amazing plugin. To make this easy for you I can prepare a pull request if we can find and agree on a solution.

**Comment by airesvsg** [comment]
Hi @sarukuku,

Please, replace the method ( `is_plugin_active` ) for the below code and check if it works for you.

```PHP
public static function is_plugin_active( $plugin ) {
	if ( ! function_exists( 'is_plugin_active' ) ) {
		include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
	}

	if ( 'rest-api' == $plugin ) {
		$active = class_exists( 'WP_REST_Controller' );
	} elseif ( 'acf' == $plugin ) {
		$active = class_exists( 'acf' );
	} elseif ( 'all' == $plugin ) {
		$active = self::is_plugin_active( 'rest-api' ) && self::is_plugin_active( 'acf' );
	} else {
		$active = false;
	}

	return apply_filters( 'acf/rest_api/plugin_active', $active, $plugin );
}
```

Please, let know if it will work. :wink:

**Comment by sarukuku** [comment]
Seems to work :+1:. Can we get this change in to the plugin?

**Comment by airesvsg** [comment]
Done! :+1: 

Thanks
