### ISSUE TITLE
status 403 after PUT request

### ISSUE THREAD

**Issue by adminko-svk** [airesvsg/acf-to-rest-api#80]
I need to change ACF data, so I am sending via Postman to URL ```/wp-json/acf/v2/page/2/custom_field_test``` ```PUT``` ```JSON``` data (using basic authentication):
```
{
  "fields": {
    "custom_field_test": "hello"
  }
}
```

But I receive:
```
{
  "code": "rest_forbidden",
  "message": "Sorry, you are not allowed to do that.",
  "data": {
    "status": 403
  }
}
```

WordPress is 4.6.1 and plugins are:

- WP REST API (2.0-beta15)
- Advanced Custom Fields (4.4.11)
- ACF to REST API (2.2.1)
- JSON Basic Authentication (0.1)

I've spent a few hours trying to figure it out without any luck. 
Any help would be much appreciated!

Cheers

**Comment by airesvsg** [comment]
Hi @adminko-svk,
you need authenticate.
See more detail here: http://v2.wp-api.org/guide/authentication
Thanks

**Comment by adminko-svk** [comment]
Thank you for your quick response!
I am using basic authentication with `JSON Basic Authentication` plugin.

**Comment by airesvsg** [comment]
Please, send me the link authentication plugin.

**Comment by adminko-svk** [comment]
https://github.com/WP-API/Basic-Auth

**Comment by adminko-svk** [comment]
Or what plugin for authentication do you recommend?

**Comment by airesvsg** [comment]
I can't see any error.
I recommend [OAuth](https://github.com/WP-API/OAuth1).
![postman](https://cloud.githubusercontent.com/assets/396668/19966666/f7ad570c-a1b3-11e6-9e2c-5ce74cb370da.png)

**Comment by adminko-svk** [comment]
Aires, now I get error 500.
I send you a mail. Thank you very much.

**Comment by airesvsg** [comment]
You need to create the field groups.
