### ISSUE TITLE
Edit field registred via PHP

### ISSUE THREAD

**Issue by adminko-svk** [airesvsg/acf-to-rest-api#81]
How can I edit field that is registred via PHP using register_field_group() ?
Or is there another solution to edit custom fields via REST API?

**Comment by airesvsg** [comment]
Hi @adminko-svk,

The same way, look it: 
- [ACF to REST API - Example](https://github.com/airesvsg/acf-to-rest-api-example/) 
- [Fields registered via PHP](https://github.com/airesvsg/acf-to-rest-api-example/blob/master/acf-fields.php#L8)

Thanks
