### ISSUE TITLE
Custom options page

### ISSUE THREAD

**Issue by riveramauro** [airesvsg/acf-to-rest-api#82]
I've created a custom option page like so:

```
acf_add_options_page(array(
		'page_title' 	=> 'Modals',
		'menu_title'	=> 'Theme Modals',
		'menu_slug' 	=> 'theme-modals',
		'capability'	=> 'edit_posts',
		'redirect'		=> false,
		'post_id'		=> 'theme-modals'
));
```

I can't seem to expose the JSON values. I've tried:
```
/wp-json/acf/v2/options/
/wp-json/acf/v2/theme-modals/
/wp-json/acf/v2/options/theme-modals/
```
None of those seem to work. I get `null`. Any pointers?

**Comment by airesvsg** [comment]
Hi @riveramauro,
please try regenerate your permalinks.

The endpoints to access the data
```
/wp-json/acf/v2/options
/wp-json/acf/v2/options/{field-name}
```

Thanks

**Comment by riveramauro** [comment]
After refreshing permalinks with, with:

/wp-json/acf/v2/options, I get "{acf: false}",

and with /wp-json/acf/v2/options/theme-modals, I get "{"them-modals":null}

**Comment by airesvsg** [comment]
You have defined the **post_id** equals **_theme-modals_**, but the default **post_id** is **options**.

Please, use the below filter to change.
```PHP
add_action( 'acf/rest_api/id', function( $id ) {
	if ( 'options' == $id ) {
		return 'theme-modals';
	}
} );
```

Thanks

**Comment by riveramauro** [comment]
Makes sense. Thanks for you help!

**Comment by mieradi** [comment]
Just in case anyone stumbles across this, I get a null return unless I add `/options/options`.

`https://devsite.com/wp-json/acf/v3/options/options/`

or

`https://devsite.com/wp-json/acf/v3/options/options/{option-name}`

hope this helps
