### ISSUE TITLE
Why is the acf data publicly available with this plugin

### ISSUE THREAD

**Issue by yosie123** [airesvsg/acf-to-rest-api#83]
Hello,

First off, I think you made a create plugin.
I use the wp-json api plugin (v2) to access (oauth1) to update our sites data and posts. ACF gives us more flexibilty with the backend custom fields. I was searching for an plugin which gives me the flexibilty to access acf data. So i found your plugin. 
One think i dont understand, why it is possible with GET to get all ACF fields related data? you dont need to be logged in. Example: I go to http://www.mysite.com/wp-json/acf/v2/post/123 the server responds: {"acf":{"testgroup":false,"field1":"blablabla","field2":"blablabla"}}
I expected for clients that are not authenticated with Oauth, something like: {no premission}

**Comment by airesvsg** [comment]
Hi @yosie123,
please use the filter `acf/rest_api/{type}/get_fields` to change return data.

The wildcard {type} can be: post, page, user, term, comment, attachment, options or custom_post_type ( book )

below I'll remove the field **author**:
```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( ! is_user_logged_in() ) {
        unset( $data['acf']['author'] );
    }

    return $data;
} );
```

Thanks

**Comment by yosie123** [comment]
@airesvsg Perfect. Thanks for the example filter with is_user_logged_in(). thats exactly what I was searching for. Thanks for the great plugin and keep it up. you can close this one.
