### ISSUE TITLE
Insert/update ACF Flexible content

### ISSUE THREAD

**Issue by Charkhan** [airesvsg/acf-to-rest-api#84]
Hello,

Is there a way to provide ACF Flexible content with your plugin ? If so, how would you structure it with PHP ?

There is no such example in your live demo.

Thanks for your hard work !

**Comment by airesvsg** [comment]
Hi @Charkhan,
Yes, see in the image below the structure.
![acf-flexible-content](https://cloud.githubusercontent.com/assets/396668/20347764/9b848604-abe9-11e6-9ab5-37f470962afc.jpg)
Thanks

**Comment by Charkhan** [comment]
Thanks for the quick answer !

Worked like a charm, thank you !
