### ISSUE TITLE
Multiple custom options pages

### ISSUE THREAD

**Issue by apatt124** [airesvsg/acf-to-rest-api#85]
I have an issue similar to issue [https://github.com/airesvsg/acf-to-rest-api/issues/82](https://github.com/airesvsg/acf-to-rest-api/issues/82)

However, I have several options pages that I need to access via the API, so this code

````javascript
add_action( 'acf/rest_api/id', function( $id ) {
    if ( 'options' == $id ) {
        return 'theme-modals';
    }
    return $id;
} );
````
does not fully address my issue. What modifications do I need to implement to access multiple custom options pages?

**Comment by airesvsg** [comment]
Hi @apatt124,
this version doesn't support multiple custom options pages, but you can use the code below.
```PHP
add_action( 'acf/rest_api/id', function( $id ) {
    if ( 'options' == $id ) {
    	$available = array( 'theme-modals', 'theme-test' );
    	
    	if ( isset( $_GET['option_id'] ) && in_array( $_GET['option_id'], $available ) ) {
    		return esc_sql( $_GET['option_id'] );
    	}
    }

    return $id;
} );
```

Endpoint: `/wp-json/acf/v2/options/?option_id=theme-modals`

Thanks

**Comment by airesvsg** [comment]
Hi @apatt124,
Yesterday I released a new version ( 3.0.0-beta ).
Please, check it works for you.
Thanks

**Comment by jenessawhite** [comment]
Hey @airesvsg 
I have multiple custom options pages, and would like to use v3, but the new endpoint `/wp-json/acf/v3/options/{id}/` doesn't return any of the expected values. It still returns `{"acf":[]}`

If I switch back to v2 and use the `/wp-json/acf/v2/options/?option_id={id}` then it returns the expected values.

**Comment by airesvsg** [comment]
Hi @jenessawhite,

Please, read it: https://github.com/airesvsg/acf-to-rest-api/issues/184#issuecomment-338277335

Thanks

**Comment by Twansparant** [comment]
> Please, read it: [#184 (comment)](https://github.com/airesvsg/acf-to-rest-api/issues/184#issuecomment-338277335)
> 
> Thanks

This works for one-level options pages, but not for subpages.

> If I switch back to v2 and use the `/wp-json/acf/v2/options/?option_id={id}` then it returns the expected values.

This does work for options subpages.
