### ISSUE TITLE
WP API is caching fields no longer being used

### ISSUE THREAD

**Issue by louisnovick** [airesvsg/acf-to-rest-api#86]
This plugin is working great for me.  The only thing I have noticed, and I'm not sure if this due to this plugin or the WP-API v2 plugin, is that old fields no longer in use still have values get returned when I make api calls to a post.  I have acf fields toggle on and off based on the custom post type category so I was thinking maybe it was just the db caching it or something.  I switched categories and cleared the fields being returned, but they still get returned with the same values none the less.  What am I missing here?

**Comment by airesvsg** [comment]
Hi @louisnovick,
maybe acf cache. https://github.com/elliotcondon/acf/blob/befc63020abba7d0bce27fa2bc67fec0f999b13d/core/api.php#L23

Thanks
