### ISSUE TITLE
ACF Post Object exposed?

### ISSUE THREAD

**Issue by dblodorn** [airesvsg/acf-to-rest-api#87]
Hi @airesvsg !
Trying to to use the post insert field within a repeater- when I access the post via WP REST API all that is returned is the post that is being referred to - "guid" line:

     { "acf": {
       "portfolio": [
        {
          "portfolio_item": {
             "ID": 30,
             "post_author": "1",
             "post_content": "",
             "post_title": "Dain Kim",
             "post_excerpt": "",
             "post_status": "publish",
             "post_password": "",
             "post_name": "dain-kim",
             "post_parent": 0,
             "guid": "https://flatfiles.info/?post_type=website&#038;p=30",
             "menu_order": 0,
             "post_type": "website",
             "post_mime_type": "",
             "comment_count": "0",
             "filter": "raw"
    ...

I can then access the individual post's JSON by going to this url:
https://flatfiles.info/wp-json/acf/v2/websites-api/30

So my question is A - is there support for accessing post objects from within a repeater, and B if not is there a plan for this or would i need to write some additional scripting to handle the repeater and then send another request to the post by using a regex find and replace or something with the "guid" value?

Thank you!

**Comment by airesvsg** [comment]
Hi @dblodorn,
Use the filter `acf/rest_api/{type}/get_fields`.

The wildcard **{type}** can be: post | user | term | comment | attachment | options

```PHP
add_filter( 'acf/rest_api/{type}/get_fields', function( $data ) {
    if ( method_exists( $data, 'get_data' ) ) {
        $data = $data->get_data();
    } else {
        $data = (array) $data;
    }

    if ( isset( $data['acf'] ) ) {
    	// do something
    }

    return $data;
} );
```

Thanks

**Comment by dblodorn** [comment]
Thank you so much for your help! @airesvsg
