### ISSUE TITLE
add_filter on acf/rest_api/id namespace

### ISSUE THREAD

**Issue by Charkhan** [airesvsg/acf-to-rest-api#88]
Hello again,

Ran into an issue when I tried to add a filter for the "acf/rest_api/id". By looking up at the code, I guessed the purpose of it was to alter the ID that you can provide to the ACF rest API routes (it's not explained on the doc).

I'm on a project where I need to "broadcast" post creation/modification/deletion from a 'master' WP to  other 'slaves' Wordpress.

So when I need to do a post update, I wish to provide to the slaves, the 'master' post ID, and get back the ID of the slave I'm requesting. And the  "acf/rest_api/id" filter looked like the best match to achieve my goal.

Here's the filter I added:
```php
add_filter('acf/rest_api/id', function($key) {
    if (!get_posts(['meta_key' => 'master_id', 'meta_value' => $key, 'posts_per_page' => 1]))
        return null;

    return get_posts(['meta_key' => 'master_id', 'meta_value' => $key, 'posts_per_page' => 1])[0]->ID;
}, 10, 3 );
```
I request informations on the slave and it works just fine.

**But now, every time I try to update/insert posts on "slaves", ACF fields are not inserted**

Just comment the above code make it work again.

What am I doing wrong ?

**Comment by airesvsg** [comment]
Hi @Charkhan,
you need to use the filter `acf/rest_api/{type}/prepare_item`.

The wildcard **{type}** can be: post | user | term | comment | attachment | options | custom post type

```PHP
add_filter( 'acf/rest_api/{type}/prepare_item', function( $item, $request ) {
	
	// do something

}, 10, 2 );
```

Thanks

**Comment by Charkhan** [comment]
@airesvsg 

Thanks for the answer !

What I have now....

```php
add_filter('acf/rest_api/post/prepare_item', function($item, $request) {
    $id = $request->get_param('ID');

    if (!$post = get_posts(['meta_key' => 'master_id', 'meta_value' => $id, 'posts_per_page' => 1]))
        return null;

    return $post[0];
}, 10, 2 );
```

It's still not working :(

**Comment by Charkhan** [comment]
Ok I figured out... the prepare_item was useless...

Now I'm having trouble synchronizing data with the "/wp-json/acf/v2/options" endpoint. What structure to send to the API ?

I tried with the exact same structure than inserting post etc... but it's not saving the data...
