### ISSUE TITLE
ACF Rest call - only returns 10 results for every endpoint

### ISSUE THREAD

**Issue by maikel-exitable** [airesvsg/acf-to-rest-api#89]
Is there a way to remove the limit for all requests? I already found this https://github.com/airesvsg/acf-to-rest-api/issues/76 (closed) issue but it does not work for one endpoint if i follow the example.

Maybe there is something i am missing, or even an easier way if it is ok to remove the limit for all.

**Comment by dmajka** [comment]
Unfortunately, the authors of the WP REST api removed the option to return all items at the beta 14 release, and are now limiting to 100 per request for performance reasons. See #[here](https://github.com/WP-API/WP-API/issues/2890) and [here](https://github.com/WP-API/WP-API/issues/2759) for more info. They recommend requesting 100 entries at a time and concatenating. It'd be nice though to have an easy way to grab a cached dump of the whole payload.

**Comment by maikel-exitable** [comment]
Actually, that was exactly what i was looking for. Going above 100 would be perfect on the long run, but for now this is perfect.

I was only getting 10, but 100 for now is allright. Just have to make sure we implement a pagination option then.

Thank you @dmajka !

**Comment by airesvsg** [comment]
Hi @maikel-exitable!

You can create a custom controller... 😄 

```PHP
class My_Custom_WP_REST_Posts_Controller extends WP_REST_Posts_Controller {
	public function get_collection_params() {
		$params = parent::get_collection_params();
		
		if ( isset( $params['per_page'] ) ) {
			unset( $params['per_page'] );
		}

		return $params;
	}
}

add_filter( 'init', function(){
	global $wp_post_types;

	if ( isset( $wp_post_types['post'] ) ) {
		$wp_post_types['post']->rest_controller_class = 'My_Custom_WP_REST_Posts_Controller';
	}	
}, 15 );
```

Thanks

**Comment by markfriday** [comment]
Hi guys,

This doesn't seem to work since Wordpress 4.7.

Any thoughts on how I can fix it?

Thanks,

Mark

**Comment by airesvsg** [comment]
Hi @markfriday,
please read it https://github.com/WP-API/WP-API/issues/2759#issuecomment-251809005 or try it https://github.com/airesvsg/acf-to-rest-api/issues/89#issuecomment-262862145

Thanks

**Comment by Nhaztaljik** [comment]
Any way to do the same thing, but with categories, and pages?
