### ISSUE TITLE
Custom Endpoints

### ISSUE THREAD

**Issue by barcadictni** [airesvsg/acf-to-rest-api#90]
Hi there!

Quick question, How can I include ACF with custom endpoints, diferent namespaces, etc?

**Comment by airesvsg** [comment]
Hi @barcadictni,
you can extend the class base `ACF_To_REST_API_Controller`, see an example: [class-acf-to-rest-api-option-controller.php](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-option-controller.php)

Thanks
