### ISSUE TITLE
getting an acf:false

### ISSUE THREAD

**Issue by barbareshet** [airesvsg/acf-to-rest-api#91]
I know this question has come up a lot here, I've looked into all the answers and still didn't solve my problem.
this is my endpoint
http://80.179.140.91/~shlomit/wp-json/acf/v2/post/20

I did not create an options page but a regular ACF post 

post_type name is projects
show_in_rest => true
rest_base => projects-api

I'll appreciate any help at this point.

thanks

**Comment by airesvsg** [comment]
Hi @barbareshet,
when I access this endpoint `wp-json/wp/v2/posts/20` I receive this status: **rest_forbidden ( 403 )**.
Thanks
