### ISSUE TITLE
Plugin is not working in WP 4.7

### ISSUE THREAD

**Issue by adminko-svk** [airesvsg/acf-to-rest-api#92]
In WP 4.7 is plugin not working anymore. 
I get all records if I am using filter `?filter[meta_key]=xxx&filter[meta_value]=yyy`

**Comment by airesvsg** [comment]
Hi @adminko-svk,
what's your endpoint? `wp/v2/posts` or `acf/v2/post`
Thanks

**Comment by adminko-svk** [comment]
I use `wp` with custom page type - `wp/v2/email`

**Comment by airesvsg** [comment]
https://github.com/WP-API/WP-API/issues/2949
