### ISSUE TITLE
Clone Fields sometimes not shown

### ISSUE THREAD

**Issue by slcr** [airesvsg/acf-to-rest-api#93]
Working example: https://gist.github.com/slcr/ee94fde6f1bc97c64c2d8e17a66926c9
Non-Working example: https://gist.github.com/slcr/f9b00699fcea41d053e2ae8f05cec83e

in the non-working example columns don't get the cloned content, only the `column_width` is shown. posts & products use the exact same custom fields, they vary just in some optional fields.

acf-setup for the columns-field: https://gist.github.com/slcr/d3e8b67eaddf40b74a3e0b9483a6977e

any hints or advices of what is happening here?

**Comment by airesvsg** [comment]
Hi @slcr,
I'll test it today.
Thanks

**Comment by airesvsg** [comment]
Hi @slcr,
please provide me a json file with all fields?
Custom Fields > Tools > Export Field Groups ( selet groups ) > Download Export File
Thanks

**Comment by slcr** [comment]
thanks for looking into it @airesvsg 
here is the json-export: https://gist.github.com/slcr/606212e2d90ff8db4b5537b88f0cb426

**Comment by slcr** [comment]
hey @airesvsg, any progress or any new hints?

**Comment by airesvsg** [comment]
Hi @slcr,
this error is not in my plugin.
![joxi_screenshot_1484014496389](https://cloud.githubusercontent.com/assets/396668/21791469/116db614-d6ca-11e6-8c57-c2333ed9c11f.png)

I use the same functions `get_fields` in my plugin, this above image is redundant.

![joxi_screenshot_1484014686361 1](https://cloud.githubusercontent.com/assets/396668/21791510/6b63ef3a-d6ca-11e6-9132-f55cb0c81997.png)

Please open new thread here: 
https://support.advancedcustomfields.com/

Thanks

**Comment by slcr** [comment]
thanks @airesvsg but i already talked to Elliot Condon.
As i said in my initial post, i see the clone field, but the contents are — sometimes — not shown.

to see a live example: 
`http://cms.koffein.io/wp-json/acf/v2/products/3453/`
-> `columns` / `column` has no content
`http://cms.koffein.io/wp-json/acf/v2/products/3453/modules_and_components/`
-> `columns` / `column` has content

i just can't use the extra field of `modules_and_components` because then other stuff outside of the flexible content is missing.

**Comment by slcr** [comment]
okay, update: it seems to be an odd thing with ACF. 
I happens only when i set the display of the clone-field to `seamless`.
![bildschirmfoto 2017-01-10 um 13 13 33](https://cloud.githubusercontent.com/assets/71357/21805846/9dc43202-d736-11e6-8203-0540e4a6ea23.png)

I already notified Elliot and try to rewrite my sync now.
Thanks a lot for your help!
