### ISSUE TITLE
ACF object missing from related objects

### ISSUE THREAD

**Issue by rainboxx** [airesvsg/acf-to-rest-api#94]
**Issue:** When I define a field as `Relationship`, the JSON returned by the API for the "parent" post doesn't contain the `acf` key for the related items.

**Expected:** When a `Relationship` field is detected, it should not only return the "standard" JSON data from Wordpress but the ACF fields as well.

I can supply a PR if someone helps me to understand the architecture of how WP collects these objects and which hook can modify them.

**Comment by airesvsg** [comment]
Hi @rainboxx,
This isseu has already been solved.
Follow the link: https://github.com/airesvsg/acf-to-rest-api/issues/9#issuecomment-175110946
Thanks

**Comment by rainboxx** [comment]
Hey @airesvsg, thanks for hinting to this solution! I did not find it by searching through the issues.

From my perspective I'd expect this functionality to be integrated into the plugin and available for all types. I did not try this solution yet but from looking at it, related ACF fields will only be added to one specific post type but not all. Looking also at the filter documentation, it seems there's no filter that will be called for all post types. Is that correct?

I'm now going to integrate it temporarily in my setup because I'm not familiar with WP at all so I have to fiddle around with it. Would you accept a PR if I can make it so that the related ACF fields will be attached to relationships?

**Comment by rainboxx** [comment]
@airesvsg I proposed a change that would solve this issue for me. Could you please check and verify the PR? I'd love if this would be integrated into the plugin.

Thanks!

**Comment by rainboxx** [comment]
@airesvsg I proposed a change that would solve this issue for me. Could you please check and verify the PR #95? I'd love if this would be integrated into the plugin.

Thanks!
