### ISSUE TITLE
Ready for Wordpress 2.7?

### ISSUE THREAD

**Issue by kerray** [airesvsg/acf-to-rest-api#97]
Will this plugin work after REST API has been merged into core?

**Comment by airesvsg** [comment]
Hi @kerray,
https://github.com/airesvsg/acf-to-rest-api#acf-to-rest-api

> Exposes [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/) Endpoints in the [WP REST API v2](https://wordpress.org/plugins/rest-api/)
